Raku/doc

- lib/Type/IO/FileTestable.pod
The hard tab had the effect of making the code example be split in the html;
the closing brace was in a separate "code" presentation block.  With this
change the entire code example is in the same presentation block in the
html.
> Replacing hard tab with spaces in code example

- lib/Type/SetHash.pod
I added the union operator to the example code at lines 68 and 74.  I (hopefully) fixed the broken link to the setbagmix page at line 77.
> Added example code and fixed a broken link - fixes #43

- lib/Language/5to6.pod
fixed typo in section "Special matchers generally fall under the <> syntax": surrouned -> surrounded
> fixed typo surrouned -> surrounded

- bin/p6doc
- bin/p6doc-index
Before:
~~~
$ p6doc 
What documentation do you want to read?
Examples: /Users/iv/src/rakudo-star-2015.02/install/bin/p6doc Type::Str
/Users/iv/src/rakudo-star-2015.02/install/bin/p6doc Type::Str.split
~~~
After:
~~~
$ ~/src/doc/bin/p6doc
What documentation do you want to read?
Examples: p6doc Type::Str
p6doc Type::Str.split
~~~
I only tested this on OS X.
I'm not sure we actually want this change, but I opened the PR for discussion.
> Prettier usage output for p6doc and p6doc-index.

- lib/Language/setbagmix.pod
Emphasize the unorderedness of these containers. Avoid calling them "lists".
Add some words about immutable/mutable variants.
> Emphasize unorderedness of "Sets, Bags, and Mixes".

- lib/Language/variables.pod
The context used to determine whether item or list assignment used is
a bit tricky. Added detailed explanation and examples.
> Clarify item vs list assignment in Variables

- bin/p6doc
`$*TMPDIR` will follow the operating system's best practices for
temporary file management
> Use $*TMPDIR to create temporary files

- lib/Language/modules.pod
This is simply as I understood it from experimenting and reading s10 and s11. Not sure if some of it wasn't rakudo specific.
> Increased scope of modules.pod by adding "Creating and Using" section

- lib/Language/regexes.pod
This is mostly just lookbehind copied and tweaked so it's accurate for lookahead.
> Document lookahead assertions

- lib/Language/grammars.pod
Escape single-quote in string in sample code
> Fix grammars.pod unescaped quote mark in string

- lib/Language/testing.pod
To signify the end of a test file without using a plan, we used to use `done()`. This has since become `done-testing()`.
> done() has become done-testing()

- t/pod-convenience.t
- t/typegraph.t
This also fixes the below test failure:
$ panda install p6doc
==> Fetching p6doc
==> Building p6doc
==> Testing p6doc
t/pod-convenience.t .. 
Failed 1/10 subtests 
t/pod-htmlify.t ...... ok
t/typegraph.t ........ ok
Test Summary Report
-------------------
t/pod-convenience.t (Wstat: 0 Tests: 9 Failed: 0)
Parse errors: Bad plan.  You planned 10 tests but ran 9.
Files=3, Tests=21, 30 wallclock secs ( 0.20 usr  0.03 sys + 26.77 cusr  1.00 csys = 28.00 CPU)
Result: FAIL
test stage failed for p6doc: Tests failed
in method throw at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/runtime/CORE.setting.moarvm:1
in method install at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/lib/Panda.pm:142
in method resolve at /home/cschwenz/.rakudobrew/moar-nom/install/share/perl6/site/l …
> As we have a plan, the deprecated "done;" can be removed.

- lib/Type/Cool.pod
Fixes https://github.com/perl6/doc/issues/143 . Change sine to cosine.
> Update cosine wikipedia link with correct text

- doc/Language/syntax.pod
Blob literals are described in S02 but the section in syntax.pod uses
the wrong syntax and blob literals don't appear to be implemented in
Rakudo or tested for in Roast.  Avoid confusion, remove the section.
> Remove blob literal section.

- doc/Language/modules.pod
A simple clarification that is export appear after a subs args
> Make clear that is export should appear after function args list

- doc/Language/control.pod
- htmlify.p6
```
1. Added X<> blocks around everything control.pod (separating via ' '
instead of '/'. '/' conflicts with url path atm)
2. Made X<if|control flow> work as shorthand for X<if|control flow,if> in htmlify.p6
3. Got rid of extra `while` heading, it was already documented in `while/until`
```
Making PR just incase 2. is not desirable. I X<>'d everything except for LABELs as "control flow".
> Made headings in control.pod searchable

- doc/Language/5to6-nutshell.pod
- doc/Language/5to6-perlop.pod
- doc/Language/control.pod
- doc/Language/objects.pod
- doc/Language/quoting.pod
- doc/Language/subscripts.pod
- doc/Language/syntax.pod
- doc/Type/Block.pod
My brief research suggests that "braces" eq "curly braces" is American-English, so I figure we should disambiguate globally.
> Find all the references to curly braces and make them consistent

- doc/Language/regexes.pod
Recent changes allowed 1^..^10 non inclusive range syntax as general quantifiers in regexes. These were documented.
> Document recent changes to allow non-inclusive ranges as quantifiers

- doc/Language/classtut.pod
Due to first example contains custom `new` it may give impression that writing `new` is something that programmer want to do. Maybe it would be good to mark it as non standard behavior and say that probably want to write build method?
Or maybe better to close this pull request and rewrite this tutorial in way that will not contain neither BUILD nor new at start. Perl has many ways to initialize attributes without them and should be shown first
Example question http://www.nntp.perl.org/group/perl.perl6.users/2015/10/msg2309.html
> Comment about new method to not confuse new users

- lib/Language/classtut.pod
The old link was to `#Object Construction` but the live page has an underscore in place of space.
> fix anchor link

- doc/Language/5to6-nutshell.pod
Not sure how "item" got in here, as it's not used anywhere else in this context. So, reverting to the more traditional "scalar".
> Changed "item" to "scalar" in section on scalar sigils

- doc/Language/io.pod
- doc/Type/IO/Handle.pod
Most people will get to know .lines from the Input/Output chapter in the Language section of the documentation. It should be stated there that this method will exclude the new line separator.
> Add info exclusion new line reparator by .lines + fix typo in example

- doc/Language/functions.pod
"Very often, a re-dispatch passes the same argument along that the caller received, so there is a special routine for that: callsame.G"
=> 
"Very often, a re-dispatch passes the same argument along that the caller received, so there is a special routine for that: callsame."
> Remove typo

- doc/Language/nativecall.pod
This commit clarifies that the CStructs of NativeCall are always pass by reference. 
This wasn't immediately clear to me when I worked on Compress::Brotli, leading to some odd behaviour.
> Clarify that CStructs are exchanged by reference

- doc/Type/List.pod
clarify that tail always returns a Seq as its signature already correctly shows
> fix tail docs

- .travis.yml
- README.md
This PR extends the travis configuration to also run make html.
I didn't commit this directly because it extends the travis build time from 11 min to **40 min**.
The Pro's are that issues such as  #227 and #240 and #241 will be immediately noticed when they arise.
The Con's are that this duplicates some info captured in the build logs http://doc.perl6.org/build-log/?C=M;O=D  and slows down the CI system substantially
> Travis runs make html

- htmlify.p6
> Remove some unneeded unspace

- doc/Language/faq.pod
Reason: rational numbers are not floating point and most math functions yield a Num.
> Clarified item on numeric computation.

- bin/p6doc
Adds `-n` flag which pipes the output into `cat` instead of a pager.
> Add -n flag for no pager

- bin/p6doc
Previously would just revert to `more`/`less` when faced with a method/routine,
now it properly passes the flag along to `MAIN` or `show-docs`.
Also wondering if `type` would do the same thing in Windows.  Anyone able to confirm? I could add another ternary like L57 i.e.,
```perl6
($*DISTRO.name eq 'mswin32' ?? 'type' !! 'cat')
```
> Allow -n flag on method/routine docs

- doc/Type/Hash.pod
added examples of the other two forms of calling, and documented some non-obvious behaviour of what perl5 programmers might expect from fat commas
> clarifying push usage

- bin/p6doc
Made original ternary more idiomatic as per @jnthn's comment in
PR #311.  Added another ternary to support no-pager mode in Windows.
Please confirm that `type` works as `cat` in this situation under Windows.
I did some research last night and another alternative might be `findstr "^"` but that seems a bit hackish, would prefer to use `type` if possible.
> Update Windows support in show-docs sub

- doc/Language/operators.pod
Some of the meta operator documentation is repeated in the infix operator sections. This makes the cross section match the other meta operators, though.
> Cross meta operator

- template/header.html
The search field autofocus provides a very bad UX on mobile (I tested android/firefox) - causing the virtual keyboard to open on every new page load.
It also breaks the desktop/firefox feature "Search for text when I start typing", whereby typing no longer searches within the page by default.
> remove 'autofocus' from search input field

- doc/Language/operators.pod
Mostly, this just adds `X<>` tags, but sometimes adds a name for the operator if it's missing.
> Index operators

- doc/Type/Signature.pod
So it fails for the right reason.
> wont -> won't

- doc/Language/operators.pod
Reversed operators are taught before operator reduction, so give an example that does not depend on operator reduction
> Provide a simpler example for reversed operators

- Build.pm
In windows File::Find::&find returns files with backslash (\\) separator, so $dest.split fails to find '/doc' in them.
See:
```
> say $dest, '=>', $dest.split("$workdir/doc")[1];
C:\rakudo\tests\doc\doc\Type\X\Syntax\Signature\InvocantMarker.pod=>Nil
> say $dest, '=>', $dest.split("$workdir\\doc")[1];
C:\rakudo\tests\doc\doc\Type\X\Syntax\Signature\InvocantMarker.pod=>\Type\X\Syntax\Signature\InvocantMarker.pod
```
> Fix Build.pm for proper Windows support

- doc/Type/Regex.pod
> Bool() doesn't return a Match object.

- doc/Type/Supply.pod
Also, emit() is called on a Supplier rather than Supply.
> replace Supply.new in grep and map

- doc/Type/Tap.pod
at line 60 `method closing(Tap:D:)'  changed into 'method close(Tap:D:)'
> repairing a typo

- doc/Language/operators.pod
The sample definition for "~" was the same as that for "-"
> Fixed definition for ~

- doc/Language/5to6-nutshell.pod
These headers had incorrect markup and were not displaying as such. Now they are fixed, but the is the content up to date, or should it be marked as TODO?
> Fix markup in nutshell headers

- doc/Language/operators.pod
I left out ==>> and <<== since they are not implemented in Rakudo.
> Add documentation for pipeline operators

- doc/Language/modules-extra.pod
> Replace a dead link

- doc/Language/testing.pod
- doc/Language/traps.pod
Add a note about Test being a core module.  Also add an example of a user-supplied tolerance for numerical testing.
I find these additions helpful. It isn't clear in current docs that Test is a core module, and thus a casual user has to search a while for its source.  A section on core modules would be helpful, perhaps referenced on the page where the external modules are listed: <https://modules.perl6.org/>.
Another place to reference them would be to add another category, "Core Modules," on this page: <https://doc.perl6.org/>
> add example of a user-entered tolerance; emphasize Test is a core module

- doc/Language/unicode_texas.pod
I think we should add a note about best practice:  for portable Perl 6 code, use of non-ASCII characters for operators and mathematical operations is not recommended.
> add some examples; format some text for ease of maintenance

- doc/Language/regexes.pod
Trivial change to avoid unterminated regex in an example.
> Add missing matching "/" at the end of regex

- doc/Language/control.pod
Based this on Brad Gilbert's example here: http://stackoverflow.com/a/37064186/215487. I recommend further elaboration by someone who knows more about it than I do.
> Added samewith

- bin/p6doc
Lifted @opts to an outer scope so it could be seen in another spot it was used.
> @opts compilation error fix

- doc/Type/Str.pod
I think that there is no reason to use the list for the arguments of the printf subroutine.
It will confuse those who read the following section.
https://doc.perl6.org/type/Signature#Slurpy_%28A.K.A._Variadic%29_Parameters
And they will think that "The printf subroutine in Perl 6 is different from C-style printf".
> Fix printf arguments

- doc/Language/syntax.pod
Added language to the description of how identifiers are formed to indicate that an embedded quote or hyphen must be followed immediately by an alphabetic character.
> Added alphabetic-after-hyphen-or-quote restriction to Identifier

- htmlify.p6
Before this change,
http://doc.perl6.org/type/Pod::Item
```
Pod::Item inherits from class Pod::Block, which provides the following methods:
```
*Pod::Block* links to http://doc.perl6.org/type/Pod%3A%3ABlock
Ideally (not actually tested w/ a build, although *star-m:* approves of the general code) this should result in links to http://doc.perl6.org/type/Pod::Block
> htmlify: do not escape :: in site local links

- CONTRIBUTING.md
CONTRIBUTING was missing the need to install Python dev components if they aren't already installed, before installing Inline::Python
> added blurb about python-dev in CONTRIBUTING

- doc/Language/5to6-perlsyn.pod
I'm not sure this works. If someone can confirm it does, I'd appreciate it.
> use pod link instead of url for 5to6-nutshell

- htmlify.p6
In order to speed up the doc generation the program precompiles pod files
into the directory precompiled. The code in the sub extract-pod loads the
precompiled files but if it detects that a pod file has been changed it
calls the method precompile in CompUnit::PrecompilationRepository. The
problem is that the precompile method checks if the file, that it is being
asked to recompile, exists in the repo, and if it does it won't recompile
it unless the named parameter :force is set to True. My suggested
change is that we set :force => True when calling the precompile method.
> Fix for issue https://github.com/perl6/doc/issues/545

- htmlify.p6
- lib/Perl6/TypeGraph/Viz.pm
Convert the "Processing $dir Pod files ..." section to a bunch of start()s and await()s. Convert the "Writing [type graph images, specialized visualizations] to html/image" section to a bunch of Proc::Async.new.start()s, and awaits(). 
For me, this brings "time perl6 htmlify.p6 --no-highlight" from 6 min to 1.5 min. However, in my experience, the async/concurrency parts of Rakudo are definitely kind of weird crash prone, and this change does produce the occasional segfault.
> Parallelize a bunch of htmlify.p6

- doc/Language/variables.pod6
Explain the current default limit on hyperoperators and methods.
> How to increase the maximum threads in $*SCHEDULER

- doc/Language/regexes.pod6
Correction replaced second smartmatch with double asterisk. Now the statement is true as advertised.
> syntax correction

- README.md
- bin/p6doc
Hi,
The first example in the README wasn't working for me (rakudo 2016.06).  Setting PERL6LIB seems to fix it.
best
Brian
> README example needs PERL6LIB to be set

- doc/Language/5to6-nutshell.pod6
- doc/Language/functions.pod6
- doc/Language/glossary.pod6
- doc/Language/grammars.pod6
- doc/Language/objects.pod6
- doc/Language/variables.pod6
- doc/Type/Signature.pod6
1.Entries that just point to wiki were removed(except MoarVM, since it's definitely Perl6-specific).
2.Entries which are already described were removed.
This is a part of https://github.com/perl6/doc/issues/728#issuecomment-234317210
> Glossary cleanup

- doc/Language/operators.pod6
In the spirit of https://github.com/perl6/doc/issues/728, adding operator classifications to the index.
> add operator classifications to the Index

- doc/Type/Bool.pod6
I first encountered the method "succ" today, and it was a method on Bool. At first I misunderstood it to mean "success", and wondered what type of failure or disaster "pred" stood for. Then I discovered that "succ" means "successor" and "pred" means "predecessor" and that they seem to totally make sense if we think of Bool in terms of it consisting of two possible enums.  So, that's what I tried to explain, but I would really like someone that feels more comfortable with this topic to please review my proposed changes (and please improve them if needed), before merging this pull request. (I could have committed directly, but I wanted someone to review this first.)
> Bool.succ, .pred methods explained (please review)

- doc/Language/glossary.pod6
According to https://github.com/perl6/doc/issues/728 discussion, this is a patch that removes glossary items which just point to wikipedia pages.
**Should we remove them or not is still a debatable question, so don't merge this "Just because".**
Opinions are still needed.
> Second part of entries cleanup

- assets/sass/style.scss
- html/js/main.js
Smooth css animation for TOC. This animation isn't based on (max-)height. The only JS part needed is to change css classes, should work with most browsers.
> Css-based TOC animation

- doc/Language/5to6-nutshell.pod6
- doc/Language/functions.pod6
- doc/Language/list.pod6
- doc/Language/unicode_entry.pod6
- doc/Language/variables.pod6
- doc/Type/Any.pod6
- doc/Type/Array.pod6
- doc/Type/Attribute.pod6
- doc/Type/Bag.pod6
- doc/Type/BagHash.pod6
- doc/Type/Baggy.pod6
- doc/Type/Block.pod6
- doc/Type/Capture.pod6
- doc/Type/Cool.pod6
- doc/Type/Hash.pod6
- doc/Type/IO.pod6
- doc/Type/Iterable.pod6
- doc/Type/Junction.pod6
- doc/Type/List.pod6
- doc/Type/Metamodel/C3MRO.pod6
- doc/Type/Metamodel/ClassHOW.pod6
- doc/Type/Metamodel/MultipleInheritance.pod6
- doc/Type/Mix.pod6
- doc/Type/MixHash.pod6
- doc/Type/Range.pod6
- doc/Type/Rat.pod6
- doc/Type/Set.pod6
- doc/Type/SetHash.pod6
- doc/Type/Sub.pod6
- doc/Type/Whatever.pod6
See https://github.com/perl6/doc/issues/761 for details.
> Almost all example outputs were changed to literal versions

- doc/Type/Int.pod6
Description of msb was slightly misleading, as the indexing referred to is always from the right.
Clarified both lsb and msb.
> Clarify description of lsb, msb

- html/js/main.js
We already decided at https://github.com/perl6/doc/issues/686 that the delay should be removed anyway, since it has no sense. Now someone have to just remove it's remainder. After this original issue can be closed.
> The TOC animation was removed

- doc/Language/nativecall.pod6
The ['Basic use of Pointers' section of the Native Calling documentation](https://docs.perl6.org/language/nativecall#Basic_use_of_Pointers) previously read:
```
sub my_version(int32 is rw, int32 is rw) is native('foo') { * }
my_version(my int32 $mayor, my int32 $minor); # Pass a pointer to
```
I changed both instances of 'mayor' to 'major'.
> Change 'mayor' to 'major' in my_version pointers example

- htmlify.p6
This should address  #631.
I'd rather someone else consider it (the output does change, it becomes wordier).
> work around duplicate id= anchors

- CONTRIBUTING.md
- doc/Type/Any.pod6
- doc/Type/Array.pod6
- doc/Type/Attribute.pod6
- doc/Type/Bool.pod6
- doc/Type/IO/Socket/Async.pod6
- doc/Type/Label.pod6
- doc/Type/Metamodel/AttributeContainer.pod6
- doc/Type/Numeric.pod6
- doc/Type/Proc/Async.pod6
- doc/Type/RatStr.pod6
- doc/Type/Setty.pod6
- doc/Type/Signature.pod6
- doc/Type/X/AdHoc.pod6
- doc/Type/X/Anon/Augment.pod6
- doc/Type/X/Proc/Async.pod6
- doc/Type/X/Syntax/Regex/Adverb.pod6
- util/extract-examples.p6
See https://github.com/perl6/doc/issues/794#issuecomment-237981574
Firstly, cast @gfldex, since he is the main inventor of our doc-compiling project.
Since we need to compile signatures(errors occur there too) we need some method/routine/sub body to compile it without error. The thing is, we don't want reader to see this ugly `{}` empty method body.
Because of that, using @coke advice, I've implemented this option. If you write it like this:
```
=begin code :signature
method some(Bar)
=end code
```
or even like that
```
=begin code :signature
method some1(Bar)
method some2(Bar)
=end code
```
empty brackets will be added automatically(in second case, for every string respectively).
My English is less than awesome(I guess, it really is), so I'll be really grateful if someone will fix up my …
> New pod config option: 'signature'

- CONTRIBUTING.md
- doc/Type/Any.pod6
- doc/Type/Array.pod6
- doc/Type/Attribute.pod6
- doc/Type/Bool.pod6
- doc/Type/IO/Socket/Async.pod6
- doc/Type/Label.pod6
- doc/Type/Metamodel/AttributeContainer.pod6
- doc/Type/Numeric.pod6
- doc/Type/Proc/Async.pod6
- doc/Type/RatStr.pod6
- doc/Type/Setty.pod6
- doc/Type/Signature.pod6
- doc/Type/X/AdHoc.pod6
- doc/Type/X/Anon/Augment.pod6
- doc/Type/X/Proc/Async.pod6
- doc/Type/X/Syntax/Regex/Adverb.pod6
- util/extract-examples.p6
Reverts perl6/doc#814
It was decided to don't mix the logic and the presentation, hence the examples code extractor should detect and complete signatures by itself.
@tbrowder++
> Revert "New pod config option: 'signature'"

- doc/Language/5to6-nutshell.pod6
Following https://docs.perl6.org/language/terms#index-entry-constant_%28Terms%29: 
"Constants are declared with constant and do not require a sigil"
> Remove sigil from perl6 constant in accordance with the Term doc

- doc/Language/operators.pod6
> Fix typo from assoc<none> to assoc<non>

- doc/Language/functions.pod6
It's preventing a code sample from rendering.
> Fix a typo in functions.pod6

- doc/Type/Signature.pod6
`X<C<;;>|;;>` seems incorrect style and this index is broken
> Revert "Add an index for ;;"

- doc/Type/Signature.pod6
Reverts perl6/doc#844
`X<C<<;;>>|;;>` is the incorrect form. 
Sorry for reverting many times.
> Revert "Fix a ;; index again (use C<<;;>>)"

- doc/Language/testing.pod6
Clarify to refer to the done-testing method.
> Remove references to 'done' method (obsolete)

- doc/Type/IO/Handle.pod6
- doc/Type/Str.pod6
- xt/trailing-whitespace.t
doc/Type/IO/Handle.pod6
+ add brief description of 'printf'; reference
format details in 'doc/Type/Str.pod6'
doc/Type/Str.pod6
+ move 'printf' format details to 'sprintf'
+ remove 'printf' function and move it to 'doc/Type/IO/Handle.pod6'
xt/trailing-whitespace.t
+ add line number for the affected file
> Changes to files:

- doc/Type/Str.pod6
ref Str sprintf method/funtion
> add note about current state of the implementation

- doc/Language/syntax.pod6
These examples with trailing dollar symbols seems incorrect.
```
$ perl6 -e 'sub alignment(+@l) { +@l };$'
WARNINGS for -e:
Useless use of unnamed $ variable in sink context (line 1)
```
> Delete trailing dollar symbols

- doc/Language/variables.pod6
#906 - I moved a paragraph up to make it clear what code sample it belongs to.
> Fixed confusing wording in the state variables docs

- doc/Language/glossary.pod6
> Commented out :rotate adverb example, add back when it works. Fixes #895

- doc/Language/objects.pod6
"Roles can by anonymous" -> "Roles can be anonymous"
> Fixed small typo

- doc/Language/exceptions.pod6
tried to make it clear what happens with the code following after the CATCH blocks …
> Exceptions handlers and enclosing blocks.

- doc/Type/List.pod6
Also documents the :&with parameter to zip.
> Fix #382: Add docs for cross and X

- doc/Type/Signature.pod6
I hope this makes the difference between \*@, \**@, and +@ more clear. I also hope my descriptions are correct. I believe they are more correct than what was previously present.
> Fix #914: An attempt to clarify slurpy conventions

- doc/Language/classtut.pod6
Looked to see if "chapter" occurred anywhere else too. It did not.
> Fix #889: Nix "previous chapters" sentence

- doc/Language/concurrency.pod6
Explains the Promise statuses in the concurrent documentation page.
> Explain the Promise available statuses.

- doc/Type/Attribute.pod6
> Fix the example of the Attribute.type method

- doc/Language/5to6-perlop.pod6
- doc/Language/5to6-perlvar.pod6
- doc/Type/IO/Notification.pod6
Per the suggestion of issue #619, this removes some weak language.
> Remove some 'seems' usage

- doc/Language/about.pod6
the first example "=head2" block was spelled as "d2" instead of "=head2" which probably did actually blow some minds... it at least caused a misfire in mine.
(fixes apparent mistake from https://github.com/perl6/doc/commit/fb947c098cd6e9cec6874f5d77d38cee08f6a7a1 )
> fix typo in doc about how to fix typo in doc, doc

- doc/Language/classtut.pod6
This method was referred to as the second method, which was confusing since the method before it was also referred to as the second method. Removed the ordinal; just use the name, for future-proofing.
> minor wording fix

- doc/Type/Cool.pod6
The example was obviously corrupted with redundand whitespace cleanup commit.
VynceMontgomery++
> Fix of the example code

- doc/Type/List.pod6
Prepending a zero to the result is unlikely to be desired.
> Remove supplying explicit identity from produce examples. 

- doc/Language/syntax.pod6
Belief in negative numeric literals creates false expectations regarding precedence conflicts (see #971)
> Clarifications on numeric literals

- doc/Language/grammar_tutorial.pod6
Edits to the Grammar Tutorial. I've attempted to tighten up the description of how the proto token works, and specifically focus on the utilisation of the ``<sym>`` token. I also removed the use of ``$<command><sym>`` in the Grammar Actions class, using instead just ``$<command>``.
Making a PR for this, since there maybe a bit of discussion on this. I've checked over and over again, that my statements are in tune with what the proto-regex is doing. I'm happy to receive comments to the opposite however.
I've built the html docs on my local machine and the grammar_tutorial looks good.
> Grammar Tutorial : attempt to tighten up the description of how the proto token works.

- doc/Language/testing.pod6
Block of text immediately above removed lines is identical.
> Remove duplicate done-testing text

- doc/Language/quoting.pod6
The original example had very strange behavior; not sure how to
document this:
Q:w { [ ] \{ \} } eqv ('[', ']', '{', '}') # False
> Q:w { [ ] \{ \} }.perl
("[", "]", "\\\{\\}")
> Fix example that mixed up q:w and Q:w

- doc/Type/Any.pod6
- doc/Type/Bag.pod6
- doc/Type/Date.pod6
- doc/Type/IO.pod6
- doc/Type/IO/Handle.pod6
- doc/Type/IO/Path.pod6
- doc/Type/Mix.pod6
- doc/Type/Mixy.pod6
- doc/Type/Nil.pod6
- doc/Type/Set.pod6
- doc/Type/Setty.pod6
- t/return-type.t
Here are two commits:
* First makes the consistent types consistent.
* Seconds adds a test to check it automatically.
Questions and reviews are welcome!
It closes https://github.com/perl6/doc/issues/1024, see it for a previous discussion.
> Consistent return types

- doc/Type/Dateish.pod6
- doc/Type/Hash.pod6
- doc/Type/Int.pod6
- doc/Type/List.pod6
- doc/Type/Real.pod6
- doc/Type/Regex.pod6
- doc/Type/Str.pod6
- doc/Type/WrapHandle.pod6
It includes such types of fixes:
1)Missed semicolons;
2)Typos;
3)Endless code without :skip-test;
4)Convert flags table to actual table, not code.
Review is welcome.
> Small bunch of changes to make examples compileable.

- doc/Language/traps.pod6
Fixed typo in "Traps". Changed variable name "$arg" to "$list" so that it matches the declaration above it.
> Fixed typo in "Traps". Changed variable name.

- doc/Type/Sub.pod6
Added explanations and examples to document what `is default` does for Subs. This is to fix #1040.
> Document `is deafult` for Subs

- doc/Type/Sub.pod6
- doc/Type/Variable.pod6
This adds a header to the 'is default' section of the Sub type so that it is indexed. The 'is default' section for variables has also been changed a bit so that it is in the same format as the Sub one.
> Edit headers to 'is default' sections

- README.md
So that if you are a rakudobrew user or simply don't have p6doc
available in your path can start straight away to use it. Refs to
perl6/doc#1117 and eventually closes #1117 if accepted.
> Adds quick installation instructions in README.md

- doc/Language/functions.pod6
And, I made the output look like the that for the 
other examples in that section. Note that those 
examples have extra spaces after "\n" that aren't 
part of the actual output.
> Part of the call with example was marked as output

- doc/Language/grammar_tutorial.pod6
The current grammar allows '/product/update7/notify' to parse as well as '/product/update/7/notify'.  This change restricts to second case.
> group optional slash(/) and data so data does not parse without slash

- doc/Language/modules.pod6
- template/search_template.js
First fix is related to https://github.com/perl6/doc/issues/1050 - limit results of search to 50 or something like that.
I just used "default" google way to limit results in autocomplete plugin and tested it for work - nothing special.
Second fix is related to this minor issue - https://github.com/perl6/doc/issues/550. I just made it searchable. It still lacks of documentation, but we have two another issues about this matter: https://github.com/perl6/doc/issues/764 and https://github.com/perl6/doc/issues/551. This is a temporary link until someone great enough will write a paragraph about meta-document with its own header.
> Two minor fixes

- htmlify.p6
- template/type-graph.html
For consideration.
Untested, as 'make htmlify' is insanely slow on my particular machine at the moment. Should resolve #1063 if it's accepted.
> Don't generate .png typegraph files

- doc/Language/about.pod6
- doc/Language/classtut.pod6
- doc/Language/concurrency.pod6
- doc/Language/exceptions.pod6
- doc/Language/experimental.pod6
- doc/Language/faq.pod6
- doc/Language/glossary.pod6
- doc/Language/grammars.pod6
- doc/Language/io.pod6
- doc/Language/ipc.pod6
- doc/Language/list.pod6
- doc/Language/modules.pod6
- doc/Language/objects.pod6
- doc/Language/operators.pod6
- doc/Language/packages.pod6
- doc/Language/performance.pod6
- doc/Language/quoting.pod6
- doc/Language/regexes.pod6
- doc/Language/setbagmix.pod6
- doc/Language/subscripts.pod6
- doc/Language/syntax.pod6
- doc/Language/terms.pod6
- doc/Language/typesystem.pod6
- doc/Language/unicode.pod6
- doc/Language/unicode_entry.pod6
- doc/Language/unicode_texas.pod6
- doc/Language/variables.pod6
- util/extract-examples.p6
* Make many examples compile by adding semicolons, adding actual test data, etc.
* Add `:skip-test` directive to many examples. For further explanation see https://github.com/perl6/doc/issues/776.
* Use `table` instead of plain code where appropriately;
* Reformatting of some old examples.
Sadly, this is not the end, just some preparation work; My further plan is:
* To reformat results in this section too, just as for Type/.
* To write an addition to the contribution guide about the output style.
* To close this big issue.
I wanted this to be merged quickly to prevent conflicts, since this work is slow and our commits to master are everyday thing. After that, I will be able to continue my work in a small chunks directly into the master to be closer to upstream.
> Language section examples reworking (part two)

- doc/Language/operators.pod6
- xt/return-type.t
No test-skipping where possible, no `proto`, no `returns`, see commit messages to find links to appropriate issues.
> Operators reformat

- doc/Language/regexes.pod6
This PR is heading to deal with our absence of `~` character explanation in regexes.
Firstly, I just copied a description from https://design.perl6.org/S05.html#New_metacharacters and polished it a bit.
I wasn't able to find traces of this `:dba` adverb, is it alive and undocumented? The first paragraph of explanation seems good for me, but the further part needs clarification and proving.
Also, much appropriate examples will be good to have.
~~**Do not merge this yet, though reviews are needed.**~~
> Draft of tilde character explanation

- doc/Language/grammar_tutorial.pod6
Would invite feedback, suggestions for changes.
> Did some extensive editing of the grammar tutorial.

- doc/Language/operators.pod6
- doc/Language/unicode_texas.pod6
Rakudo PR: https://github.com/rakudo/rakudo/pull/1032
Tests: https://github.com/perl6/roast/pull/249
> Docs for ≤ ≥ ≠ unicode ops

- doc/Type/List.pod6
Sync with latest rakudo definition for `List`
> doc/Type: correct List definition

- doc/Language/operators.pod6
This documents the behavior implemented in:
https://github.com/rakudo/rakudo/commit/cb25b2f475f31335d77d018474482aceec2c74de
and
https://github.com/rakudo/rakudo/commit/be141b8d9bddc9798db6f11f70cdb117b7309526
> Document the infix method call operators

- doc/Language/5to6-perlfunc.pod6
"shell and exit" are poor substitutes for exec in some common
situations. Add language to 5to6-perlfunc to explain these situations
and suggest NativeCall if they pertain.
Also note that most Unixes have no single "exec" function exactly (Perl
5 automagically dispatches the right one for the situation).
> 5to6: Add caution about `exec` workarounds

- doc/Language/5to6-perlfunc.pod6
I apparently managed to hit the transpose key a few times accidentally
right after spell-checking...
> 5to6-perlfunc: Fix typo

- doc/Language/ipc.pod6
- doc/Language/pod.pod6
Per discussion on IRC and SO:
http://stackoverflow.com/questions/43199427/why-doesnt-perl-6s-try-handle-a-non-zero-exit-in-shell
> Added a note about run/shell exceptions due to non-zero exits

- doc/Type/Failure.pod6
Something I learned today as part of code review. Thought it might be useful in the documentation.
> Document that Failure.handled is an lvalue

- doc/Type/IO/Handle.pod6
Fix grammer around IO::Handle.getc.
> Fix grammer around IO::Handle.getc.

- doc/Language/traps.pod6
As discussed in #992 there are a few possible traps in Cool, especially with regard to Lists. Some of these behaviors may change, but while they work this way, let's document them.
> Document some of the Cool traps

- doc/Language/traps.pod6
While browsing the traps section I came across the examples traps in "quotes and interpolation", and the "Perl 6 understands that as ..."  answers looked all wrong to me.  Here are my suggested corrections.
FWIW, the "You can avoid those problems ... "  section looks equally confusing to me -- I know Perl 6 (or think that I do) and yet I have to really work to figure out what the alternative is accomplishing.  Jumping straight into qq[] and :c feels very line-noisey to me.
To me some much simpler alternatives might be:
```
"$foo\<html></html>"
"{$foo}<html></html>"
"{$foo}(" ~ @args ~ ")"
"$foo\(@args[])"
```
Pm
> Correct Perl 6 interpretation of trap examples.

- doc/Language/faq.pod6
Explained how one may encounter errors with immutable objects using `map` and gave examples of how to work around the issue.
> How to work around immutable string issue when using map

- doc/Language/syntax.pod6
I've modified the explanation to focus more on the ending blocks than on the ending semicolon. This is to make improvements toward resolving (or at least mitigating) concerns with issue #1471. Also included an example of implied separator rule with a colon method call.
> Implied separator rule: focus on ending blocks (instead of the curly brace itself)

- doc/Language/syntax.pod6
> Cleaning up "Separating statements by semicolons"

- doc/Language/traps.pod6
I am really not sure if we planned this, but looking on https://docs.perl6.org/language/traps it seems that code examples indentation is dead broken: examples are shifted to the right, while no one does that. It looks very strange for me. And even if it's still a convention(?), we had two spaces indentation there too.
Normalize indentation level for all examples on traps page.
> Fix examples indentation

- doc/Type/Real.pod6
Specify whether the endpoints are included or not when selecting the
pseudo-random number.
References:
- https://github.com/perl6/roast/blob/master/S32-num/rand.t#L13-L30
- https://github.com/MoarVM/MoarVM/blob/master/3rdparty/tinymt/tinymt64.c#L97-L116
Fixes #787.
> Clear ambiguity regarding Int/Real rand()

- doc/Type/Proc/Async.pod6
Tackle issue #1468.
IMO in this case it is reasonable to expect that people will be
copying the example and reducing it to their needs, so I tried to
include everything that may be needed.
The logic for kill signals is questionable, I don't know if there's
anything better we can show.
**This is not mergeable because of [RT #132016](https://rt.perl.org/Ticket/Display.html?id=132016)**. Either wait for the
ticket to be resolved or get rid of ｢Supply.merge｣ and ｢Supply.zip｣.
> Proc::Async example with ｢react｣

- doc/Language/objects.pod6
Add documentation on setting invocant in method signatures, using type
constraints to define class and object methods, and using multi
declarator for defining same-name class and object methods.
Fixes #1121.
> Document invocant in method signature

- doc/Type/Signature.pod6
Based on conversation with @zoffixznet, try to add more context (and
definiteness) to the current elaboration for the `:D`, `:U`, and `:_`
type constraints.  I realize this is also a good place here to show type
objects and instances, to support the concept of definiteness.
Fixes #1469.
> (Try to) clarify type smileys for .DEFINITE-ness

- doc/Type/Proxy.pod6
The accompanying text seems to indicate that the modification of the
stored value would occur at retrieval.
Text-'To create a container that returns twice of what was stored in it'
The example showcases the capabilities of Proxy in the same way, but
hopefully is a bit more clear.
> Modify Proxy Example To More Closely Match Text

- doc/Type/IO/Socket/Async.pod6
As per Issue #1213, change the use of $p to $promise to make it
more expressive.
> Change $p to $promise in Async documentation

- lib/Pod/Htmlify.pm6
- template/footer.html
Let the pod6 docs link to their non-raw GitHub pages, so visitors can
see and maybe help out on improving some more.  And for convenience,
also provide an edit link.
There's probably some more improvement to do on the footer as well; will
further work on separate commits/PRs.
> Link to non-raw GitHub page, with edit link

- doc/Language/variables.pod6
Explains the relationship between lexical/package and normal/dynamic scope a bit more.
Asked in  #1082
> “my” docs mentioning dynamic variables

- lib/Pod/Htmlify.pm6
- template/footer.html
The first paragraph/line was getting too long, so split it a bit and
rephrase to emphasize source location and actions to either report
issues and/or edit/fork.
Fixes #1535.
> Split and rephrase lines in the footer

- doc/Programs/01-debugging.pod6
Since a common debugging question is "how is this function being called?", I added the Backtrace class to the page that describes debugging techniques.
> Describe the Backtrace class in the debugging section.

- doc/Type/IO/Path.pod6
Also intended to fix broken link to https://docs.perl6.org/type/IO::Path#File_test_operators from https://docs.perl6.org/language/5to6-perlfunc#Filetests. Much was copied from https://docs.perl6.org/type/IO::Path#File_test_operators.
> File test adverb forms with links to method forms

- doc/Language/syntax.pod6
Should help removing the TODO tag on this section.
The subroutine are now briefly explained in the section, and the example
contains a reference to the hyper method call ">>".
A new head2 section about precedence dropping has been created
with a short example about the difference on using a "standard" method call
and a precedence drop one.
> Add a short introduction to subroutines and precedence dropping.

- doc/Language/syntax.pod6
That was my fault on PR merged by commit 135102b39481aa.
There was an extra space between "head" and "2" leading to
the wrong rendering of the section title.
> Fix "head2" POD title section.

- doc/Type/Hash.pod6
Mentioned in #1588 .
We do have a intro of non-string keys at https://docs.perl6.org/type/Hash#index-entry-object_hash
but obviously its position is wrong.
So I try to rearrange the text and make a PR, but its readability should be improved.
Not a native English speaker, I ask for your help to make the doc read more smoothly.
> Try to fix intro of non-string keys of Hash

- doc/Language/5to6-perlvar.pod6
- doc/Type/IO/Handle.pod6
- :buffer remains under the hood, deprecated for 3 releases
- :buffer is now :out-buffer, tweaking output buffer
- :in-buffer lets tweak input buffer
Impl: https://github.com/rakudo/rakudo/commit/f9c10c2145
https://github.com/rakudo/rakudo/commit/3fcd74abf0
Spec: https://github.com/perl6/roast/commit/1a7b5f6130
https://github.com/perl6/roast/commit/a99c1d5ae1
(also, loosen up warning about closing handles, since we now
close them on exit automatically)
> Document handle buffering

- doc/Language/5to6-nutshell.pod6
In 5to6 - it was not properly documented. Also spell "," as the comma.
This got me tripped when working on perl6-examples.
> Document the proper way to concat arrays.

- CREDITS
- doc/Type/List.pod6
This is a powerful way of sorting, but it's not currently apparent that
it can be done this way in the documentation.
> Document List cmp infix and sorting by multiple values (via List)

- doc/Language/modules.pod6
After discussion in #perl6, the consensus seems to be that the link referenced in the docs does not resemble the META6 spec. To avoid confusion, the link should be removed.
> Remove link to outdated META6 spec

- doc/Language/grammar_tutorial.pod6
Since this tutorial shows actions in grammar only by associating a action object, I add an example to introduce write actions directly.
As I am a nonnative, maybe there is some improper expression in the text.
Thanks for your review!
> Add example "Add actions directly", review needed

- doc/Type/Label.pod6
The largest of the changes here is the documenting of the redo method on
Label. Also made some modifications for the existing label examples.
Changed the example for the next method so that it's output differs from
that of the last example. With the change, the numbers 5 through 10 are
printed, which makes it more clear that the loop has iterated a total of
ten times but only reached the print statement during 6 of those.
Also, added the output to the example, as I believe that is clearer and
allows better visualization of what occurred. It also is more consistent with
the example-then-output style used throughout the docs.
These example changes are largely subjective, but I think they are for the allow
for better clarity / consistency.
> Modify Label Doc and Examples

- .dockerignore
- CONTRIBUTING.md
- Dockerfile
- Makefile
Made a number of modifications to the Dockerfile in the repo:
* Minimized the number of cache layers in final image (by reducing the
number of Run commands)
* This way Docker cannot reuse cache layers containing outdated
package versions.
* Purge build dependencies and apt cache data.
* These files do not appear in final image due to minimal intermediate
cache layers.
* The resulting image is over 100 MB smaller as a result.
* Update NodeJS to the latest stable release via the
[n](https://github.com/tj/n) script.
* Added Test::META module and GNU aspell (used in tests).
Also added a .dockerignore file, so that files within the repo do not
get used in the build context.
Added Make targets that make the Docker containers a bit easier to work with.
Add info to CONTRIBUTING indicating how to …
> Modify Dockerfile and Add Docker-related Make targets

- doc/Type/Grammar.pod6
Review needed
And plz help improving examples of `*%opt` arguments.
I have try :
```
grammar RepeatChar {
token start($character) { $character+ }
}
say RepeatChar.subparse('bbbabb', :rule('start'), :args(\('b')), :g);
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('B')), :i);
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('B')), :i, :pos(4));
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('b')), :i, :pos(4));
```
but the results are too confusing.
> Rewrite Type/Grammar.pod6

- doc/Type/Metamodel/EnumHOW.pod6
This adds a page for MetaModel::EnumHOW.  Looking for feedback -- I took these from the source, though I don't think they are part of the spec, so not sure if it's appropriate to list them here?  (Or maybe there should be a note about them being rakudo-specific?)
Resolves #1642
> Add Metamodel::EnumHOW page

- doc/Language/regexes.pod6
I think it's worthy to be documented, because people will looking for a way to using patten given at the runtime.
But I'm not sure if this's the only way to interpolate patten(string) into regex.
> Document Regex Interpolation, jnthn++

- doc/Language/regexes.pod6
It seems the comment working on regexp was referencing the similar feature of
Perl 5, not Perl 6.
Reading as it is now cannot make me  sure if this was referencing \x regexp in Perl 5 and comments or it was bad spelled out to explain that Perl 6 comments work _also_ in regexp.
> Fix reference to Perl 5.

- doc/Type/Proc/Async.pod6
Very simple link from Proc::Async to Promise while documenting the start method.
> Fix link to Promise.

- doc/Language/5to6-nutshell.pod6
- doc/Language/regexes.pod6
As of discussion <https://github.com/perl6/doc/issues/1705> related to
my previous pull request <https://github.com/perl6/doc/pull/1704> I decided
to remove the explicit reference to Perl 5 and to make it
a separate section in the 5-to-6 part related to regexps.
> Remove reference to Perl 5 in not 5-to-6 document.

- doc/Language/subscripts.pod6
The L<> directive does not work within a table, while it seems to work
within an iterable list.
I'm not sure this is the best solution, in particular with regard to its verbosity in explaining the slicing.
> Fix slice table.

- doc/Language/packages.pod6
Lookup within packages and the global namespace is described. Classes should be covered as well.
> Describe how to look up class members

- doc/Language/list.pod6
- doc/Language/subscripts.pod6
- doc/Language/traps.pod6
Previously, this section stated that:
* All ranges (including non-lazy ones) will truncate the output/ omit
undefined elements.
Rewrote the section to remove that inaccuracy and address the following:
* If the element at index [x] does not exist then the result will be an
undefined element (when subscripting Positionals).
* This behavior can be modified using the :v adverb.
* Using lazy Iterables as subscripts yields a different behavior. Only
returns defined elements (most of the time; see bullets below).
* Behind the scenes the elements of the lazy subscript are being
reified up until the point that the element in the Positional
is undefined.
* Continued use of lazy Lists will begin to return undefined
elements as new elements in the lazy List are reified.
* Include justification for …
> Rewrite, remove inaccurate Range truncation info

- doc/Language/glossary.pod6
- doc/Language/regexes.pod6
This branch referes to isse #1671 and creates a separate section in order to explain, with a simple example, what backtracking is.
I've also added the term to the glossary, linked from ratchet to the new section.
I've placed the section at the very end of the regexes since I don't believe we should explain "before" what backtracking is, it is an internal thing.
If this sounds good, I can merge. If need further work, I can proceed.
> Fluca1978 backtracking

- doc/Language/regexes.pod6
In the first example where `show_captures` is defined, the call to it has also `$string` as its second argument(line 1937). this is not used in the sub signature.
Furthermore a small typo on line 1917 (matched instead of match).
Regards,
Marcel
> first call to show_captures has wrong number of arguments in section Backtracking

- doc/Language/regexes.pod6
Fix #1755
(I thought make it clear what non-word character is is better than demonstrating by a non-word character other than whitespace)
> Add examples for << and >> (regex)

- doc/Language/variables.pod6
Left as "such like" for consistency with the rest of the text.
> Correct small typo: "suck like".

- doc/Language/faq.pod6
Fix #1830 
I didn't describe the release cycle of the compiler-only version because this one is not a mainstream distribution for many users.
See also: https://github.com/perl6/perl6.org/issues/93
> Add a Q and A about Rakudo Star release cycle

- doc/Language/5to6-nutshell.pod6
- doc/Language/5to6-perlfunc.pod6
- doc/Language/faq.pod6
- doc/Language/glossary.pod6
- doc/Language/list.pod6
- doc/Language/operators.pod6
- doc/Language/phasers.pod6
- doc/Language/pragmas.pod6
- doc/Language/py-nutshell.pod6
- doc/Language/rb-nutshell.pod6
- doc/Language/typesystem.pod6
- doc/Language/unicode.pod6
- doc/Type/Blob.pod6
- doc/Type/Cool.pod6
- doc/Type/Dateish.pod6
- doc/Type/IO/Socket/INET.pod6
- doc/Type/Numeric.pod6
- doc/Type/Signature.pod6
- doc/Type/X/Temporal/InvalidFormat.pod6
There are numerous instances of `=for` and `=begin` code blocks marking already indented code peppered through the documentation. This indentation is preserved in the rendered output, which is typically unintentional. So, for example:
=for code
say 'hello';
is rendered as
say 'hello';
rather than
say 'hello';
Although this is a fairly boring commit, it touches a lot of files—hence the PR rather than direct push. Note that If you ignore whitespace (`git diff master -w`), no content has changed. There're also no `test` or `xtest` regresssions.
> Remove leading indentation from (some) pod code blocks.

- doc/Language/unicode_entry.pod6
I'm going to PR the https://github.com/vim-perl/vim-perl6 repository to add instruction on their `README.md` on how to configure this plugin to get the behaviour described here.
Edit: PR opened on `vim-perl6`: https://github.com/vim-perl/vim-perl6/pull/17
> Add reference to vim-perl6 in the unicode_entry page

- doc/Language/modules.pod6
I'm considering to split up this section into a mandatory and optional section, to make it clearer what a user *needs*, and what they can additionally use to achieve certain goals (such as semantic versioning, in this case).
> Update META6.json documentation to include "api" field

- doc/Type/Signature.pod6
> return type constraints also work for pointy blocks

- doc/Language/objects.pod6
Hopefully completion of issue #136 that I had to put aside for a while.  Python, Ruby, C# and Delphi all allow 'setters' for attributes that overload the assignment operator so other people from other languages may wonder about the feature.  Patch tries to give just enough to satisfy their curiosity.
Forgot to mention [March 24 IRC discussion](https://irclog.perlgeek.de/perl6/2018-03-24#i_15961290) with @timo when posting.
> Mention attribute mutators by Proxy and refer to mutators.t in roast

- doc/Type/Grammar.pod6
The previous one calls pre-defined tokens (See: https://docs.perl6.org/language/regexes#Unicode_properties) not user-defined one.
That is confusing since this example defines unused tokens as if it used.
> Fix Identifiers exmple

- doc/Language/nativecall.pod6
NativeCall's`explicitly-manage` subroutine is exported by default but undocumented.
I added information on it to NativeCall's documentation, as well as a strings section that goes into more detail on how it should be used, where documentation on buffers and blobs could also be placed later on. Please review before merging
> Document NativeCall explicitly-manage subroutine

- doc/Language/regexes.pod6
Added examples to help illustrate difference between m/ / and / /.  Zoffix provided the examples.  I provided the learning.  An example for rx/ / is needed.  As a newbie, this info is very helpful and rare.  It is not in Think Perl 6, ttbomk.  And definitely not in Perl6Intro.com.  Needed info or something better.
> m/ / and / / examples added

- doc/Language/module-packages.pod6
Reference to Bar.pm6 is arguably ambiguous
Added three words
> Clarify 'Bar.pm6' vs 'how to use Bar.pm6'

- doc/Language/nativecall.pod6
CArray.allocate from https://github.com/rakudo/rakudo/pull/1779/commits/a02131d53d52bf96ba8f7bd56d04c45771dbb08c is undocumented
The old example showing how to allocate a CArray was updated to use the new method
> Document CArray.allocate

- doc/Language/5to6-nutshell.pod6
- doc/Language/glossary.pod6
- doc/Language/io-guide.pod6
- doc/Language/io.pod6
- doc/Language/ipc.pod6
- doc/Language/traps.pod6
- doc/Language/unicode.pod6
- doc/Type/IO.pod6
- doc/Type/IO/Handle.pod6
- doc/Type/IO/Path.pod6
- doc/Type/IO/Special.pod6
This is part of the fixes suggested in #2015
Looking for handles to solve #761, I have found that file handle appear at least in that form or in the filehandle form. We should try and normalize terminology across all the documents, and this is only an example. When normalization is done, we should turn it into a test later on.
Change: file handle, filehandle, file-handle → filehandle
> Change "file handle" to "filehandle"

- doc/Language/5to6-perlsyn.pod6
- doc/Language/glossary.pod6
- doc/Language/haskell-to-p6.pod6
- doc/Language/rb-nutshell.pod6
- util/perl-nbsp.p6
Perl 6 is supposed to use U00A0 instead of a regular space, but this isn't always the case in the documentation.
util/perl-nbsp.p6 lints each of the documentation files, checking for
cases where Perl 6 is written with a regular space instead of a
non-breaking one, and replaces it accordingly.
> Implement Perl 6 NBSP linter script

- doc/Language/glossary.pod6
- doc/Language/modules.pod6
- doc/Language/operators.pod6
- doc/Language/performance.pod6
- doc/Language/phasers.pod6
- doc/Language/regexes.pod6
- doc/Language/subscripts.pod6
- doc/Language/syntax.pod6
- doc/Language/variables.pod6
- doc/Type/Variable.pod6
Terms fixed: runtime, shorthand, lookahead, lookbehind
Looking for handles to solve #761, I have found that file handle appear at least in that form or in the filehandle form. We should try and normalize terminology across all the documents, and this is only an example. When normalization is done, we should turn it into a test later on.
Changes applied: 
runtime, run-time → runtime
short-hand, shorthand →shorthand
look-ahead, lookahead →lookahead
look-behind, lookbehind →lookbehind
> Change terms as suggested in #2015

- doc/Language/js-nutshell.pod6
It's the recommended way. WHAT is used to actually get a type object, which isn't what we want. We want the name of the class the object was instantiated from.
> Change use of WHAT to ^name

- doc/Language/5to6-nutshell.pod6
- doc/Language/classtut.pod6
- doc/Language/contexts.pod6
- doc/Language/objects.pod6
- doc/Language/operators.pod6
- doc/Language/rb-nutshell.pod6
- doc/Language/temporal.pod6
- doc/Language/variables.pod6
- doc/Type/Baggy.pod6
- doc/Type/Cool.pod6
- doc/Type/IO/Path.pod6
- doc/Type/List.pod6
- doc/Type/Map.pod6
- doc/Type/Range.pod6
- doc/Type/Signature.pod6
- doc/Type/Supply.pod6
- xt/word-variants.t
Change all the smart-match* matches as suggested in #2015
Change xt/word-variants.t to just display the filename an error message when
the test fails
Looking for handles to solve #761, I have found that file handle appear at least in that form or in the filehandle form. We should try and normalize terminology across all the documents, and this is only an example. When normalization is done, we should turn it into a test later on.
Change smart-match -> smartwatch
Add terms in the xt/word-variants.t test
> Add the prefered terms to xt/word-variants.t

- doc/Language/regexes.pod6
In the [Regexes section Predefined Character Classes](https://docs.perl6.org/language/regexes#Predefined_Character_Classes), the sentence after the table of classes incorrectly
identifies the zero width assertions as "the last three" which is not true for any sorting of
the table.  The line after that appears to be a pasto.
Fix confusing sentence about zero-width assertions included with character classes and remove likely pasto right after.
> Update Language/regexes.pod6.  Fix confusing sentence about zero-width assertions

- CONTRIBUTING.md
- Dockerfile
- doc/Language/packages.pod6
- It appears that the nodejs package no longer exists for the base image
used by the Dockerfile, and since it's already using the `n` script to
install the latest stable version of nodejs, I simply use `n` to
install nodejs in the first place instead.
- Also fixed a small code formatting issue in packages.pod6.
- Corrected the instructions on running the built docker image in CONTRIBUTING.md.
Initially, I was only trying to fix the formatting issue in packages.pod6, but couldn't get
Mojolicious working to be able to preview my changes, so I ended up building a docker
image from the Dockerfile.
> Fix missing nodejs dependency in the Dockerfile.

- doc/Language/regexes.pod6
I believe that an update to fix #2087 reversed the connection between "." for suppressing capture with grammars/methods and "&" to suppress capture with lexical rules.
Rewrote relevant sentence.
> Update regexes.pod6 fix reversed suppress capture operators ".&"

- doc/Language/control.pod6
The update displays the type of `$answer` that seems more useful as an example.
If you run the given code you'll get an error about default stringification which seems LTA
Update the example code to use .perl which seems more useful.
> Modify without example

- doc/Language/nativecall.pod6
Library paths and names needed more documentation. See https://github.com/perl6/doc/issues/1513
More was written
> More documentation on library paths and names

- htmlify.p6
+ added: sub get-pod6-page-order
+ added: process 'Language' with page-order
+ added: various comments
> Modify to allow pod6 page sorting by :page-order value

- Build.pm
`zef install p6doc` fails after building.
After looking through zef's code, I found that it considers the build to have passed only if a truthy value is returned, so I made the build method return `True`.
> Fix p6doc build errors

- doc/Type/Real.pod6
Fix the Fahrenheit to Kelvin / Celsius factor, and update expected result.
Example for Bridge uses the incorrect (inverted) factor for Temperature unit conversion.
The sum (expressed in Kelvin) was obviously wrong.
Correct the conversion factor, and the example result
> Do the correct Fahrenheit to Kelvin conversion.

- doc/Language/nativecall.pod6
A potential fix for #2178.
The link to "Function Pointers" in the nativecast page didn't point to the right location.
This fixes the link, however I was not able to view the change properly due to the app interpreting forward slashes as "$SOLIDUS".
> - Fixes bad link in route page for nativecast.

- Makefile
- util/manage-page-order.p6
Keep reorg, but remove number prefixes from transformed files for now.
> revert file names to no number prefix

- doc/Language/unicode_entry.pod6
Closes https://github.com/perl6/doc/issues/1531.
> Add WinCompose to unicode_entry

- doc/Type/Str.pod6
The method section for Str#substr-rw did not mention the default value of $length.
Patch supplies the proper wording, as discussed on IRC, and on the pages for #2187
> Xliff patch 20180725

- doc/Type/Str.pod6
The method section for Str#substr-rw did not mention the default value of $length.
Patch supplies the proper wording, as discussed on IRC, and on the pages for #2187
> - Addresses issue #2187.

- doc/Type/X/Method/NotFound.pod6
- doc/Type/X/Parameter/MultipleTypeConstraints.pod6
- doc/Type/X/Parameter/WrongOrder.pod6
- doc/Type/X/Placeholder/Mainline.pod6
`X::Method::NotFound`, `X::Parameter::MultipleTypeConstraints`, `X::Parameter::WrongOrder` and `X::Placeholder::Mainline` have no `class` keyword in their `=TITLE`. All other classes do.
Add `class` keyword in their `=TITLE`
> add missing 'class' keyword for consistency with other types

- doc/Language/regexes.pod6
Three typos fixed.
Typos in the paragraph in the Capture Markers section of the regexes document
Made what I considered to be sensible changes
> Fixes typos in regexes:: Capture Markers

- doc/Language/traps.pod6
The `Infix operator assignment` section in traps explains the problem but offers no solution. This PR fixes that.
> mention hyped form of infix assignment ops in traps

- doc/Language/5to6-nutshell.pod6
These are sentence cases I was less sure of as wasn't sure whether to consider things like "List Separator" as proper noun. Hopefully digestible enough for someone to consider in this separate commit.
Also a couple that I noticed I missed whilst looking at those.
This is just a small tail end to the closed bug:
Use sentence case throughout titles and headings
https://github.com/perl6/doc/issues/2223
Small list of final changes of sweep through to sentence case titles in language documents.
> Fixes missed and doubtful sentence cases on Language docs

- doc/Language/5to6-nutshell.pod6
- doc/Language/about.pod6
- doc/Language/glossary.pod6
- doc/Language/hashmap.pod6
- doc/Language/modules-extra.pod6
- doc/Language/mop.pod6
- doc/Language/newline.pod6
- doc/Language/performance.pod6
- doc/Language/testing.pod6
- doc/Language/traps.pod6
- doc/Language/unicode.pod6
- doc/Language/unicode_entry.pod6
For format L<name|url> in 'Language' docs, changes http to https where appropriate.
This is a start on the following:
Use HTTPS URLs, where available #2246
I've switched http to https in the 'Language' docs where the format is L<name|url>
https://vimdoc.sourceforge.net/htmldoc/digraph.html is not correctly configured for https so left as http
https://vim.wikia.com/wiki/Entering_special_characters redirects to a non-secure version so have left as http
> Makes some http links across 'Language' documents https

- doc/Language/5to6-nutshell.pod6
- doc/Language/glossary.pod6
- doc/Language/haskell-to-p6.pod6
- doc/Language/unicode_ascii.pod6
Finding links that match  L\<url\> and replacing http links with https where appropriate (ie where they work)
Use HTTPS URLs, where available #2246
Further work on this issue, using a different pattern to find the links
> Replaces more http links with https in 'Language' docs

- doc/Language/modules.pod6
After struggling for half an hour with a change to a local module that wasn't being reflected, 
I realized that I needed to uninstall and install the local module again for the change to take place.
If this is mentioned somewhere else, this can be disregarded.
Point out that one must uninstall and install a given local module for the latest changes to take place.
> Add some small advise about module's update

- doc/Language/5to6-nutshell.pod6
Replace http://www.perlfoundation.org/perl6/index.cgi?perl_6_delta_tablet with https://docs.perl6.org/language/5to6-overview for tips on translating Perl 5 to Perl 6
404 on link on https://docs.perl6.org/language/5to6-nutshell #2250
I've replaced the link with the one to the 5to6-overview, which seems best to me.
> Replace broken link with a new link

- doc/Type/Any.pod6
The "1-item list" in Any docs is inaccurate #2176
I have standardised the language based on other language in the document, though will need checking by someone with a greater understanding of what's actually being said.
Looking at the Cool type document, I have changed all descriptions which say 'coerce' to 'coerces' as there were both in the document.
I have added 'the invocant' in many places and hope this is correct to fit in with the language I was using in this update. Again, this was something used sporadically and I had to choose what to follow. It is now more consistent.
I have referred to C\<List\> meaning a class, rather than just 'a list'. Again, this seems more consistent to me with the rest of the document.
> Any list clarity

- doc/Language/modules.pod6
- doc/Language/pragmas.pod6
Previous link does not jump to paragraph: https://docs.perl6.org/language/modules#Finding_Modules
Adjusted case: https://docs.perl6.org/language/modules#Finding_modules
> Modify case in link to Finding_modules

- assets/sass/style.scss
If a table is too wide for a page a horizontal scroll bar will be added to the bottom.
If the page is focused, the right key will scroll right and left to come back.
I'm presuming this will work on mobile with finger dragging, but no testing set up for that at the moment.
Squished table cells on mobile #650 
Table columns that are outside the viewport are not viewable. Problem on mobile. This occurs in the bug report and is also in the 'Routines' page, directly linkable from the front page of the site making the bug quite prominent.
Add css via sass generator following advice from someone's question on stackoverflow (https://stackoverflow.com/questions/5533636/add-horizontal-scrollbar-to-html-table) on best way for creating scrollable table.
Requested reviews as not sure if other …
> Make pod-tables scroll horizontally on smaller views

- assets/sass/style.scss
Reverts perl6/doc#2258
Scrolling worked, but layout affected. Back to the drawing board
> Revert "Make pod-tables scroll horizontally on smaller views"

- doc/Type/Baggy.pod6
- doc/Type/List.pod6
- doc/Type/Setty.pod6
Not clear that you use `pick(*)` to shuffle a list.
Describe `pick(*)` as shuffling.
> describe .pick(*) as shuffling

- doc/Language/control.pod6
Reverts perl6/doc#2274
See the discussion.
> Revert "Update control.pod6"

- doc/Language/regexes.pod6
Also clarifies how round brackets work in name capture.
Also take the mystery out of what we are going to see in subrules.
named capture using non-capturing group confusion #1634
Also looked like a little further clarity could be added to the way brackets work for capturing.
Refer to 'default' of square brackets not capturing and then highlight that it is a change to default behaviour that they capture when named. Didn't want to use round brackets in the example as think it's advisable myself (though not imperative) to use square brackets in named groupings. Highlighted that you can use round brackets in the example though.
Added a line mentioning named regexes as this is what the subrules link goes on to talk about, but no harm mentioning it here.
> Clarifies capturing properties of square brackets in regex

- doc/Language/5to6-nutshell.pod6
- doc/Language/classtut.pod6
- doc/Language/contexts.pod6
- doc/Language/faq.pod6
- doc/Language/functions.pod6
- doc/Language/glossary.pod6
- doc/Language/hashmap.pod6
- doc/Language/nativecall.pod6
- doc/Language/nativetypes.pod6
- doc/Language/objects.pod6
- doc/Language/operators.pod6
- doc/Language/performance.pod6
- doc/Language/quoting.pod6
- doc/Language/structures.pod6
- doc/Language/system.pod6
- doc/Language/traps.pod6
- doc/Language/typesystem.pod6
- doc/Language/unicode_entry.pod6
- doc/Language/variables.pod6
Adjust links to headings according to latest adaptation of headings
from #Links_Of_This_Form to #Links_of_this_form.
refs: https://github.com/perl6/doc/issues/1838
> Adjust heading links

- doc/Type/Cool.pod6
If a routine is only defined as sub, change to 'sub name', if only by
method to 'method name', and if by both to 'routine name' - where this was
not already the case.
Methods, routines, subs misnamed on Cool page #2308
Made changes
> Changes routine headlines

- doc/Language/operators.pod6
Response to:
The documentation on ==> should get to the point faster #2316
The documentation on ==> should get to the point faster #2316
Adds example at top
> Adds straightforward example for feed operator

- doc/Type/Pod/Block.pod6
- doc/Type/Pod/Defn.pod6
- doc/Type/Pod/FormattingCode.pod6
Missing type doc for `Pod::Defn` & `Pod::FormattingCode`
Related issues: #2238 & #2302 
Add type docs
> Add Pod::Defn & Pod::FormattingCode

- doc/Type/Signature.pod6
Incorrect heading for section describing smiley constraints :U/:D.
Heading corrected, and added a brief clarification of the difference between "definiteness" and "definedness". Clarification based on: https://stackoverflow.com/questions/48986414/whats-the-difference-between-perl-6s-definite-and-defined-methods
> Closes #2321

- doc/Language/typesystem.pod6
As discussed on #perl6 document the typing of return in signatures.
> Document typing of returns in signature

- doc/Language/syntax.pod6
Identifier-section was perceived as a bit messy.
Restructured section along the lines of the different types of identifiers:
> Rewrite of Syntax-Identifier section

- doc/Language/modules.pod6
A missing comma in a META6.json example
The comma was added, validating the JSON
> Add a missing comma

- doc/Language/modules.pod6
The paragraph between two code blocks is not itself a code block and should not be indented by four spaces.
> Take a small paragraph out of verbatim mode

- doc/Language/math.pod6
The cited article contains a few mathematical imprecisions which ought to be addressed. One of them, about sequences and the real numbers, is particularly troublesome since there seemingly is no justification for this claim and doesn't really add much value to the rest of the article. 
* Disclaimer about the purported mathematical field nature of Rat, Num
and Complex
* Rephrases the Int section to be more consistent
* Matrices are not, in general, a field but a ring
* Hamilton's quaternions are not a field, but an algebra over the real
numbers
* Claiming that ℝ is a sequence makes very little sense from a
mathematical standpoint. Lacking further explanation/justification,
the reference should be dropped until it can be given some meaning.
> Corrects some imprecisions in the "Doing math with Perl 6" article

- doc/Language/setbagmix.pod6
- doc/Type/BagHash.pod6
- doc/Type/MixHash.pod6
Also added code examples to a note in BagHash.pod6 about .reverse
and included that note in MixHash.pod6.
Also a few grammar/accuracy touches.
The documentation was incomplete, waiting on the Setty operator rework.
Per the todo, I used BagHash.pod6 as the template.
Along the way, running the code samples, I found that the output was now 'Mix' and 'Bag' instead of 'mix' and 'bag', so fixed.
I thought the note on C<reverse> was excellent, so I added samples to it, and moved that also into MixHash.pod6.
> Document the Setty ops for MixHashes per TODO

- doc/Language/00-POD6-CONTROL
- doc/Language/intro.pod6
- util/manage-page-order.p6
Change to Sentence case for sections
typos in code
Remove Perl6
Also, changed some section titles (eg removed Perl 6 from Advanced topics).
> Changes as requested by AlexDaniel

- doc/Language/intro.pod6
- doc/Language/syntax.pod6
> Text reflow and minor fixes

- doc/Language/modules.pod6
Syntax error on modules.pod6 causing tests to fail
Remove extra =end item
> Remove extra =end item

- doc/Type/Supply.pod6
Supply doc is wrong about `done` #2161
Clarifies when &done and &quit are called
> Supply fix

- doc/Language/pod.pod6
The section https://docs.perl6.org/language/pod#Rendering_Pod mentions that if order to render Pod files some modules must be installed, but there are no links to the related webpages, this PR adds them:
Link for Pod::To::HTML = https://github.com/perl6/Pod-To-HTML
Link for Pod::To::Markdown = https://github.com/softmoth/perl6-pod-to-markdown
> Add links for needed modules in Rendering Pod section

- doc/Language/modules.pod6
The link was pointing to https://design.perl6.org/S26.html and probably is better to use the Perl 6 Pod documentation from docs.perl6.org
> Update link to Perl 6 Pod documentation in Modules

- doc/Language/objects.pod6
This PR adds a link to  https://docs.perl6.org/language/functions#Arguments from the object construction phase, as the issue #2359 suggests.
> Fix #2359 Add link to arguments in Objects

- doc/Language/grammars.pod6
Demonstrate passing arguments to grammars
Passing arguments to tokens in Grammars is undocumented #2102
Adds some examples of using arguments with classes and rules
> Add examples of passing arguments to grammars

- doc/Type/IO/Handle.pod6
See rakudo/rakudo/#2466.
This addresses the issue with the example for IO::Handle.Supply.
-->
> - Should be a fix for rakudo/issues/#2466

- doc/Language/glossary.pod6
This fixes a typo and an incorrect link on the Glossary page.
From what I read, it seems like "an historical" is not up to taste. It's "a" unless the "h" is silent, which it isn't in "historical", unless you're French :-)
> Fix typo and link in Glossary

- CREDITS
- doc/Type/IO/Socket/Async.pod6
whenever needs to be in a react block (looks like a 6.d feature).
Wrapped the usage of whenever in a react block within the example for listen().
Also added myself to CREDITS.
> Example use of whenever should use a react block

- doc/Type/Promise.pod6
- doc/Type/Signature.pod6
Once 6.d is shipped in a compiler, apply this to remove the PREVIEW from these examples
> remove PREVIEW from examples

- doc/Language/glossary.pod6
Synopsis 99 has an entry for WAT. It still appears in chat and issues,
e.g. in the doc repo, often as the backside of a DWIM [1]. The formulation
in this commit differs a bit from S99 to highlight that perceived duality.
I haven't seen any issue about it nor any mention of WAT in the history
of the doc repository, so it doesn't seem like it has been removed for
any reason -- and it's still used.
[1] https://colabti.org/irclogger/irclogger_log_search/perl6?search=WAT&action=search
> Add WAT to Glossary

- doc/Language/operators.pod6
The `eqv` documentation demonstrates that two arbitrary (from user-defined
classes) objects are equivalent when their types agree and, recursively, their
properties are equivalent. But if you put these two equivalent objects each into
a `Set`, the sets do not compare `True` when using `eqv`. This is a WAT to me.
`eqv` on Sets works differently than I had imagined. It doesn't unpack the Sets,
but delegates the check to Set.ACCEPTS, which in turn uses `===` to perform
the element-wise comparisons. To get the expected behaviour, as timotimo [explained](https://colabti.org/irclogger/irclogger_log/perl6?date=2018-12-04#l49),
the class must act like a value type.
Since I had never once heard of value types before, I think it is a good idea
to show the problem and link to an explanation of …
> Mention value types in eqv documentation

- Makefile
Writing disambiguation files >2000 of them adds substantially to the creation time. 
No discernable change has been found with cursory testing to the operation of the system without the files.
No documentation exists about their use.
The MakeFile is modified to add a disambiguate flag and it is set to False. 
When false, the disambiguation files are not written.
If there is a need for them, the flag can be set back to True.
> add disambiguate to makefile and set to False

- doc/Language/operators.pod6
- doc/Type/Str.pod6
This fixes two small issues with Pod tables: the first is an unescaped column separator '+' and the second is missing multi-line row separators in a table with multi-line content.
> Two Pod table fixes

- doc/Language/create-cli.pod6
commit c8eef326fc7efe6f0e09de6677e9dd1c1e7a9aa1
Author: Harrison Chienjo <hhathersage@gmail.com>
Date:   Fri Dec 7 17:25:16 2018 +0300
Replace -v with --verbose.
Supplying ```-v``` as one of the command line argument triggers help message display instead of toggling verbose on
> Replace -v with --verbose

- doc/Language/list.pod6
Documentation had mentioned a wrong result of a array slice.
```
$ perl6 -e 'my @a = 1..5; say @a[0..^*]'
(1 2 3 4)
```
> Fixed array slice with [0..^*]

- doc/Language/traps.pod6
Fixes https://github.com/rakudo/rakudo/issues/2604
`Map/Bag/BagHash/Hash (cont) <string>` returns `False` if the value of the key is falsey.
Document the trap.
> Document trap on set subroutines on Associative

- doc/Language/modules.pod6
I searched the docs for information on exporting a multi method and didn't find anything.  The behavior works as you might guess, but I thought it might be helpful to make it explicit in the documentation.
Added a short section with what seems to be the correct information.  I tested it with a toy module on Rakudo Star 18.10.
> Add section on exporting multi methods in a Module

- doc/Type/CompUnit/Repository/FileSystem.pod6
- doc/Type/CompUnit/Repository/Installation.pod6
This adds basic documentation on the parts of CURFS and CURI that can be considered stable.
This probably needs some cleanup. For instance I wasn't exactly sure how to express `need()`s signature since it includes a private method call in its default value:
`CompUnit::PrecompilationStore :@precomp-stores = self!precomp-stores()`
> CURFS and CURI basics

- doc/Language/io-guide.pod6
As mentioned on #perl6 today, the original introductory text here
could lead one to think the difference was between `my IO $path` and
`my Str $path`, when it's actually in using `~` for getting the value
rather than `.absolute` or `.relative`.
This version uses `.Str` explicitly so it lines up more obviously with
the text.
> Make .Str vs .IO example more explicit

- doc/Language/5to6-perlfunc.pod6
It is incorrect to say that `.base` is an alternative to `:16`, since `:16` is Str -> Int and `.base` is Int -> Str.
Reworded
> Correct description of `hex`

- doc/Type/Rational.pod6
> check rational type #2632

- doc/Language/variables.pod6
$*USAGE and $*COLLATE were mentioned in other places, but absent from Variables page. Also, $*COLLATION explanation depends on `Collation` type, which is not documented at all.
Add brief explanations to Variables page, file an issue about `Collation` type absence(https://github.com/perl6/doc/issues/2644)
> Document $*USAGE and $*COLLATE

- doc/Type/Complex.pod6
`Complex.new` is working since 2016.10, so I assume it is old enough to just document it. It was stabilized into spec for 6.d.
> Note arg-less Complex.new call

- doc/Type/Supply.pod6
As it was standardized in 6.d version, it is healthy to mention it without a bind to "implementations" word.
> Mention 6.d standard value of minimal interval

- doc/Type/Supply.pod6
The `:&tap` parameter of `Supply.tap` was undocumented.
It is now documented.
> Document the :&tap parameter of Supply.tap

- xt/aspell.t
This is an attempt at addressing #975.
Aspell's URL mode turned out to yield the fewest false positives (`--mode=none` gets thrown by "%3Aopen…", increasing the FP count); awk was dropped in favour of Perl for lookbehind assertions. 
"\suffix" no longer causes problems (it's treated as "suffix"), nor does "foo\tbar" ("foo bar"). No doubt the `s///` pattern can be further improved.
(Please don't merge without testing.)
> Workaround for aspell backslash escaping issues (#975).

- doc/Type/Match.pod6
```
Match provides .Int and .actions
```
from 6.d changelog.
`actions` method was documented already, this adds `Int`.
> Document Int method on Match

- doc/Language/traps.pod6
This particular trap is regarding an operator, but is created by
incorrect use of whitespace, so it should probably be mentioned in
both places.
> Traps: point at operator trap in whitespace section

- doc/Language/js-nutshell.pod6
I asked someone familiar with JS but not Perl 6 whether the JS nutshell page explained everything clearly or not. This was their response:
[16:05:53] #Zarel: Morfent, re: your Perl article, I don't recognize the term "dynamically scoped"
[16:05:59] #Zarel: you might want to explain that one
Don't use the term "dynamically scoped" and explain what dynamic variables are. Also clean up the code examples since a couple were wrong and `console.log`/`say` output wasn't preceded by `OUTPUT: ` in all the examples.
> JS nutshell: clarify variables section, clean up code examples

- doc/Type/Pair.pod6
Part of 6.d changelog, `Non-ASCII numerics can be used in :42foo colonpair shortcut`.
> Note non-ASCII numerics in Pair colonpair

- doc/Type/StrDistance.pod6
Part of 6.d changelog, `StrDistance stringifies to its .after string`.
> Document StrDistance.Str

- doc/Type/Enumeration.pod6
Part of 6.d checklist, `Enumeration.enums returns a Map`.
> Update enums method description

- doc/Language/subscripts.pod6
Part of 6.d changelog, `:exists can be used with multi-dimensional associative subscripts`.
> Show multi-dim :exists adverb

- doc/Language/list.pod6
Part of 6.d changelog, `Typed arrays can be created with both my SomeType @array and my @array of SomeType`.
> Show typed array of syntax

- doc/Language/control.pod6
Part of 6.d changelog, `next can be used in whenever`.
> Add next in whenever example

- doc/Language/syntax.pod6
Part of 6.d checklist.
```
QuantHashes/Map in % variables and List in @ variablescan be declared with is trait (e.g. my %h is Set)
```
> Show a non-coercing hash/array subclass init

- doc/Language/typesystem.pod6
Part of 6.d changelog, `Dynamically created lists can be used to define an enum`.
> Add example of dynamically created enum

- doc/Type/Map.pod6
- doc/Type/Range.pod6
Docs for Map and Range classes say `is Iterable`, but Iterable is a class.
Change to `does`.
> Map and Range: Iterable is a role; use 'does' not 'is'

- doc/Language/functions.pod6
This way new users can understand the point of the call without having to open a REPL and figuring it out for themselves.
The example does not provide the proper context. A new user needs to start a REPL, copy the example, and then run it before the docs make sense. While this should be encouraged, it should not be REQUIRED.
Reworked the example so that the output of the code is clear.
> Adds output to nextsame example.

- xt/examples-compilation.t
examples-compilation.t wraps code to test into a template and
heuristically adds some other bits, so that a bare
``` perl6
method foo ($x)
```
would compile successfully. This includes adding empty blocks at
the end of a line when a situation like above is detected. Previously,
the heuristic was triggered also with this way to split a signature:
``` perl6
submethod BUILD (
...
) {}
```
introducing a syntax error that wasn't the example code's fault.
Fixes #2750
> Allow examples-compilation.t to pass for subs with multiline signatures

- xt/examples-compilation.t
Add :preamble code to an example test even if it was marked as :solo,
fixes 2754
***
Currently, there are no uses of `:preamble` and `:solo`on the same code block so this change is a priori harmless, but there will be uses after I'm done with #2738.
> examples-compilation.t: always add :preamble code

- doc/Type/Bool.pod6
Documentation for ".Int on Bool objects returns an Int object" from 
https://github.com/perl6/doc/issues/2632 checklist for 6.d.
> .Int on Bool objects returns an Int object

- xt/camelia-invocations.t
Resolves #2695. This adds a test xt/camelia-invocations.t which goes
through all code blocks and looks for accidental "m:" prefixes from
pasting code from IRC where the eval bots react to this prefix.
***
Ambiguity with adverb'd `m///` is resolved heuristically with a regex for
valid matching adverbs. Labels called "m" must be avoided. The test passes,
there are currently no false positives.
> Add xtest for copy-pasted camelia invocations

- doc/Type/Scheduler.pod6
The changes in https://github.com/rakudo/rakudo/pull/2819 are undocumented.
This documents them.
> Document Scheduler.cue edge cases with :at/:in/:every

- doc/Type/Seq.pod6
I thought the original sentence, "The same is true when assigning a Seq to an array."  is not very clear on what's the same here. So I rewrote it and provided an example too.
> Clarify that assigning a Seq to an Array consumes it

- doc/Type/QuantHash.pod6
Resolves `Items with negative weights are removed when coercing a Mixy to Setty/Baggy` item in 6.d checklist.
> Clarify Setty/Baggy and add examples

- doc/Language/js-nutshell.pod6
The original documentation referred to "the two's complement" of a number.  Which is technically correct, but that's a very strange phrasing; everyone just says bitnot or bitwise not (or, in context, just not).
> Replace "two's complement" with "bitwise negation" to better reflect the meaning and usage of the operator

- doc/Language/list.pod6
From the example of `0..^*` and `0..^*+0` being consistent in Range subscripts (even though they are technically very different), it might sound like WhateverCode (finite) ranges and infinite ranges might be consistent everywhere. This is not the case.
Add a half-sentence pointing out and explaining the difference one should expect between `0..*` and `0..*+0` when used as subscript.
> Point out difference between finite and infinite Range subscripts

- doc/Type/Pair.pod6
Last thing we need for `Pair provides .ACCEPTS, .Pair, and .invert` item in 6.d changelog.
> Document Pair.Pair method

- doc/Type/Enumeration.pod6
The last thing we need to have for `Enumeration provides .Int, .pred, .succ, .kv, and .pair` item of 6.d changelog.
> Document Enumeration.Int

- doc/Type/Code.pod6
Tries to address `WhateverCode and Block provide .cando` item from 6.d changelog.
Both `WhateverCode` and `Block` inherit from `Code`, so have this method. On the other hand, it says "thunks of code" and it is unclear how to create them explicitly.
> Add cando example with Block

- doc/Language/about.pod6
- doc/Language/pod.pod6
- xt/examples-compilation.t
I'm trying to address #2798. This restores a rough test plan, now showing the number of files in the test and processing each file in a subtest. I've also removed an `if False` wrapper around non-`solo` code which was needed to prevent EVAL from executing code. I don't see how any more can be eliminated to close that issue. Suggestions welcome.
Concerning #2764, I've run the test five times on `doc/Type/*.pod6` measuring maximum memory usage and cpu time using `Telemetry` and computed mean and std. deviation:
Commit | `max-rss` µ | `cpu` µ | `max-rss` σ | `cpu` σ
--- | :---: | :---: | :---: | :---:
29952fc^ (before #2764) | 1.72 GiB | 66 s | 10.9 MiB | 0.5 s
8afc8a1 (@JJ's current) | 1.51 GiB | 51 s | 4.4 MiB | 0.3 s
taboege/doc@95e3a46 (this PR) | 1.46 GiB | 47.7 s | 9.8 MiB | 0.5 s
> examples-compilation.t memory and code quality

- doc/Language/control.pod6
Addresses `start blocks and thunks get fresh $/ and $!` from 6.d changelog.
On the other hand, I am not sure where we can indicate `thunks` part. Any ideas?
> Explain $! and $/ in start block

- doc/Language/testing.pod6
https://github.com/perl6/doc/issues/2838
> Suggest prove6 over prove

- doc/Type/Lock/Async.pod6
This documents `Lock::Async.protect-or-queue-on-recursion` and
`Lock::Async.with-lock-hidden-from-recursion-check`.
Fixes #2785
The two methods were undocumented even though they're public.
Document them.
> Document missing Lock::Async methods

- doc/Type/Kernel.pod6
`Kernel.free-memory` and `Kernel.total-memory` from https://github.com/rakudo/rakudo/pull/2959/ are undocumented.
Document them.
> Document Kernel.free-memory and Kernel.total-memory

- doc/Language/operators.pod6
X::Numeric::CannotConvert Exception for infix:<x> and infix:<xx> with -Inf and NaN. Open item in 6.d Checklist https://github.com/perl6/doc/issues/2632
> Exception for infix:<x> and infix:<xx> with -Inf and NaN

- doc/Type/Exception.pod6
Extends the example to use both X::AdHoc and a custom Exception forms, adds more explanations too.
Tries to address https://github.com/perl6/doc/issues/2793
> Extend example of fail method

- doc/Language/unicode_entry.pod6
The unicode entry page has information on how to use unicode with certain shells and editors, but nothing about terminals. Terminal support needs to be documented since it's required in order to use unicode in editors and shells.
Document how to use unicode in XTerm and URxvt.
> Document how to use unicode in XTerm and URxvt, reorganise

- CREDITS
- doc/Language/packages.pod6
No output was presented in the name interpolation example, requiring the reader to execute the code to see the output.
Include the output in the form of OUTPUT comments.
> Improve consistency and completeness of Packages document

- doc/Language/regexes.pod6
The S/// operator is documented in Operators, but not in Regexes.
See #2892 
Copied the docs from Operators over.
> Add the `S///` section from operators to regexes

- template/footer.html
- template/header.html
If the `autofocus` property is set since the beginning it blocks fragment links.
Add the autofocus property when the page is totally loaded and ready.
> Fixexternallinks, close #2836, close #2657

- doc/Language/nativecall.pod6
The syntax for NativeCall callable signature constraints under Rakudo
deviates from the usual syntax. There is an issue at
rakudo/rakudo#2878 addressing this, but until this is addressed, some
minimal explanation for the strange syntax is needed.
> nativecall: Add language to address #2684

- doc/Type/Mu.pod6
This aligns with the docs for `prefix:<so>` and `:<not>`, too. Ref #2693.
The previous explanation of so() wasn't consistent with implementation or mentioned in design docs. Double-negation is a common JavaScript idiom but not relevant to Perl 6.
The extra description of the example isn't necessary, since the parenthetical mention of Junction resolution hints at why the example is relevant. Although a better example might be found, since `if` creates a Bool context and `.so()` is redundant. But it's not wrong, so it's fine for now.
Copied the text from operators#prefix_? with appropriate tweak to text. The implementation in Radudo for `method so()` calls `self.Bool`, and the docs can be just as simple.
> Align Mu.so & Mu.not docs with design

- doc/Language/regexes.pod6
Attempt to clarify, prettify, and correct some matters in the regexes-section, most notably the incorrect reference to $?NL in the discussion of the backslashed character class \n.
> Some redactional changes and corrections

- doc/Type/Any.pod6
- doc/Type/List.pod6
Somebody on IRC asked how to customize the way join treats the elements. The documentation merely stated that the elements were treated as strings, but not how this happens.
This patch clarifies that .Str is called. Also clarify how Any.join calls self.list first.
> Clarify join

- doc/Language/101-basics.pod6
- doc/Language/classtut.pod6
- doc/Language/intro.pod6
- doc/Language/objects.pod6
- doc/Language/pod.pod6
101-basics.pod6, classtut.pod6, intro.pod6, objects.pod6 and pod.pod6
Changes include minor rewording, text reflow, move from indentation to sample codes wrapped with `=code` directives, etc.
> Update several documents

- doc/Type/Metamodel/EnumHOW.pod6
None of its methods actually specify what type the object the method is
called on must be.
I just want to make sure this matches how the rest of the docs' signatures are written before pushing.
> Correct all methods' signatures in Metamodel::EnumHOW's page

- doc/Language/glossary.pod6
- doc/Language/newline.pod6
- doc/Language/quoting.pod6
- doc/Language/syntax.pod6
glossary.pod6, newline.pod6, quoting.pod6 and syntax.pod6
Changes include minor wording, text reflow, whitespace, unindenting `=code`-wrapped code samples, etc.
> Proofread several documents

- doc/Type/Enumeration.pod6
- doc/Type/Metamodel/EnumHOW.pod6
I never finished proofreading `Metamodel::EnumHOW` and `Enumeration` during the Squashathon.
Both pages were missing several methods, so I documented them. Apart from that, only minor fixes were needed. The new documentation just needs to be double-checked.
> Document missing Enumeration and Metamodel::EnumHOW methods

- doc/Language/grammars.pod6
1) A few of the sentences on the page didn't read that well.
2) The token `letter` indentation was different than a previous example.
1) Adjust a few words and phrases here and there.
2) Adjust token `letter` indentation to match previous example.
> Improve readability.  Adjust token `letter` indentation.

- doc/Language/regexes.pod6
The current regexes document contains no systematic introduction of 'metacharacters', neither as such nor in relation to 'literals'. This requires use of the term 'metacharacter' elsewhere to be accompanied by an ad-hoc, essentially out-of-place definition.
Clarification of relation between literals and metacharacters, including a discussion of escaping and quoting inside of regexes.
NOTE: I left the discussion of the match object at the end of the section untouched . I imagine that this text portion is reworked and probably given its own section when #2864 is tackled.
> Upgrade of Literals section

- doc/Language/traps.pod6
The section is unclear and seems to cause more confusion than it solves. For instance, phrases like "the latter only works sometimes" and  "$(…) lexically interpolates the given string. So <{…}> immediately breaks with more complicated inputs" provide no accurate description of anything.
The distinction between `$(...)` and `<{...}>` is currently described in the (updated) regex interpolation section of regex.pod6, which makes it clear that for the second example in the traps section to work it should have the to-be-interpolated string defined with a quoted hash, like this: `my $x = 'ailemac"#"';`, simply because `<{...}>` interpolates the return value/string as a regex. Since the situation is now clearly described in the regexes doc, this section may be deleted.
> Improvement of regex-interpolation trap section

- doc/Language/regexes.pod6
Changes:
- intro clarifying 'regular expressions' and 'regexes';
- systematic treatment of anonymous and named regex definitions;
- new subsection on common ways of matching regexes;
> Expansion of Regexes:Lexical Conventions section

- doc/Type/Metamodel/Versioning.pod6
> Document Metamodel::Versioning

- doc/Language/101-basics.pod6
I think it's handy to make that easier to find in the
documentation.
It's not as easy as it should be to find out how to put comments into Perl6 code from the official documentation.
Examples are included right in the first example on the 101 page.
I may also revisit in other places.
> Added comment syntax on 101 page.

- doc/Language/objects.pod6
The docs say a Role can be mixed into a class using "does" but fails to mention that "is" also works.
Update the docs to clarify how "is" also works to mix a Role into a class.
> Roles can also be mixed in using 'is'.

- doc/Type/Buf.pod6
These are now available in HEAD, and will be available with the 2019.10 Rakudo compiler release.
I wasn't sure how to handle this version dependency in the documentation properly.  I just added a section describing the new behaviour.  Not sure how that would work with indexing.  Suggestions / additions welcome.
> Document the new semantics of Buf.write-int* methods

- doc/HomePage.pod6
- doc/Language/community.pod6
1 - Place the Community resources in HomePage (leaving the same link in the Language page)
2 - Add a list of bots (the text is taken from perl6.org/community/IRC) to the Community page.
3 - Some editing of Raku / Perl6
4 - Added channel #raku to resource list.
> Highlight Community, add IRC bot list

- doc/Type/Seq.pod6
`elems` method on Seq is not documented... Based on implementation at https://github.com/rakudo/rakudo/blob/master/src/core.c/Seq.pm6#L51-L61
Document it.
> Document elems on Seq

- xt/headings.t
'Raku' should be a case exception in titles.
> Add Raku to case exceptions in titles

- doc/Language/functions.pod6
I think a 'the' is missing in samewith's description and also fix its example output.
> Add missing 'the' and fix example's output

- doc/Language/classtut.pod6
- Sync output with code example
- Update code example description
- Advise .^name usage
.WHAT was removed from an example in snippet in doc/Language/classtut.pod6 a year ago in favor of .^name: this is a followup
> Pursue .WHAT removal

- doc/Type/independent-routines.pod6
Reading that `sprintf` outputs its result sounds confusing.
> Clarify that sprintf returns a Str, not outputs it

- doc/Language/grammars.pod6
This pull request should close the following issue:
https://github.com/perl6/doc/issues/3085
> Fix doc bug related to how to explicitly capture whitespace using <ws>.

- doc/Language/grammars.pod6
HTTPRequest as was written did not actually work and did not produce the output documented.
There were several issues, whitespace, use of \r\n instead of specific Unicode codepoints, and other small issues (for example the attribute being initialized in some cases). The current version fixes those errors while concentrating in the use of attributes and how they are local to each element of the grammar.
The code has been corrected.
> Fixed HTTPRequest example.

- doc/Language/math.pod6
Previously this pointed into the "pulls" area, which could be confusing for git or github neophytes.
The documentation for "Doing math with Raku" has a link to the Math::Constants repository. This actually links to github.com/JJ/p6-math-constants/pulls, which is not intuitive and could be confusing.
Link to the top of the repository tree, where the readme file is a lot more useful.
> Change link for Math::Constants to point to the top of the repo.

- doc/Type/Metamodel/Documenting.pod6
- xt/words.pws
This also makes "documenting's" and "metarole" valid words.
> Document Metamodel::Documenting

- doc/Language/faq.pod6
Some "Perl 6"s which look like they had accidentally been changed to "Raku" changed back. Some "Perl 6"-ish words changed to their "Raku"-ish equivalent. Some misc editing fixes.
> Some Raku<->Perl6 changes, some misc editing also

- doc/Type/Cool.pod6
Handle irregular cases (pun intended) and whitespace to complete #3054.
These were probably missed by d41ea22d13ff2b91a9fb2be9cbc8aa8db848e587.
> Substitute Perl 6 with Raku

- doc/Language/control.pod6
Minor adaptations to the text describing the loop construct, and addition of an example illustrating use of a loop initializer variable in the outer scope after the loop has ended.
> Fixes: #3107

- assets/sass/style.scss
...and thus avoid selecting the "internal" link to language/operators#infix_//
as seen in doc/Language/typesystem.pod6
> Be more specific in selecting href to "external" sites

- doc/Language/variables.pod6
I had difficulty understanding the current section. It doesn't (or at least not sufficiently accurately) point out the precise difference between item and list assignment, assignment syntax variations, the associated operator precedences, and the role of associativity in parsing chained assignments.
See also #1810
Rewrite of section with more systematic assignment syntax examples and additional clarifications.
> Clarification of item and list assignment syntax and evaluation.

- doc/Language/101-basics.pod6
- doc/Language/operators.pod6
The P6-101 page included imprecise statements about the operation of compound assignment operators, and the actual behavior was not documented anywhere else.
The relevant text of the P6-101 page has been corrected, and the 'Assignment operators' section of the Operators page has been expanded with more detailed information about the relation between simple and compound assignment operators, and the implicit initializing behavior of compound assignment operators.
Closes #2920
> P6-101 text refinement + expansion of assignment operators section; closes: #2920

- doc/Type/List.pod6
.batch($batch) was imprecisely explained to be "similar" to .rotor($batch, :partial).
See #2969 
Description of .batch rewritten to explain that .batch($batch) is shorthand for .rotor($batch, :partial), given that .rotor($batch, :partial) is implemented as .batch($batch,1):
https://github.com/rakudo/rakudo/blob/master/src/core.c/Any-iterable-methods.pm6#L2075
> Adaptation of .batch description; closes #2969

- doc/Type/Metamodel/Mixins.pod6
- type-graph.txt
- xt/code.pws
- xt/words.pws
[Parameterization for any type](#3132) is needed. Mixins are a common use case for parameterization, but the documentation for `Metamodel::Mixins` that would be needed before examples of this would make sense doesn't exist yet.
Document `Metamodel::Mixins`.
> Document Metamodel::Mixins

- doc/Language/compilation.pod6
Issue #3043  
Although this does not address the issue directly, the aim is to provide more context for developers and users than is currently available. The tutorial is based on niner's talk. It was in a link he provided in issue #502
> new compilation tutorial

- doc/Type/IO/Socket/Async.pod6
- doc/Type/IO/Socket/Async/ListenSocket.pod6
The documentation lists that you can set `$port = 0` when listening to allow the OS to pick your port number for you. However, this presents a serious problem, which is that now you have a listener, but have no idea what port number it is listening on. Fortunately, Raku provides a special object during `tap` that provides a `socket-host` and `socket-port` for learning this information. This is not documented in the official docs.
I added documentation of the `IO::Socket::Async::ListenSocket` object returned during tapping and then make mention of it in the documentation for the `listen` method.
> Io socket async listensocket

- doc/Type/IO/Socket/Async.pod6
- doc/Type/IO/Socket/Async/ListenSocket.pod6
- xt/code.pws
The new `IO::Socket::Async::ListenSocket` docs contain some misinformation about what it's for and how it's used, as well as lack documentation for their `native-descriptor` method. However, the code examples it gives are better than the related ones in `IO::Socket::Async`'s page, which they make redundant.
- don't say `IO::Socket::Async::ListenSocket` can't be constructed (it's possible, but impractical to do and irrelevant to how it would normally be used)
- correct its `socket-host` method documentation
- document its `native-descriptor` method
- brush up the code examples provided a bit
- remove the now redundant examples from `IO::Socket::Async`'s page and refer to `IO::Socket::Async::ListenSocket` for more information instead
- add `listensocket` as a word to `xt/code.pws`
> Proofread IO::Socket::Async::ListenSocket docs and pass make xtest

- doc/Type/Seq.pod6
Even though a cached `Seq` can be considered a lazy list in the common sense of the word, the `.is-lazy` predicate has a particular meaning in Raku: if true it _guarantees_ lazy evaluation, even if the
underlying iterator is used to create another `Iterable`.
* Use "lazy" more precisely in subtitle and introduction.
* Move a more precise definition of `.is-lazy` to just below the definition of `.iterator`.
* In the definition of `.elems`, document why an infinite sequence should be declared lazy.
> Clarify when a Seq .is-lazy

- doc/Type/Exception.pod6
There is an orphan line of code in one of the examples in Exception.
Removed that orphan line of code.
> Remove orphan code line

- writing-docs/STYLEGUIDE.md
The paragraph as written uses an incorrect word ("exposition" instead of
"exposure").
The word was corrected and the paragraph reworded to remove redundancy 
and improve the overall wording.
> Use better word than 'exposition' and reword the paragraph

- doc/Type/X/Cannot/Lazy.pod6
Documentation of class `X::Cannot::Lazy` is referenced by the documentation of class `Seq` but did not yet exist.
> Document X::Cannot::Lazy

- doc/Type/Test.pod6
Not sure if this is the way it should be, or if `use-ok` should be augmented with another argument.
Also unindented code because the rest of the file didn't seem to indent its bits.
> Document passing arguments to `use-ok`

- bin/p6doc
It's hard to search the documentation from the command line
Add a `search` option to `p6doc` that looks for references to a particular term.
Examples:
```
$ bin/p6doc search comb
searching for comb
1) 5to6-perlfunc
2) Cool
3) Str
Choose: ^C
$ bin/p6doc search zip
searching for zip
1) List
Choose: ^C
$ bin/p6doc search leave
searching for leave
1) Async
2) Channel
3) Handle
4) Lock
5) independent-routines
6) phasers
7) traps
Choose: ^C
$
```
> Add search command for p6doc

- doc/Programs/01-debugging.pod6
- xt/words.pws
- The debugging programs page is a bit disorganized. More emphasis is placed on ecosystem modules than core features, and what paragraphs pertain to which section isn't entirely clear to me at first glance.
- Albeit a somewhat new module, `Trait::Traced` offers broader support for tracing than other ecosystem modules out there (to my knowledge). I may be a bit biased since it's my own module though 😉.
- Reorganize the debugging programs page.
- Add `Trait::Traced` to the ecosystem modules section.
> Reorganize and add Trait::Traced to the debugging programs page

- doc/Language/operators.pod6
The (cont), ∋ and ∌ sections look a lot like the (elem), ∈ and ∉ones and may need a few corrections.
> Fix index entries and descriptions of (cont), ∋ and ∌

- doc/Language/typesystem.pod6
- xt/code.pws
- xt/words.pws
Enum values can be typed. Enum pairs are also typed, and may be given additional roles to add behaviour and state to them. How this is all done is undocumented though.
> Document how to type enums

- doc/Type/Match.pod6
- doc/Type/Parameter.pod6
- doc/Type/Str.pod6
* Added prefix and suffix methods to Parameter class which return textual prefix and suffix of the parameter
* The Match class now has a replace-with method
* Cool.subst doesn't need a replacement string anymore
> Document a few 2020.02 additions

- doc/Language/hashmap.pod6
say ($first-instant, $second-instant) ~~ %intervals.keys.sort;  # OUTPUT: «False␤»
output should be True
output in comment is False
output in comment should be True
> correct output in comment

- doc/Language/objects.pod6
How to __call parent method__ when get a variable on the child object ? (And no control on the class method implementation)
This belongs to objects/inheritance
The solution (present in roles) is `$child.Parent::method`
I just couldn't find it, asked in the IRC
> Object: Inheritance: Add parent direct call with $obj.Parent::method

- doc/Type/Signature.pod6
- xt/words.pws
Named arguments can be used like sentinels. In this case, there's no point in there being any symbols for them, as they're unused.
See title.
> Document how to write named arguments that do not create any symbols

- doc/Type/Metamodel/Mixins.pod6
Make the URL of mixin meta method absolute: because it is then embeded in some type: like `type/Metamodel::EnumHOW`.
PS: No more broken link
> Fix URL mixin with absolute path

- doc/Language/hashmap.pod6
- doc/Language/operators.pod6
- doc/Type/Hash.pod6
The delete adverb usage/docs don't show that in addition to removing the element it
also returns the element as well as doesn't remote the element when delete is false.
Fixed up the instances I noticed.
> Doc :delete a bit more completely.

- doc/Language/regexes.pod6
$(code) interpolation was documented, but @(code) was not.
Document @(code) interpolation, with an example that uses the keys  of a hash and substitutes the corresponding values.
> Document @(code) interpolation in regex

- doc/Type/Metamodel/DefiniteHOW.pod6
- type-graph.txt
- xt/code.pws
- xt/words.pws
My `Data::Record` module uses metamethods of definite types for type-checking purposes. These are undocumented.
Document `Metamodel::DefiniteHOW`.
> Document Metamodel::DefiniteHOW

- doc/Type/Attribute.pod6
`X::Syntax::Variable::MissingInitializer` gets thrown at compile-time when you attempt to type an attribute with a `:D` type normally. As it stands now, the exception's message makes it seem like you need to give it a default value in order for it to be typed like that, but `is required` also works.
See title.
> Mention :D types in the documentation for the "is required" trait

- doc/Type/Parameter.pod6
`is raw` has special behaviour for slurpy lists, but this is undocumented.
Document it.
> Document how `is raw` behaves with slurpy list parameters

- lib/Test-Files.pm6
This allows multiple files to be set in TEST_FILES environment variable
from a shell command substitution, hence with embedded newlines
> Also split TEST_FILES on newlines

- doc/Type/Cool.pod6
- doc/Type/Str.pod6
while here:
- Str.index is a method: adjust section heading and use it in examples
- revisit Cool.index description
Refs #3229
> Document Str.index ignorecase/ignoremark

- doc/Type/Str.pod6
Refs #3229
While here note that Str.contains' Regex support is also available since
Rakudo version 2020.02.
> Document Str.contains ignorecase/ignoremark

- doc/Type/Any.pod6
- doc/Type/Iterable.pod6
I looked up the method [flat on Iterable](https://docs.raku.org/type/Iterable#method_flat) which, unlike on [Any](https://docs.raku.org/type/Any#method_flat), does not show how to flat itemized sublists
Copy and adapt that part from the documentation of `Any.flat`.
> how to flatten itemized sublists on an Iterable

- doc/Type/Attribute.pod6
The previous phrasing made it sound like calling `DEPRECATED` was somehow mandatory for attributes marked as such, which is probably not what is meant.
The code example also uses the same variable twice with different results.
This patch corrects the phrasing and the name of the variable used in the example.
> Corrects minor mistakes on DEPRECATED Attributes

- doc/Language/rb-nutshell.pod6
Ruby uses the case equality operator (`===`) in  `case` expressions ⁠—not `==`.
This is incorrectly noted in the rb-nutshell doc.
(Ruby's `===` operates very similarly to Raku's smartmatch, as far as I can tell)
Updated the paragraph that has the error.
I didn't create an issue first, but I checked to see if there was one (there wasn't).
> Fix description of Ruby case-when in rb-nutshell

- doc/Type/Supply.pod6
Closes 'Promise.in/.at and Supply.interval work with zero and negative values' in #2632
> Explicit mention behavior with negative values for interval.

- doc/Language/regexes.pod6
These sequences were only documented within enumerated character classes, but can appear just like `\w` and friends as top-level atoms, and so should be documented with them. Also, the documentation even within character classes was pretty thin, so this seeks to rectify that situation.
**Note** I'm having trouble with the build system, so I can verify that they pass through the parser, but can't actually get to the stage of writing html...
> Docs for \c, \C, \x and \X

- doc/Language/glossary.pod6
[The entry 'Raku'](https://github.com/Raku/doc/blob/master/doc/Language/glossary.pod6#L906) is looking strange. The renaming process probably caused this.
Remove the entry 'Raku' from glossary.
Maybe we should rename this entry to Perl 6 and explaing the relation between Raku and Perl 6. What do you think?
> Meaningless entry in Glossary

- doc/Language/5to6-perlfunc.pod6
- doc/Language/classtut.pod6
- doc/Language/containers.pod6
- doc/Language/control.pod6
- doc/Language/faq.pod6
- doc/Language/functions.pod6
- doc/Language/glossary.pod6
- doc/Language/grammar_tutorial.pod6
- doc/Language/io-guide.pod6
- doc/Language/iterating.pod6
- doc/Language/list.pod6
- doc/Language/nativetypes.pod6
- doc/Language/pod.pod6
- doc/Language/rb-nutshell.pod6
- doc/Language/subscripts.pod6
- doc/Language/syntax.pod6
- doc/Language/typesystem.pod6
Once this PR is merged, we can have these marked as complete:
- Pod6 (pod.pod6)
- Classes and objects (classtut.pod6)
- Lists, sequences, and arrays (list.pod6)
- Iterating (iterating.pod6)
- Glossary (glossary.pod6)
- Functions (functions.pod6)
- FAQ (faq.pod6)
- Control flow (control.pod6)
- Grammar tutorial (grammar_tutorial.pod6)
- Input/Output the definitive guide (io-guide.pod6)
- Containers (containers.pod6)
- Ruby to Raku - nutshell (rb-nutshell.pod6)
- Subscripts (subscripts.pod6)
- Perl to Raku guide - functions (5to6-perlfunc.pod6)
- Raku native types (nativetypes.pod6)
- Syntax (syntax.pod6)
- Type system (typesystem.pod6)
> Change .perl to .raku in language documents, ref #3309

- doc/Language/subscripts.pod6
Emphasize advice on how to implement AT-KEY and AT-PO methods by
removing parentheses
> Remove parenthesis

- doc/Type/independent-routines.pod6
Addresses Raku doc GH issue #3394
The `$` symbol has a special meaning in the `sprintf` format string and
must be escaped in a double-quoted format string if intended to be
used as a literal character. That fact is very briefly described in an
offhand manner, and it may result in a hard-to-find error due to an
error message that, up to Rakudo release 2020.05, does not mention it.
This commit should help by warning of a possible interpolated `$`
symbol in the format string upon input errors when the reported `%`
directives in the format string exceed the number of elements in the
`*@args` array.
The commit also expands information on the directive `parameter index` as well as
adding a little more textual structure with `=head3` Pod directives.
In addition, some other cleanups are …
> Add more details of routine sprintf and its format string and *@args

- doc/Language/exceptions.pod6
- doc/Language/operators.pod6
- doc/Language/regexes.pod6
- doc/Type/IO/Handle.pod6
- doc/Type/List.pod6
- doc/Type/Map.pod6
- doc/Type/Mu.pod6
- doc/Type/Parameter.pod6
- doc/Type/Range.pod6
- doc/Type/Str.pod6
- doc/Type/Supply.pod6
- doc/Type/independent-routines.pod6
The latest convention for the docs is to show output in examples in
this manner:
...some Raku code...   # OUTPUT: <<...some example output...\n>>
This commit updates examples to be consistent with the "# OUTPUT: ".
part of the convention.
It also: (1) adds French quotes and newlines around output
examples that are missing them and (2) aligns output examples
vertically when feasible.
Files affected:
+ doc/Language/exceptions.pod6
+ doc/Language/operators.pod6
+ doc/Language/regexes.pod6
+ doc/Type/IO/Handle.pod6
+ doc/Type/List.pod6
+ doc/Type/Map.pod6
+ doc/Type/Mu.pod6
+ doc/Type/Parameter.pod6
+ doc/Type/Range.pod6
+ doc/Type/Str.pod6
+ doc/Type/Supply.pod6
+ doc/Type/independent-routines.pod6
> Replace 'RESULT' with 'OUTPUT:' for consistency

- bin/p6doc
Because the pseudo-`Type` name 'independent-routines' contains the string
'routine', it was being filtered out of the results list when looking up
a routine in it, such as `p6doc -f sprintf`.
```
$ p6doc -f sprintf
No such type ''
```
Be less cavalier about filtering the `@types` array.
> Fix -f routine lookup in Type/independent-routines

- README.md
A typo and some extra blanks.
Remove these mistakes.
Also, names of links to localized README files are now in both English and the corresponding language(currently Chinese only).
> Fix typo & removed extra blank lines

- doc/Type/DateTime.pod6
- doc/Type/List.pod6
Different quoting characters were being used for `infix:<cmp>`. #3038
Replaced `infix:«cmp»` with `infix:<cmp>`.
Also replaced a heading with `< >`. 
Operators doc has [heading](https://github.com/Raku/doc/blob/a07587818a5a9826dd49e1f72dfd33014d238a42/doc/Language/operators.pod6#L1902) with `C«cmp»` but I left it for consistency with the rest of the headers in that file. Let me know and I can update those headings as well.
```
$ grep -r 'infix:.cmp.'
doc/Type/DateTime.pod6:    multi sub infix:<cmp>(DateTime:D \a, DateTime:D \b --> Order:D)
doc/Type/ComplexStr.pod6:    multi sub infix:<cmp>(ComplexStr:D $a, ComplexStr:D $b)
doc/Type/Range.pod6:    multi sub infix:<cmp>(Range:D \a, Range:D \b --> Order:D)
doc/Type/Range.pod6:    multi sub infix:<cmp>(Num(Real) \a, Range:D \b --> Order:D) …
```
> Use single angle brackets for infix cmp. Fixes #3038.

- doc/Type/Date.pod6
- doc/Type/Dateish.pod6
- doc/Type/Str.pod6
* `Str` now has `.Date` and `DateTime` coercers
* `Date.yyyy-mm-dd` now takes a separator parameter, defaulting to `-`
* Add `Date.dd-mm-yyyy` and `Date.mm-dd-yyyy` methods
* Add `Date.last-date-in-month` and `Date.first-day-in-month` methods
> Document few additions introduced with 2020.05

- xt/p6doc-blackbox.t
On OpenBSD, `more` doesn't like when `TERM` is unset, causing tests run here
to fail.
> Set the TERM environment variable's value in xt/p6doc-blackbox.t

- doc/Language/py-nutshell.pod6
This is to help users coming from any language with
Tuples find a page listing an equivalent Raku feature.
As identified in issue #3393 I am trying to add sections using keywords
in other languages that have Raku equivalents with different names.
I started with the Python tuple.
> Add tuple section for Python to Raku page.

- doc/Language/haskell-to-p6.pod6
Someone coming from Haskell, Common Lisp, and
several other functional languages might want to know
if Raku supports tail call optimization.
I can't find any recent detailed discussions on it, but
my understanding is that it's not in the Raku language spec
or in the Rakudo implementation.
Per issue #3393  I wanted to add a section on tail call optimization.
A short section mentioning the feature and that Raku does not require it, and would get smaller benefit from it than Haskell or many other functional programming languages.
> Add section on tail call optimization/elimination.

- doc/Language/control.pod6
This is just for a search convenience if someone
coming from a C-style language background searches for 'case' or
'case statements' instead of 'switch'.
As part of #3393 
If the user exploring Raku has not encountered given/when in Raku before,
they might search the site using 'case' or 'case statement'.  Right now those terms
do not take the user directly to the given/when documentation.
I am not skilled with pod6 format, so it is likely I got the syntax wrong.  But
I tried to make a change that would add 'case statements' to the search index.
> Attempt to add 'case statements' to indexing

- doc/Language/101-basics.pod6
* Organize the page such that h1 headers introduce a few lines of code
that might be further discussed by subheaders. This way the examples
are self-contained to their own section (and subsections).
* Remove meta-commentary from the sample code. Instead, leave it for the
discussion text.
* Index terms more clearly.
Refs: #3320
> Revise 'Raku by example 101' page

- doc/Type/Str.pod6
Missing example of how to substitute only the last match with `.subst`.
Add missing examples. While here, clean up formatting of nearby examples, too.
> Str.subst: Add examples for nth(*), etc.

- doc/Language/regexes.pod6
- xt/words.pws
#3408 and #3433 
xt/aspell.t and xt/braces.t failed on doc/Language/regexes.pod6 file.
1. Add 'square' to description of \x character class to fix xt/braces test failures.
2. Add 'UCD' to xt/words.pws to fix xt/aspell test failures. 'UCD' is used here:
https://github.com/Raku/doc/blob/b91e0eb3f4dda9cae5dd94f1b6c1115b530420ef/doc/Language/regexes.pod6#L511-L518
> Fix doc/Language/regexes.pod6 xt/ failures. Fixes #3408.

- bin/p6doc
Hopefully this will help people find the right place to apply their
efforts. And prevent JJ from having to link to #2983 in more new PRs.
Examples of the need include #3196, #3202, #3422
> p6doc: Add a deprecation comment to inform developers

- doc/Language/variables.pod6
It's easy to put `constant $foo = changes-at-runtime()` in a module, not realizing that it will be precompiled on the first run. The previous warning here was too milquetoast and easy to gloss over.
> Language/variables: Stronger warning about pre-compiled constants

- doc/Type/Lock/Async.pod6
Closes https://github.com/Raku/doc/issues/3411
The example used some sleep and prints.
A more real-world-y example is provided with reading/modifying an array concurrently.
> Add a more realistic Lock::Async.protect example

- doc/Type/Proc.pod6
Proc::Async does not override Bool, so closes https://github.com/Raku/doc/issues/3397
No docs for the method.
Document it.
> Document Proc.Bool method

- doc/Language/functions.pod6
Previously, the search term and category were reversed, which
created resulted in a buggy results displayed to the user on search.
Use the correct order.
Can we try if it helps with https://github.com/Raku/doc/issues/3190 ?
> Fix index syntax of pointy block

- doc/Language/control.pod6
Previously, there were two separate headers for proceed and succeed,
and likely meant to be read as "header + header + content".
ALas, on content pages used to display search results, a single pair of "header + content"
is delivered, and it is actually read as "header + nothing + header + content".
To avoid an empty page for the first header, just merge those two into a single one.
Fixes https://github.com/Raku/doc/issues/3167
> Fix indexing of proceed/succeed

- doc/Type/Proc.pod6
- doc/Type/Proc/Async.pod6
- doc/Type/independent-routines.pod6
This PR is part of a set of PRs related to [Raku/problem-solving#20](https://github.com/Raku/problem-solving/issues/20). It documents the changes discussed in that problem-solving ticket.
In short: Provide a way to reliably control argument quoting used on Windows.
> Document `:$win-verbatim-args` argument of `run()` and related functions

- doc/Language/functions.pod6
- xt/code.pws
The documentation on proto was not as clear as I needed. I tried several times to understand it, but failed. 
I got it nearly right when I asked on perl6-users.  
Crucially '{*}' is a special token without whitespace - this needs to be noted.  
The extra example combines the proto declaration with methods that use it.
Added a note and a longer example
> Expand on the use of {*} with proto

- doc/Language/operators.pod6
The docs currently list the associativity for the `infix:<Z>` operator as `assoc<chain>`, but it's actual associativity is `assoc<list>`.  `Z` has list associativity because `$a Z $b Z $c == infix:<Z>($a, $b, $c)`.  It does not have chain associativity: `($a Z $b Z $c) ≠ ($a Z $b) and ($b Z $c)`.
This PR  corrects the associativity for the `infix:<Z>` operator from `assoc<chain>` to `assoc<list>`.  The chart at the top of the page already correctly indicated that `Z` has list associativity and thus does not need to be updated.
> Correct associativity for infix:<Z>

- doc/Language/contexts.pod6
I was confused with the original names. Also, the text after the code example talks about strings being interpreted in numeric context, so ```$not-a-string``` looks off.
I guess the new names match the original author's intention.
> Tweak names of two variables

- doc/Language/regexes.pod6
The code referred to as a "shorthand" is in fact longer in bytes and in the number of regex atoms involved.
The "shorthand" formulation is removed and another quality of the `~` operator is mentioned as a substitute, then the paragraph is reflowed.
> Remove false "shorthand"

- doc/Language/5to6-perlfunc.pod6
- doc/Language/5to6-perlop.pod6
- doc/Language/concurrency.pod6
- doc/Language/control.pod6
- doc/Language/glossary.pod6
- doc/Language/operators.pod6
- doc/Language/regexes.pod6
- doc/Language/traps.pod6
- doc/Language/variables.pod6
- doc/Type/Attribute.pod6
- doc/Type/Bool.pod6
- doc/Type/Cancellation.pod6
- doc/Type/List.pod6
- doc/Type/Mu.pod6
- doc/Type/Pair.pod6
- doc/Type/Regex.pod6
... since it comes from a person's name.  This should address issue #3517; although I'm not 100% sure if I've satisfied the requirements of @coke's comment about linking to the Bool enum, as I didn't find (what I thought) were references to the Raku Boolean type, however I might have misread the docs in those places.
> Capitalise the word "Boolean"

- doc/Language/traps.pod6
- doc/Type/Pair.pod6
@JJ mentioned in #3542 two locations where it would be more appropriate
to refer to the Bool type as opposed to Booleans.  This commit addresses
this issue and helps address #3517.
> Link to Bool types

- Makefile
- README.md
This target name is easier to remember than the `documentable update` command as it uses the make infrastructure which is already present.  It also uses the same general interface to the various build processes provided by make (i.e. one can use `make <target>` as opposed to having to remember what command is necessary to perform a particular operation).  Also, this wraps the `update` process behind an interface; the details of which can be changed in the future without changing the interface.
I've also updated the README to mention the new target name.
Also, and somewhat unrelated to the above changes, I've simplified the docs in the README for HTML generation as well as have removed superfluous vertical whitespace.  These changes have been put into separate commits so that they can be …
> Add `update-html` make target

- doc/Language/nativecall.pod6
Because of its name, the subject module is hard to find. Additionally, with its link shown early on in the very lengthy NativeCall description, it could encourage more authors to contribute Raku wrappers for their favorite libraries since they could get help starting with framework code.
Short descrription and a link to the parent repo.
> Add short description for a NativeCall helper

- doc/Type/Bag.pod6
- doc/Type/BagHash.pod6
- mention <> postcircumfix for BagHash
- add ref to operators' description
> More on { } and < > operators for Bag and BagHash

- doc/Type/List.pod6
- Remove duplicate note about the optional separator for the method form
- It's the subroutine form that is slurpy and flattening
- Group related examples
- Correct a typo
> Rework List.join examples and description

- doc/Type/SetHash.pod6
Add method-level documentation and overview examples using the `set` and `unset` methods on `HashSet`.  This PR represents a subset of the changes proposed in #3572 – specifically, just the few that are clearly needed in light of #3577.   When merged, this will complete one of the items in the #3229 checklist.
> Document the `set` and `unset` SetHash methods

- doc/Type/SetHash.pod6
The previous version of this file inadvertently refereed to the `unset` method as the `set` method.  This is now fixed.
> Fix typo in SetHash.unset method

- doc/Language/testing.pod6
The Test module previously included the language "as with any Perl project", which outdatedly implied that Raku projects are Perl projects.
> Remove gratuitous Perl mention from Tests

- Makefile
This passes the `--highlight` flag to Documentable via the `update-html` target, which is consistent with how the `html` target 
invokes Documentable.
Closes #3586
> Make `make update-html` generate syntax highlighting

- doc/Type/BagHash.pod6
- xt/pws/words.pws
This PR adds method documentation for the `add` and `remove` methods on the `BagHash` class and adds narrative documentation and examples showing their use.  It also adds "baghash's" to the spellcheck dictionary to prevent a test failure.
Closes #3569
> Add the `add` and `remove` BagHash methods

- xt/pws/words.pws
When looking into aspell for #3593, I discovered that the header in an aspell word list  can optionally have a hint about the length of the list.  Giving aspell this hint allows it to perform very slightly (but measurably) faster.  This appears to improve the speed of our spelling test by ~2%.  The hint does not need to be perfectly accurate to be helpful, so it won't be a problem if the hint isn't updated as contributors add more words to the aspell word list.
See [the relevant aspell docs](http://aspell.net/man-html/Format-of-the-Personal-and-Replacement-Dictionaries.html#Format-of-the-Personal-and-Replacement-Dictionaries).
> Provide a length hint for aspell

- META6.json
- Makefile
- README.md
- doc/HomePage.pod6
The Makefile targets for generating EPUB and "bigpage" (one-page HTML) were removed as they were broken. Now they may be restored - but only after (or if) https://github.com/perl6/perl6-pod-to-bigpage/pull/36 is merged & released.
This should solve #1981.
> Restore epub and bigpage

- doc/Type/Code.pod6
Code.line's documentation previously just stated that it returns the line of the code object's declaration.  This is *usually* true, but
isn't true for auto-generated code objects, which don't have a declaration.  This commit explains how the method works in that case.  Closes #3606
> Expand Code.line documentation

- xt/check-signatures.t
This commit adds a new xtest, check-signatures.t and closes #3604.  Here is the description of the test from its documentation:
> For each method documented in a .pod6 file in doc/doc/Type/, this test compares the documented signature against the signature in the Rakudo source code.  Because we are documenting _Raku_ and not _Rakudo_, detecting a difference in the signature does not automatically cause the test to fail: some differences in signature (such as different names for positional parameters) represent different implementation choices rather than an error in the docs.
>
> To ensure that implementation details don't cause failing tests, we check only for certain discrepancies that are guaranteed to indicate a substantive/non-implementation detail mismatch between Rakudo and the …
> Add xt/check-signatures

- doc/Language/regexes.pod6
The `<~~>` recursive regex was previously undocumented; now it is, with examples.  Closes #3533
> Add documentation for recursive Regex <~~>

- doc/Programs/02-reading-docs.pod6
https://github.com/Raku/doc/blob/master/doc/Programs/02-reading-docs.pod6 still recommends using `p6doc` to read POD from the command-line. Unfortunately the latest version of the `p6doc` distro (as installed by `zef install p6doc`) does contain neither the `p6doc` nor the `rakudoc` executable (I tried to `zef install p6doc`, but I found neither `p6doc` nor `rakudoc` executable after successfully installing it).
It looks to me that the command-line POD reader tool, which used to live in the https://github.com/Raku/doc repo and called `p6doc` now lives in a separate repo, https://github.com/Raku/rakudoc, and it's called `rakudoc` now; and now the `p6doc` distro (from the https://github.com/Raku/doc repo) only contains the POD, but not the command-line reader tool. To make things even …
> Update 02-reading-docs.pod6 - s/p6doc/rakudoc/g

- doc/Type/Any.pod6
- doc/Type/Backtrace/Frame.pod6
- doc/Type/Baggy.pod6
- doc/Type/Blob.pod6
- doc/Type/Buf.pod6
- doc/Type/Channel.pod6
- doc/Type/ComplexStr.pod6
- doc/Type/Cool.pod6
- doc/Type/Date.pod6
- doc/Type/DateTime.pod6
- doc/Type/Dateish.pod6
- doc/Type/Hash.pod6
- doc/Type/IO/Handle.pod6
- doc/Type/IO/Path.pod6
- doc/Type/IO/Socket/Async.pod6
- doc/Type/IO/Spec/Cygwin.pod6
- doc/Type/IO/Spec/Unix.pod6
- doc/Type/IO/Spec/Win32.pod6
- doc/Type/Iterable.pod6
- doc/Type/List.pod6
- doc/Type/Mu.pod6
- doc/Type/Pair.pod6
- doc/Type/Promise.pod6
- doc/Type/Range.pod6
- doc/Type/RatStr.pod6
- doc/Type/Real.pod6
- doc/Type/Setty.pod6
- doc/Type/Str.pod6
- doc/Type/Thread.pod6
This PR fixes the errors detected by xt/check-signatures.t.  Most of these were simple typos (typically forgetting `:`).  Nearly all others were places where Rakudo constrains the invocant but we did not.
One change was slightly more substantive: we had inadvertently documented the `match` method twice in `Cool`, so I merged the two definitions.
> Fix typos detected by xt/check-signatures.t

- doc/Language/typesystem.pod6
See this discussion: https://colabti.org/irclogger/irclogger_log/raku?date=2020-09-07#l201
The use of a Whatever was mentioned, but not documented in the examples. This PR adds such an example.
An example of the use of a HyperWhateverable would also be nice, but I don't understand the concept well enough to add one. Maybe in a future PR.
> - Document the use of a Whatever to delegate all methods from a class.

- doc/Language/traits.pod6
- doc/Type/Code.pod6
- xref implementation-detail trait
- fix pasto (trait -> method)
- give is-implementation-detail its own section in implementation-detail
trait's description, hence nicely grouped in search results and routine
page
> Revisite (is-)implementation-detail

- doc/Type/Array.pod6
- reduce repetition
- add a missing self mention
- remove an extraneous 'just'
> Tweak Array.splice description

- doc/Type/Map.pod6
The `%m is Map` syntax is not easily discovered as it is only shown on the `Syntax` page.
Give it some more visibility by also showcasing it on the `Map` page itself.
> Promote `%d is Map` syntax more

- doc/Language/functions.pod6
The listed output for the extended proto example did not match the code, and two of the functions had the same message, making following the code more difficult.
The messages printed by the methods have been modified so they are all different, and the output listing has been updated after executing the code.
> Fix output for proto example

- doc/Type/Routine.pod6
As stated in #3579:
> But pick(2..5) is the same as pick(4). Seeing this in the docs had me running to the "pick" documentation, and trying things out in the REPL.
As suggested on that ticket, the use of `pick` has been simplified.
> Simplify use of pick in is-pure documentation

- doc/Language/objects.pod6
- doc/Language/operators.pod6
- xt/pws/code.pws
The special syntax for initialising the single public attribute provided by a role in a runtime mixin (using the `but` or `does` operator) is not documented.
This should fix #3658.
> Documenting the special syntax for initialising the single public attribute of a role in runtime mixin

- doc/Language/haskell-to-p6.pod6
To make literal behaving like regular function sorround operator with parens. To get opposite sorround function with backticks.
Proper syntax provided.
> Fix typo in haskell example

- doc/Language/objects.pod6
- doc/Type/Mu.pod6
This is mostly a rewording and restructuring of the previous material with the aim of being clearer and easier to understand.
Also several statements that I believe to be false have been corrected:
- There is no need to pass arguments to superclasses during construction.
- `BUILD` methods accessing attributes via `self.^attributes` are not a prerequisite for implementing custom `new` methods.
- In an inheritance hierarchy each `TWEAK` method is called after the corresponding `BUILD` method not after all `BUILD` methods in all classes have run.
> Rework object construction documentation

- doc/Language/faq.pod6
- resources/i18n/de/README.de.md
- resources/i18n/es/README.es.md
- resources/i18n/fr/README.fr.md
- resources/i18n/it/README.it.md
- resources/i18n/jp/README.jp.md
- resources/i18n/nl/README.nl.md
- resources/i18n/pt/README.pt.md
Replace `rakudobrew` with its successor `rakubrew` where it makes sense. No need to send readers to a page that then forwards them to rakubrew.
> rakudobrew -> rakubrew

- resources/i18n/es/README.es.md
The text `în modul` is not Spanish. It was copied by accident from a different language.
It was replaced by the equivalent "en modo".
> Replace non-Spanish phrase

- doc/Programs/03-environment-variables.pod6
`doc/Programs/03-environment-variables.pod6` is a copy of [rakudo/docs/running.pod]<https://github.com/rakudo/rakudo/blob/master/docs/running.pod> but ran out of sync. Merge the two files. Also now include all bits of the rakudo/rakudo version of the file and not only the environment variable paragraph. As a consequence rename the file to `03-running-rakudo.pod6`.
Of note this pulls in the documentation for the new `rakuw.exe` and `rakudow.exe` executables.
> Rename and update Programs/03-environment-variables.pod6

- highlights/highlight-file.coffee
- highlights/highlight-filename-from-stdin.coffee
- highlights/highlight-folder.coffee
... when using a recent version of Raku/atom-language-perl6
Recently the scope name for Raku code has changed from 'source.perl6fe'
to 'source.raku' in the package atom-language-perl6.
See Raku/atom-language-perl6#96
We try to detect this change by testing for the presence of grammar file
'raku.cson', which beforehand was named 'perl6fe.cson'
Also, I suspect the script highlights/highlight-folder.coffee is not really used anymore. Perhaps it could be removed ?
> Fix code highlighting using the correct scope name

- doc/Type/Signature.pod6
The runtime creation of a `Signature` object silently fails when arguments of `Signature.new` have a wrong type. This issue currently is not documented.
Moreover the given example precisely show a wrong type for the parameter `count` and would not work.
(See rakudo/rakudo issue #4014)
1. Modify the example to show the right type
2. Add a small explanatory paragraph to warn the users
> Add a warning paragraph about type of arguments of Signature.new

- doc/Language/functions.pod6
- doc/Type/Signature.pod6
The difference between `+` and `+@` slurpies was not clear.
> Document behavior of the + slurpy

- doc/Type/Map.pod6
There are two ways to ensure that a literal pair is not interpreted
as a named argument. Quoting the key is arguably the clearest.
> Improve documentation of Map.new

- doc/Type/Hash.pod6
* correct signature
* sub `push` throws if it receives an unexpected named argument
> Improve documentation of Hash.push

- doc/Type/IO/Path.pod6
Flag added in https://github.com/rakudo/rakudo/pull/3980
(Probably a bit early to merge right now)
> Document absolute parameter for IO::Path symlink method

- doc/Type/Test.pod6
... to untie them from the parameters' names
> Rephrase descriptions

- doc/Language/rb-nutshell.pod6
OO code example in rb-nutshell doesn't work #3706
Code snippet example "is bogus code in several ways, generating warnings, failing to initialize the object, etc."
The snippet uses BUILD to access properties at instantiation, but they don't yet exist. TWEAK must be used as it runs after the properties are set.
For clarity, have removed private attributes from this example as they are not referred to.
> Issue 3706

- doc/Type/Slip.pod6
Slip documentation give example result that doesn't mesh with current rakudo result #3709
Fixed example result. Checked with v6.c and the result in the original example was still wrong, so no versioning required.
> Fix slip example error

- doc/Type/independent-routines.pod6
- ref #2905
- Add a small introduction to EVAL routine's description
- Bring EVAL prototype (mostly) in sync with Rakudo's current
implementation
- Also mention EVALFILE's $check parameter
- Use 'Perl' word
- Use '.raku' filename suffix
> Document EVAL $check and $filename parameters

- doc/Type/independent-routines.pod6
While here minor rewriting of {s,}printf's descriptions, including the
acknowledgment that this document's sprintf section holds the reference
to printf format description :-)
> Remove references to Str.sprintf

- doc/Language/modules.pod6
There is important information in https://stackoverflow.com/questions/55661464/what-is-the-difference-between-i-and-ilib-in-perl6
that is not reflected in the documentation. I have wasted HOURS of time getting a module to install properly because I did not know this.
> Update modules.pod6 to include Testing modules

- doc/Type/Proc.pod6
- doc/Type/Proc/Async.pod6
- doc/Type/independent-routines.pod6
Add documentation for the new Proc::Async :arg0 argument implemented in [rakudo/rakudo#4166](https://github.com/rakudo/rakudo/pull/4166).
> Document new Proc(::Async) arg `arg0`

- doc/Type/Array.pod6
When a type's routine documentation is rendered as a part of
'/routine/RoutineName', a link to the documentation of another routine for
the same type needs to provided with an absolute path ('/type/Type#...').
> Use absolute path to routine's documentation

- doc/Language/unicode_entry.pod6
Please review and advice: I had some doubts about adding a 55 line-long example.
Input of Unicode characters can be simplified by using dead keys and XCompose
This PR shows a way to add several two-key combinations to a user's ~/.XCompose file in order to let them enter easily all the relevant Unicode characters used by Raku.
> Input Unicode characters with two-key combinations

- doc/Programs/03-environment-variables.pod6
`F<...>` is not a standard FormatCode, either in the current Pod6 documentation, or in Damian Conway's original spec. This is the only Raku documentation content file to contain `F<...>`. The current standard HTML renderer just stringifies `F< ... >` to `F< ...>`, which is quite ugly imho. 
I have replaced `F<...>` with `B<...>`, which is a standard FormatCode.
> Programs/03-Environment... remove F<

- doc/Language/pod.pod6
The `Pod::To::HTML` renderer automatically translates the token `::` in a L<> to `/`
In Perl sibling languages, a Module called `Some::Module` resides in `lib/Some/Module`, so the token `::` is a synonym for `/` or directory marker.
This assumption has been carried unremarked into Raku, even though there is no need for directory markers to be followed. 
In VERY many Pod6 files documentation authors have used the notation `L<some reference|type/X::Inheritance::NotComposed>` to refer to the file `doc/Type/X/Inheritance/NotComposed.pod6`.
Since there tens of such references, changing the behaviour is not worth the effort.
Consequently, the behaviour should simply be documented.
> Undocumented L<> behaviour

- doc/Language/community.pod6
The domain `rakudo.party` no longer exists. Since `Undercover` bot only differs from SourceBaby because it points to wtf.rakudo.party,
this link is pointless. Zoffix, perhaps could point to a different domain???
> #3883 remove non-existent host

- doc/Language/5to6-perlfunc.pod6
P5rewinddir is referenced, but the module no longer exists at all. I cannot find a substitute.
I see no reason why we don't just state the Raku does not implement the functionality.
> issue #3883 remove 404

- doc/Language/faq.pod6
- Replace 'posts' with 'news', which is a working page on rakudo.org
- correct download path reference
- reference 'star/etc/modules.txt' which exists. (Possibly better to eliminate this link altogether, but being minimal here)
> Issue #3883 remove 404 replace with working

- doc/Type/DateTime.pod6
The description is wrong, the new method for epoch (posix) takes a Numeric:D argument, not an Int.
Corrected the description
> Correct the description of the epoch (posix) DateTime new method.

- doc/Language/operators.pod6
Removing B<..> **inside** a X<> for $*COLLATION .  
The problem is that there is no specification for a corresponding `L<>` in another file. As the present, the link author has to know how the target will be rendered. So `B<>` could be rendered as `<b> ... </b>` or `<strong>...</strong>` in HTML. **BUT** if this were to be rendered in some other output format (pdf? epub? latex?), the link would fail. This has already happened in `Language/Operators`, where the link author did not include `<strong>...</strong>` in the link.
So, I have removed B<> inside the X<>, and simplified the X<>, and corrected the link in Operators.
If this has a knock-on effect in other documents, it will be picked up in `Collection` tests when the documentation files are re-rendered.
> Related #3841

- doc/Language/typesystem.pod6
Part of  #3841 . But I'm flagging this error because the orginal documentation calls `.^` a postfix op, but in `
language/operators` it is called a metamethod. So I have also change 'postfix' to 'metamethod' to be consistent.
> Reference error to .^

- doc/Type/Proc.pod6
`Type/Independent-routines` contains a reference to `Proc#sub_run` but `Type/Proc` does not contain any target for `run`.
So I have inserted a X<> around the first explanation of `run` in Proc. This provides a target for Independent-routines (also opening separate PR with new target)
BUT, for consistency, `run` should be listed as sub along with `new` and `shell`. Also relationship with new should be illustrated. This is not done in this PR.
> Insert missing target into Proc #3841

- doc/Type/Map.pod6
Hash → /type/Hash
A link to the Hash class page generates a 404 error
> Correct a link to Hash

- xt/word-variants.t
... as it should be written 'Boolean'.
This word variant test is all about case, thus the %variants hash now
contains Regex values with the case-insensitive adverb when applicable.
> Search/test for the word 'boolean', ref #3517

- doc/Type/Any.pod6
The only example of a named sort routine is using the trick of referencing a operator by its "name".
No example is provided of creating a new separate sort routine, and passing it to .sort .
A minimal code example is added: a short named sub, and usage of that sub on data whose results highlights the sorting *and* the stability,  since ties are included in the data.
> Add complete example of a callable sort routine #3883

- Makefile
- xt/pws/words.pws
`make ctest` was broken, unable to find the `tabs` test.
This was due to a incomplete test renumbering from 201128008 and 04702f1fb .
Also, the aspell test was failing from missing new words.
One-line test renumbering in Makefile .
Words added to words.pws .
No separate Github issue was created. Please let me know if I should have created an issue for a minor fix like this.
> Fixed ctest and aspell

- doc/Type/Iterable.pod6
From IRC:
```
Jun 14 15:37:13 <xinming>	Hi, I always get confused about .hyper/.race, which one ensures order of results, the other doesn't, Any hints on how I can remember this? Thx
Jun 14 15:37:32 <xinming>	I've looked-up the raku doc over and over again :-(
Jun 14 15:38:09 <dakkar>	xinming: in a `.race`, you never know who's goinig to arrive first
Jun 14 15:40:00 <dakkar>	xinming: does that help?
Jun 14 15:42:26 <xinming>	dakkar: got it, thx
Jun 14 15:42:38 <xinming>	this helped a lot.
Jun 14 15:42:48 <dakkar>	maybe https://docs.raku.org/type/Iterable#method_race should say that…
```
It may not be obvious, especially to non-native English speakers, that the name `.race` implies unpredictable ordering.
Mention that in the documentation.
> add a mnemonic for `Iterable.race`

- doc/Type/DateTime.pod6
Three new methods have been added to class `DateTime` to Raku for the next release (via merged Rakudo PR #4288) and need documenting:
+ `day-fraction`
+ `julian-date`
+ `modified-julian-date`
Proposed doc entries for the three new methods.
> Add description of three new DateTime methods

- doc/Type/Callable.pod6
Text in [Callable](https://docs.raku.org/type/Callable#___top):
> If the object needs to be stored in a &-sigiled container, **is** has to implement Callable.
(my emphasis).
the one-character change 
> is has to -> **it** has to
> fix typo in Callable.pod6

- doc/Language/operators.pod6
Based on the current docs, I thought that `foo.&{...}` created an unnamed method and called it on `foo`.  However, [Jonathan's recent Stack Overflow answer](https://stackoverflow.com/questions/68308991/what-is-the-intended-value-of-routine/68327774) clarified that `.&` creates a `Block` and calls that `Block` with method syntax.
This commit clarifies the description to avoid similar confusion.
> clarify .& methodop

- doc/Language/py-nutshell.pod6
was wrong Python syntax, or, dict() definition (with {} literal) in fact tried to use (non-existent) variables instead of string literals
> fix Python (dict key string) syntax

- doc/Language/js-nutshell.pod6
- doc/Language/py-nutshell.pod6
Previously, 'override' implied that the value of the outer scope may change if a variable of the same name is defined in an inner scope. I have clarified this.
> clarify sentence, fix typo

- doc/Type/Cool.pod6
This fixes routine examples' excessive nested quoting;
longest uniname probably from older data, current one is 6 chars longer.
> Uniname examples fix/update

- doc/Language/functions.pod6
hi,
It seems `and` was meant in `hour > 8 or hour < 22` 
but I think chained comparison is better!
> using chaining operators in comparison

- doc/Language/py-nutshell.pod6
Resolves #3924.
Modified from suggestion in issue to include `kv()`’s other use case in maps,
matching Python’s `dict.items()`.
> py-nutshell: Add how to enumerate in iteration

- doc/Language/faq.pod6
- doc/Type/Array.pod6
- doc/Type/Parameter.pod6
Just a small fix to add missing `#` character on OUTPUT comment.
> Add missing "#" on OUTPUT comment

- util/new-type.raku
```
util/new-type.raku --kind=role Some::Role
```
This generated the following stub
```
=head1 Methods
=head2 method flurb
method flurb(Some::Role:D: *@args --> Str)
method description here
=end pod
```
It should have been
```
=begin pod
=TITLE role Some::Role
=SUBTITLE ...
role Some::Role is SuperClass { ... }
Synopsis goes here
=head1 Methods
=head2 method flurb
method flurb(Some::Role:D: *@args --> Str)
method description here
=end pod
```
It happened due to file truncation when writing to it twice.
- fixed the truncation issue.
- a variable interpolation issue.
- check to only create the file if it does not exist.
- a comment to help with  #3906.
> Fix file truncate and extrapolation errors in stub doc generation

- doc/Language/regexes.pod6
The docs previously mentioned that you can  use `\` to escape characters inside `<[  ]>` ; this PR adds the fact that you don't need to escape most non-alphanumeric characters the way you do in the portion of a regex outside `<[ ]>` and that you must escape (rather than quote) characters inside `<[ ]>` for them to have their literal meaning.
> Explain behavior of non-alphanumerics in <[ ]>

- doc/Language/create-cli.pod6
When passing an indeterminate number of parameters to `sub MAIN` there might be some confusion that `sub MAIN(@a)` might work. It took me a while to debug that such a declaration will not accept any number of parameters.
A simple example that uses slurpy parameters `sub MAIN(*@a)` to accept multiple arguments.
PR is relevant to the issue: https://github.com/Raku/doc/issues/2167
> passing indeterminate number of parameters to MAIN

- doc/Language/regexes.pod6
A regex declared with `rx` allows adverbs both before the delimiter (`rx:s/pattern/`) and after (`rx/:s pattern/`), but the docs only mentioned the first option.  This fixes that, and brings the rx section of the page into alignment with the adverb section.
> Clarify where rx declarator allows adverbs

- doc/Language/rb-nutshell.pod6
The Ruby "in a nutshell" page shows the following syntax
foo_method = &foo
This is not valid Ruby syntax.
Ruby methods are strictly in a different namespace than values. To convert a method (such as one named `foo`) to a first-class value, we use the built-in method called, appropriately, `method`.
def foo
...
end
foo_method = method(:foo)
Then we call it using the call syntax. The following two lines are equivalent
foo_method.()
foo_method.call
This PR updates the Ruby code snippet in question.
> Corrected Ruby nutshell typo

- doc/Language/functions.pod6
The docs previously stated that `samewith` calls the same multi _candidate_, but `samewith` calls the entire `multi`.  This PR corrects that, and adds an example that illustrates `samewith`'s behavior.  It also changes the name of the example function (which computes the factorial of a number) from `a` to `factorial` for clarity.
> Correct description of samewith

- doc/Language/variables.pod6
This PR adds a note that `&?ROUTINE` refers to the current `multi` candidate and compares it to `samewith`, which allows self-recursion to the entire proto.
> Note that &?ROUTINE refers to current multi

- doc/Language/operators.pod6
The choice of Set operator characters was awkward to me until @lizmat explained them to me on IRC.
This is the beginning of a try to add explanations to (all of?) them to clarify why they where chosen to make it easier to remember them.
> add Set operator character explanations

- doc/Language/objects.pod6
Part of the spec in Roast [S12-class/attributes.t](https://github.com/Raku/roast/blob/master/S12-class/attributes.t#L23-L33).
> Document attribute aliases

- doc/Language/variables.pod6
This PR describes the use of non-`$` sigils (that is, `@`, `%`, and `&`) with the `^` and `:` twigils.  It also adds `@^`, `%^`, `&^`, `@:`, `%:`, and `&:` to the index.
Closes #3953
> Describe use of non-$ sigils with ^ and : twigils

- doc/Language/quoting.pod6
The docs previously stated that you can start multiple heredocs on a single line, but neither said what effect that had nor showed the output in the accompanying example.
This PR adds both an explanation and example output.
> Add output to "multiple heredoc" example

- doc/Language/functions.pod6
- doc/Type/Any.pod6
- doc/Type/Channel.pod6
- doc/Type/Failure.pod6
- doc/Type/List.pod6
- doc/Type/Map.pod6
- doc/Type/PositionalBindFailover.pod6
- doc/Type/QuantHash.pod6
- doc/Type/Range.pod6
- doc/Type/Supply.pod6
- doc/Type/Uni.pod6
The documentation of the `list` subroutine is a good place to explain the
single argument rule yet again.
Most core types implementing a `list` method only accept an object instance
as the invocant. If the core type implements `list` as a multi method,
listing the type object is handled by
multi method list(Any:U: --> List)
> Improve documentation of the list routine

- doc/Type/independent-routines.pod6
In Raku parlance, a container generally refers to a scalar container. 
Arrays and hashes are mutable _collections_ that store values in scalar 
containers. To avoid confusion it's better to refer to these composite
types as  collections.
> Talk about collections rather than containers

- doc/Type/List.pod6
This is another false link that probably needs removing.
There is no `routine_Str`or `method_Str` documented in `Any`. I could not find a single reference to `.Str` that I could replace the reference with.
Removing the link does not seem to me to be important, but it probably should be an issue that `Str` is not documented in a single place. Strings and stringification are important enough to need a separate document.
> Remove link from List #3841

- doc/Language/101-basics.pod6
The previous paragraph points out that matches is the primary sort criterion.
This line takes advantage of stable sort by sorting by the _secondary_ criterion (sets) _first_ and then sorts by the _primary_ (matches).
> 101-basics: correct secondary/primary designation

- doc/Language/5to6-nutshell.pod6
I was converting Perl 5 code to Raku and didn't know what the equivalent of `$#array` was, to find the max element of the array. I looked in the Perl-to-Raku guides, but couldn't find the string `$#` in any of them.
The `.end` method appears to be what I was looking for. That was hard to find. Add a mention in the Perl-to-Raku overview, so others can find it.
I'm not completely sure this is definitely the best place to put it, but it's with other array-index things, and having it somewhere is better than not having it at all.
> Add $#array equivalent

- doc/Language/objects.pod6
The doc says that  an object delegates all methods to one delegatee.
The quoting of delegator /delegatee/delegation is inconsistent.
I have simplified the language for finding 'current' and 'original' unhelpful.
> Fix error re: delegation and simplify some text.

- doc/Language/5to6-perlfunc.pod6
In Perl, split without a pattern is different from split "" — telling users of the former to switch to the latter changes from splitting by words to splitting by characters.
Suggest using words instead, which is probably the most useful Raku alternative, while also mentioning the correct explicit pattern.
> Correct equivalent for split without a pattern

- doc/Type/List.pod6
This removes the `&eager` Sub, which does not seem to exist.
(There's an `.eager` method and an `eager` statement prefix, but no Sub)
> Remove &eager sub form

- doc/Language/operators.pod6
The sequence `'aa'…'cc'` does not use a `*.succ` default generator  (and this is correct [per Roast](https://github.com/Raku/roast/blob/master/S03-sequence/nonnumeric.t#L58)).
See also [Can Raku range operator on strings mimic Perl's behaviour?](https://stackoverflow.com/questions/70239228/can-raku-range-operator-on-strings-mimic-perls-behaviour/70239585) and the links cited in the answers.
> Document sequences like 'aa'…'cc'

- doc/Type/Test.pod6
`Mu.isa` explicitly does *not* match roles, so it seems worth calling out that `&isa-ok` behaves differently.
> State that isa-ok matches Roles

- doc/Language/nativecall.pod6
1. The description of versioned shared libraries mixes libfoo and libxxx -- most likely this was a typo.
2. The last sentence before the second code example seems to be missing a word.
3. Usually we add a space after the comma in parameter lists. 
1. Unify on ```libfoo```. That's what we have in the section "ABI/API version" as well.
2. and 3. are fixed in the obvious way.
> Minor cleanup for section "Getting started"

- doc/Language/performance.pod6
The example query would produce results with a few rows with high `inclusive_time` and then lots of small `inclusive_time`, each of which appeared to only happen once.
Use the foreign key when joining, rather than joining two tables by their own primary keys.
> Fix foreign key reference in profile SQL query

- xt/01-raku-version.t
Avoid issues where an older version might fail an example/signature test.
> add test for version of raku

- doc/Type/Signature.pod6
In a code example to demonstrate slurping, a signature object get assigned to the nameless state variable. This assignment does not appear to be needed and may add confusion for readers.
The code example removes the assignment.
> remove unneeded assignment to nameless state variable

- doc/Language/5to6-perlop.pod6
Being slightly competent with Perl, I took the fat arrow description in 5to6-perlop as a disincentive to read about Pairs.  That was an efficient choice except for my later ignorance of adverbially constructed pair syntax.
Here, I have added a link to the type Pair and to the glossary entry for adverbial pair.
> Mention adverbial pair in 5to6

- doc/Language/objects.pod6
This PR explains that you can pass a `HyperWhatever` to the `handles` method and describes how that's different from passing a `Whatever` (specifically, the `HyperWhatever` delegates method calls that will end up in the attribute's `FALLBACK` method; the `Whatever` only delegates if the attribute `.^can` do a method of that name).
> Document `handles(**)`

- doc/Language/quoting.pod6
- doc/Language/syntax.pod6
This expands the description of interpolation with qq, especially with regards to backslash escape sequences, which it now lists in a table.  It also separates the discussion of variable, closure, and backslash-escape interpolation and emphasizes the connection to the equivalent quoting adverb(s). 
Finally, this also fixes a link on the syntax page that incorrectly implied that backslash escape sequences work in `q` rather than `qq`.
> Expand qq docs re esc sequences

- doc/Language/functions.pod6
- doc/Language/operators.pod6
This PR clarifies the operator precedence table (as discussed in #4029) and clarifies/expands the accompanying discussion of operator precedence and associativity.
This PR makes the following changes:
* In the operators table, replaced the column that contained L, R, N, C, and X with a column listing associativites of 'left', 'right',
'non', 'chain', and 'list'.  These single-letter abbreviations were  used in S03, but are not currently used in elsewhere in  Raku/Rakudo/the docs other than in a table in `language/functions`.
* Made corresponding changes to the `language/functions` table.
* Split the discussion of precedence and associativity into separate subsections for clarity.
* Marked precedence levels that do not currently have any operator subroutines (these mostly do have …
> Clarify operator precedence description and table

- doc/Language/typesystem.pod6
- doc/Type/Method.pod6
This PR adds a note to the `is hidden` docs to explain that methods in a class declared with `is hidden` don't get the `*%_` parameter and explain why. See [this recent Stack Overflow answer](https://stackoverflow.com/a/71088429/) and the design docs [A12](https://raku.org/archive/doc/design/apo/A12.html#Interface%20Consistency) and [S12](https://design.raku.org/S12.html#Interface_Consistency).
> Methods in a class that `is hidden` don't get *%_

- doc/Language/grammar_tutorial.pod6
Fix grammar tutorial still referring to 'Perl' instead of 'Raku'.
> Replace "Perl Grammar Guide" with "Raku Grammar Guide"

- doc/Language/containers.pod6
This PR removes some text describing binding semantics that, after discussion, turned out to be the result of a bug rather than
intended behavior (the intended behavior is still under-documented, see Raku/doc#3961).  It also removes the accompanying test, which
failed to compile once the bug was fixed.
Finally, it adds a doc-comment clarifying that a nearby test fails at runtime even though it *looks* like it would throw a compile-time
error (and thus would need to be marked for xt/example-compilation to skip).
Resolves #4020
> Remove incorrect text & non-compiling example

- doc/Language/regexes.pod6
As we correctly note [further down the page](https://docs.raku.org/language/regexes#Predefined_character_classes), `\d` matches _decimal digits_ (Unicode `Nd`) not all numbers (Unicode `N`).  This PR fixes the description here, adds an example of where that makes a difference, and provides a way to match against Numbers if that's what the user meant.
> \d is for decimal

- doc/Language/modules.pod6
The actual path where bin/ scripts are installed to is not mentioned.
Mention where scripts are typically installed. Also drop the mention of Rakubrew which I think feels a bit out of place here.
> Give the more obvious answer to "Where are bin/ scipts installed?"

- doc/Language/nativecall.pod6
MacOS has some annoying behavior when dynamically loading C libs. Document those.
See https://github.com/Raku/App-Rakubrew/issues/9 for the very long story.
> Document MacOS quirk wrt DYLD_LIBRARY_PATH and SIP

- doc/Language/modules.pod6
To use a module of the own distribution, it must be listed
in the `provides` section, not the `depends` section.
> Correct META6.json `provides` snippet

- doc/Type/X/Cannot/Empty.pod6
- doc/Type/independent-routines.pod6
- type-graph.txt
Documenting `X::Cannot::Empty` allows the ecosystem to reuse the class, rather than copy it.
> Document X::Cannot::Empty

- cpanfile
\>= 2.12 requires Mojolicious 9.0.
> Set max AssetPack version in cpanfile

- assets/js/main.js
Table header names changed in https://github.com/Raku/doc/pull/4031. Closes https://github.com/Raku/doc/issues/4085.
> Fix precedence table ordering

- doc/Language/regexes.pod6
`Language/regexes` omitted the `:x` adverb, so this patch is just to add that.
> Including :x adverb

- doc/Type/Scalar.pod6
In Type/Scalar.pod6,
- Add a link to anonymous scalar,
- Delete a `my` from example,
- Refer to `$` as 'anonymous scalar variable`
> add link; lose my; change phrasing

- doc/Language/quoting.pod6
- doc/Language/traps.pod6
It is not clear from `qqx` examples that it can be used to execute arbitrary code if the user did not take the necessary precautions to prevent such issue.
Add example in traps page to show how the content of a variable used by `qqx` can be used to execute malicious code, also warned the user about it in quoting page. so that the user is aware of such cases before deciding to use `qqx`
Note: please let me know about any grammar/punctuation corrections.
> Make user aware of the risk of using qqx

- doc/Language/classtut.pod6
This is a reworked version of https://github.com/Raku/doc/pull/3794. The changes are largely the same, for the largest part only pulled apart into many separate commits.
With the advent of `is built` all the common use-cases of object
construction are now covered by our attribute syntax. This means that the
need to fall back to using `BUILD` has lessened enormously. Given that
`BUILD` has a number of behaviours that are non-obvious and require
knowing and understanding them, it makes sense to consider `BUILD` the
last resort mechanism to use when all else fails and recommend using
automatic attribute initialization and `TWEAK` for everything else.
Communicating this clearly in our object tutorial is very valuable, it
shows newcomers the sane default first. We do not want to send them off …
> Largely rework the Object Tutorial 2nd try

- doc/Language/glossary.pod6
- xt/pws/words.pws
Relates to https://github.com/Raku/doc/issues/711.
These were the only mentions to IRC bots I found. It seems that their entries had been removed earlier. Now the description links to the irc page on raku.org.
> Remove bot examples

- doc/Type/Pair.pod6
Closes https://github.com/Raku/doc/issues/4147.
The description of the Pair ~~ Pair case has been updated to match the specification and contemporary Rakudo.
> Pair.ACCEPTS documentation fix

- doc/Type/Metamodel/Primitives.pod6
- xt/pws/words.pws
The parameterization cache is *very* handy in MOP-heavy code, but is rather unintuitive and undocumented.
Document the `set_parameterizer`, `parameterize_type`, `type_parameters`, and `type_parameter_at` methods of `Metamodel::Primitives`.
Adds "parameterizer" and "noop" as words.
> Document Metamodel::Primitives' parameterization cache API

- doc/Language/classtut.pod6
Two instances of the phrase "act similar" are not grammatically correct.
Change to read "act similarly" in each instance.
> correct grammar

- doc/Language/control.pod6
- doc/Language/statement-prefixes.pod6
Put SPoT for `quietly` into `language/statement_prefixes` following from  #4117.
> Consolidate quietly into statement-prefix.pod6 from control.pod6.

- doc/Language/control.pod6
- doc/Language/statement-prefixes.pod6
Part of the 'Consolidate' series of PRs which is about removing duplication between statement-prefixes.pod6 and control.pod6.  The first in the series is PR #4151.
> Consolidate once from statement-prefixes.pod6 into control.pod6.

- doc/Language/control.pod6
- doc/Language/statement-prefixes.pod6
Part of the 'Consolidate' series of PRs which is about removing duplication between statement-prefixes.pod6 and control.pod6.  The first in the series is PR #4151.
> Consolidate start from statement-prefixes.pod6 into control.pod6.

- doc/Language/control.pod6
- doc/Language/statement-prefixes.pod6
Part of the 'Consolidate' series of PRs which is about removing duplication between statement-prefixes.pod6 and control.pod6. The first in the series is PR #4151.
> Consolidate supply from statement-prefixes.pod6 to control.pod6.

- doc/Language/control.pod6
- doc/Language/experimental.pod6
- doc/Language/faq.pod6
- doc/Language/modules.pod6
- doc/Type/Any.pod6
- doc/Type/Nil.pod6
- doc/Type/Signature.pod6
Some links are prefixed by https://docs.raku.org/, which is not needed. Also, one link is using wrong syntax for links.
Links are simplified, and correct syntax are used.
> Simplify links and fix syntax

- doc/Type/Test.pod6
Documentation is incorrect for throws-like.  If the eval code throws an exception, a string containing the name of that exception will not match.  Example:
```
raku -MTest -e "throws-like 'Exception.new.throw', 'Exception'"
```
This outputs:
```
1..2
ok 1 - 'Exception.new.throw' died
not ok 2 - right exception type (Str)
Stub code executed
in block  at /home/jmaslak/.rakubrew/versions/moar-2022.12/install/share/perl6/core/sources/60CBD62BA814F88B5840C355CCC73B21A03D70B9 (Test) line 658
in any  at /home/jmaslak/.rakubrew/versions/moar-2022.12/install/share/perl6/core/sources/60CBD62BA814F88B5840C355CCC73B21A03D70B9 (Test) line 642
in block <unit> at EVAL_0 line 1
in block  at /home/jmaslak/.rakubrew/versions/moar-2022.12/install/share/perl6/core/sources/60CBD62BA814F88B5840C355CCC73B21A03D7 …
```
> throws-like does not work correctly a string for the exception name

- doc/Language/variables.pod6
As @niner pointed out, the docs had the "what is an alias of what" backwards.
This change brings the description closer to S04-control, which also seems more factual for this matter.
> Making "our declaration" more accurately described

- doc/Type/independent-routines.pod6
This page should appear in the language page of the website, but is missed because the category metadata is 'basic' not 'fundamental'
This page does not appear in the language index page.
Change metadata 'basic' to 'fundamental'
> Change metadata from unknown basic to fundamental

- doc/Language/unicode.pod6
It's kind-of dependent on the VM it's running on. Moar is up to Version 15.0 at least.
Interesting enough, the repository said 13.1, the [live site ](https://docs.raku.org/language/unicode) says 12.1. I would suspect that unicode.pod6 hasn't been regenned for a while.
> Change supported Unicode version

- doc/Language/101-basics.pod6
This addresses issue #119 in doc-website, was in Raku/doc Either all references to Raku should have tm or none. My preference is for none as it is obvious
> remove TM char for consistency

- doc/Language/js-nutshell.pod6
Relates to https://github.com/rakudo/rakudo/issues/5221
This example got attention because of a related regression, however it was a severely problematic example:
- the implementation was incorrect
- hence the described output wasn't matched
- `||=` exists natively anyway so this example didn't illustrate what it claimed to
Here is a proposed alternative that does illustrate the point and the output is also correct.
> Rewrite the "make your own operator" example

- doc/Language/5to6-nutshell.pod6
- doc/Language/haskell-to-p6.pod6
- doc/Language/math.pod6
- doc/Language/objects.pod6
- doc/Language/operators.pod6
- doc/Language/py-nutshell.pod6
- doc/Language/regexes.pod6
- doc/Language/traps.pod6
- doc/Type/Any.pod6
- doc/Type/Attribute.pod6
- doc/Type/Bag.pod6
- doc/Type/BagHash.pod6
- doc/Type/Date.pod6
- doc/Type/Dateish.pod6
- doc/Type/Hash.pod6
- doc/Type/Mix.pod6
- doc/Type/MixHash.pod6
- doc/Type/Mu.pod6
- doc/Type/Set.pod6
- doc/Type/SetHash.pod6
- doc/Type/Signature.pod6
Also try to ensure consistent casing of `OUTPUT:` and add missing `␤`s.
> Prefer OUTPUT: «…» in examples

- META6.json
- util/create-brackets-table.raku
The following changes have been made:
+ removed hard-wired file paths
+ ensured the output table has no trailing spaces
+ eliminated the 'Reorder' and 'original' options
+ eliminated the embedded array
+ removed unneeded code
Possible changes to be made in this or another PR:
+ modify the behavior for a failed download of the source HLL::Grammar.nqp
+ change the output table name
+ change the pod6 file name
> Ensure the 'Brackets' table generator always uses the data source file

- xt/link-checker.rakutest
This is useful for links to the `/language` index, for example.
> link-checker: Check for the existence of directories as well as pod6 files

- doc/Type/Distribution/Resource.pod6
Reverts two lines changed in 4118f0c: the directory name has yet to be changed from `perl6` to `raku`.
> Partially revert changes to `Distribution::Resource`

- doc/Type/Any.pod6
`use v6.e.PREVIEW` for `snip` and `snitch` examples.
> Declare `v6.e.PREVIEW` in the preamble for examples that require 6.e

- doc/Language/regexes.rakudoc
- xt/rakudoc-c.rakutest
`Z<ignore-code-ws>` indicates that the following whitespace check ought to be skipped.
A couple of these `Z<>`s have been added to `doc/Language/regexes.rakudoc`. 
Relates to #4251.
> xt/rakudoc-c.rakutest: respect `Z<ignore-code-ws>`

- doc/Language/101-basics.rakudoc
- doc/Language/5to6-nutshell.rakudoc
- doc/Language/5to6-perlvar.rakudoc
- doc/Language/js-nutshell.rakudoc
- doc/Language/modules.rakudoc
- doc/Language/quoting.rakudoc
- doc/Language/regexes.rakudoc
- doc/Type/CX/Done.rakudoc
- doc/Type/CX/Emit.rakudoc
- doc/Type/CX/Last.rakudoc
- doc/Type/CX/Next.rakudoc
- doc/Type/CX/Proceed.rakudoc
- doc/Type/CX/Redo.rakudoc
- doc/Type/CX/Return.rakudoc
- doc/Type/CX/Succeed.rakudoc
- doc/Type/CX/Take.rakudoc
- doc/Type/CX/Warn.rakudoc
- doc/Type/Thread.rakudoc
- doc/Type/X/Method/InvalidQualifier.rakudoc
- xt/rakudoc-brackets.rakutest
Authors occasionally writing `<foo>` instead of, e.g.: `C<foo>`
xt/rakudoc-brackets.rakutest
> Add test for <> (missing formatcode)

- doc/Language/functions.rakudoc
- doc/Language/modules.rakudoc
- doc/Language/operators.rakudoc
- doc/Language/pragmas.rakudoc
- doc/Language/quoting.rakudoc
- doc/Language/regexes.rakudoc
- doc/Language/signatures.rakudoc
- doc/Language/unicode_entry.rakudoc
- doc/Type/IO/Handle.rakudoc
- doc/Type/Routine.rakudoc
- doc/Type/Variable.rakudoc
These don't currently render correctly on the [doc website](https://docs.raku.org), and in some cases make example source more difficult to read and maintain.  Output presentation has also been tidied.
Rendering of examples has been discussed in a few places recently,
- https://github.com/Raku/doc/discussions/4216
- https://github.com/Raku/doc-website/issues/124
- https://github.com/Raku/doc/issues/4250
While these changes doesn't resolve the overarching issue, they do improve the readability (and usability) of public facing documentation in the interim.
(If in future formatting codes are permitted in examples by the renderer, we could consider reverting this commit.)
> Remove formatting codes from various examples

- .gitignore
- util/test-website.raku
templates in doc-website exist but are not verified to pass raku/doc's basic pod structure.
util/test-website
> Add utility to test doc-website templates

- writing-docs/README.md
The following links in this page are not become links. 
* [CREATING-NEW-DOCS.md]
* [EXAMPLES.md]
* [INDEXING.md]
* [STYLEGUIDE.md]
Also, the following link in this page is broken.
* [the CONTRIBUTING document]
We can set correct links in above links by this modification.
> Fix broken links

- doc/Language/modules.rakudoc
- xt/pws/code.pws
The how to section for distributing your module could also mention that dist management tools can also make the boilerplate faster
Added `fez` to the list of ways you can initialize a skeleton dist repo
> mention dist tools

- README.md
For issue #4244 
The bullet point entry for READMEs in other languages is too long.
I reformatted the list as a one liner separated by | (idea stolen from coke)
> Reduce size of entry for READMEs in other languages

- doc/Type/Cool.rakudoc
The sentence is missing a 'the'.
> Add missing word

- doc/Language/quoting.rakudoc
It's not obvious that interpolating word quotes break on any interpolation, even without a space.
I added this remark and the analoguous remark for "sub-strings" in general. Also, I thought an example of being able to interpolate within qww "sub-strings" can give the reader a bit of sanity boost.
> Describe additional word splitters for quote protection

- doc/Language/js-nutshell.rakudoc
Missing section about buffers on the NodeJs - Raku migration guide.
Add a section about buffers  on the NodeJs - Raku migration guide.
> Add Buffers section to the JS/NodeJS to Raku migration guide

- doc/Type/Int.rakudoc
I think angle brackets are `<>`; this text is referring to `[]`.
> Name the right type of bracket in :100[99, 2, 3]

- doc/Language/structures.rakudoc
The sentence is explaining the difference between `deepmap` and `duckmap` as it continues to exemplify `duckmap`, but it was erroneously typed `deepmap`.
> Fix typo in structures documentation

- doc/Type/Mu.rakudoc
Remove the `multi method new($, *@)` candidate from the docs. It throws an error when used, and going by the description of `Mu.new` it wasn't meant to be documented.
See #4188.
Remove `multi method new($, *@)` from the docs.
> Remove multi new candidate

- doc/Language/unicode.rakudoc
- doc/Type/Cool.rakudoc
- doc/Type/Str.rakudoc
The routines uniname(s) & uniparse should refer to each other. See #4299.
The routines uniname(s) & uniparse now reference each other when they're defined. Also surround some types with `C<>`.
> Cross reference uniname(s) and uniparse routines

- doc/Language/subscripts.rakudoc
If you're linking within the same page, the `#` will show up in the display text unless you provide a label. This looks out of place in comparison to other links. It also might confuse readers into thinking `#:delete` is the adverb instead of `:delete` for example.
Also change `Can...` to `It can...`.
Provide a label to links pointing somewhere within the same page in order to remove the `#`s from the display text.
> Label links to remove #s from display text in subscripts page

- doc/Language/operators.rakudoc
When quickly looking at a specific example for ff() (or related functions), the examples
provided don't show the core functionality of the function – namely that the function ignores
elements until the first match, and after the second match.
Add an element in the example array before and after the objects matched, so the
main functionality of the functions is show, in addition to the nuance offered by the
specific variation.
> Improve examples in ff() and related docs

- CONTRIBUTING.md
- doc/Language/regexes.rakudoc
- doc/Language/unicode.rakudoc
- doc/Language/unicode_ascii.rakudoc
+ Grammar tweaks
+ Add more examples
+ Align examples of Unicode naming corrections for clarity
- Use comments to distinguish correct versus incorrect naming versions
> Add a reference to Whitespace

- doc/Language/operators.rakudoc
Addressing https://github.com/Raku/doc/issues/4073
Moreover removing fake "operators" that are mere
functions from the list.
> Polish the "list prefix" entry

- util/dumpast.raku
- xt/links-not-links.rakutest
Updates the links test to use the new RakuAST API instead of the old parser.
Allows URLS in the same positions as the original test.
add utility to dump AST of doc files.
> Rakuast links

- doc/Language/subscripts.rakudoc
The link generated for :kv near https://docs.raku.org/language/subscripts#:k:~:text=in%20which%20case%20the%20return%20value%20will%20be%20determined%20by%20those%20adverbs is malformed.
The pipe character appears to have been omitted. It is now provided.
> fix typo in link to :kv adverb

- doc/Language/regexes.rakudoc
Does this read better ?
~~~diff
-$/.Int <= 255 && $/.Int >= 0
+0 <= $/.Int <= 255
~~~
> Using chained comparator

- doc/Type/DateTime.rakudoc
The numeric comparison operators were previously documented here because they were specifically implemented for this type.
However, this changed with https://github.com/rakudo/rakudo/commit/72856df91b2e1cafb439bcd8bcc7ae46c378d01e .
Now, the fact that this type can be used with these operators is simply a natural consequence of the provided coercion.
> Remove numeric comparison operators from DateTime

- doc/Language/regexes.rakudoc
The previous phrasing didn't make it clear whether the trailing separator is optional or mandatory.
https://design.raku.org/S05.html line 1118 clarifies that it is optional, which is in accordance with the current behavior.
I made it stand out a bit more by taking it into a separate paragraph.
> Making %% for regexes more noticeable and precise

- doc/Type/IO/Socket/Async.rakudoc
This adds documentation for for the `connect-path` and `listen-path` methods of `IO::Socket::Async`
This fixes #4355
> IO::Socket::Async: add documentation for connect-path and listen-path

- doc/Programs/02-reading-docs.rakudoc
The [programs/02-reading-docs](https://docs.raku.org/programs/02-reading-docs) page showed usage info for the old version of `rakudoc`; this PR updates the info to the current version.
> Update `rakudoc -h` output to match current rakudoc

- doc/Type/Bool.rakudoc
I found the existing prose description way too complicated to understand, and when rewriting it decided to separate the description and example that corresponds to one signature from the description and examples that corresponds to the other signature.
> Rewrite `pick` description of Bool.rakudoc

- doc/Type/IO/Path.rakudoc
Quoting the current version of https://docs.raku.org/routine/dir:
> Returns the contents of a directory as a lazy list of IO::Path objects representing relative paths, filtered by [smartmatching](https://docs.raku.org/language/operators#infix_~~) their names (as strings) against the `:test` parameter. The path of returned files will be absolute or relative depending on what `$path` is, and are returned in an arbitrary order.
The first sentence says there's a list of "objects representing relative paths". The second says it's "absolute or relative". That seems wrong. (Or am I misunderstanding something?)
The first sentence mentions "as strings" as a parenthetical but I think the fact the filtering is against strings ought be *emphasized* given the import of what's explained in the …
> Tweak description of `dir` in `IO::Path` doc

- doc/Type/Junction.rakudoc
The earlier example reassured the misconception that it's a good idea to use `contains` to check for elements in a list. I changed it to a more idiomatic use of `contains`.
> Change `contains` snippet to a non-trap

- doc/Language/regexes.rakudoc
This PR is an attempt to resolve #4370 by extending the language/regex#Backtracking section to include a explanations of the `:`, `:!`, and `:?` metacharecters.  This PR includes only new material; it's possible that some of the information from language/regexes#Preventing_backtracking:_: should be moved to this section (or deleted, see #4369), but this PR hasn't done so.
> Add backtracking control metacharecters :, :!, and :?

- doc/Language/regexes.rakudoc
This PR is my attempt to solve (most of) the issues discussed in #4356.  I've split the discussion of Raku's built-in regexes into two sections: one discussing the anchors/zero-width assertions and one discussing the two built-in tokens (`<ws>` and `<ident>`) – and calling them tokens.  I've also edited the table to show a "rexex equivalent" that uses the `:` backtracking control character.  Hopefully this will help clarify the ratcheting behavior of `<ws>`.
However, this PR does not document the fact that `<ws>` enables backtracking for the _previous_ atom.  That's largely because there's no consensus about whether that behavior is intentional (see raku/problem-solving#390; it seems likely that `<ws>`'s behavior is a bug).
> Clarify built-in regexes

- doc/Language/syntax.rakudoc
- xt/pws/words.pws
This PR replaces the "Subroutine declaration" section with a "Callable declarations" section, which now contains sub-sections on "Subroutine declaration", "Multiple dispatch subroutine declaration", "Block declaration", "Method declaration", and "Multiple-dispatch method declaration".  Similarly, it replaces the "Subroutine calls" section with an "Invoking code objects" section, which contains "Invoking subroutines or blocks", "Invoking methods", and "Method-like function calls & function-like method calls".
These sections document previously un- or under-documented syntax such as `method $invocant:` and `$obj.&subroutine`.
Closes #4380 and #4379
> Expand code declaration/invocation syntax

- doc/Language/regexes.rakudoc
We currently say that space after a quantifier becomes a `<.ws>` call with `:sigspace`.  However, that's not true if the quantifier is modified by `%` or `%%`; In that case, whitespace after the quantifier is ignored (which is logical, since `a+ <.ws>%` isn't valid).
> Clarify :sigspace behavior for % and %%

- doc/Type/IO/Socket/Async.rakudoc
Fix `connect-path` method name in example.
> Fix IO::Socket::Async::connect-path method name

- doc/Language/regexes.rakudoc
We mention the main quoting options, but left out a couple.  `｢…｣`  is particularly worth documenting, since it makes matching `\`s much easier.
> Add ｢…｣, ‘…’, and “…”  as Regex syntax

- doc/Type/List.rakudoc
This PR clarifies that `List.fmt` flattens the lists it operates on; e.g., `(<a b>, <c d>).fmt('[%s]')` produces `[a] [b] [c] [d]`.  See https://stackoverflow.com/a/69144246
(I really should have clarified the docs when this confused me two years ago, instead of waiting to run into the same confusion again!)
> Explain that List.fmt flattens

- doc/Language/classtut.rakudoc
2 Missing links 
- Link to Attributes is to the heading in same file, but missing a `#`
- Link text `L<has>` would reference a primary source file `has`, which does not exist. But there is a `/syntax/has` file
> Missing links classtut.rakudoc

- doc/Language/intro.rakudoc
Missing links reported 
- documentation suite has 'introduction' and 'reference' pages in place of 'language', so update the text to include them
- 'help' should point to the section on entering unicode
> missing links: Update intro.rakudoc

- doc/Language/numerics.rakudoc
- to handle case insensitive OS, documentation for 'int' is at `native/int` not `type/int`.
change type/int to native/int
> missing links: Update numerics.rakudoc

- doc/Language/operators.rakudoc
Link to `/routine/=` does not exist because separate `=` heading does not exist. The heading is `= (item assignment)`
Change '=' to '= (item assignment)'
> missing link - Update operators.rakudoc

- doc/Language/regexes.rakudoc
link url requires initial `/`. Several urls missing one.
add `/` to url, eg. `L<grammars|language/grammars>` to `L<grammars|/language/grammars>`
> missing links - Update regexes.rakudoc

- doc/Language/syntax.rakudoc
missing `/` in Link url
add `/` to url eg `L< `... `|language/functions`...`>` to `|/language/functions`
> missing links - Update syntax.rakudoc

- doc/Language/traits.rakudoc
link to `/syntax/is` should be `/routine/is`
change url
> missing links - Update traits.rakudoc

- doc/Language/traps.rakudoc
Too many spaces in url
remove spaces
> missing links - Update traps.rakudoc

- doc/Language/variables.rakudoc
Link to `/syntax/%?RESOURCES` in `/type/Distribution/Resource` fails because Composite not generated
Add X<> markup to Heading
> missing link - Update variables.rakudoc

- doc/Type/Hash.rakudoc
3 missing links all different
- `L<Mu>` needs to point at a source, provided /type/Mu
- `L<subroutine|/language/...>` should be type/independent...
- `is default` points to an incorrect Composite. Found the most probable one.
> missing links - Update Hash.rakudoc

- doc/Type/Perl.rakudoc
`L<Raku>` identified as missing link, but web server recognises bare url `/Raku` as `/type/Raku`
add url for robustness
> missing link - Update Perl.rakudoc

- doc/Language/operators.rakudoc
See #280 in Raku/doc-website.
- A search for `X<L<` in all documents, it only occurs once - here
- Having markup codes inside other markup codes, as here, should be valid, and it will be in the next iteration of the Renderer. But that might take some time. 
- Better in the short term to create a workaround
Remove the inner link, which is provided later in the same line anyway. No information lost.
> Remove `X<L<` form in Update operators.rakudoc

- doc/Language/haskell-to-p6.rakudoc
a simple example of partial application in raku.
Couldn't figure out what `method chaining` has to do with currying, so I just left it as it is.
> haskell partial application example in raku

- doc/Language/unicode.rakudoc
Firefox does not display some "rare" Unicode fonts
Document the work around for Firefox in unicode.rakudoc
> document Firefox Unicode config in unicode.rakudoc

- doc/Type/Lock.rakudoc
Changing '::' too '/' in URL of `L<>`
- Having '::' in the **URL part** of `L<...| link url >` markup is a hold-over from Perl5 behaviour.
- There are only two files in the Raku/docs/doc suite that contain `L<>` **URLs** with '::' instead of `/`.
- New RakuDoc v2 renderers will not automatically make this change.
> remove '::' from links Update Lock.rakudoc

- doc/Type/Lock/Async.rakudoc
- '::' in URL instead of '/' is Perl5 behaviour. 
- subst '/' for '::'
> subst '/' for '::' in URL of L<> Update Async.rakudoc

- doc/Language/typesystem.rakudoc
<.^.> reads like a typo.  I don't like my explicit parentheses as breaking the usual style of  links, but the link is unusual.
> Update typesystem.rakudoc "the ... metamethod .^."

- doc/Language/rb-nutshell.rakudoc
> rb-nutshell: clarify break -> last in Flow interruption statements

- doc/Type/Cool.rakudoc
Attempts to fix #4449 with a Wikipedia link. There is a more formal [link](https://www.unicode.org/versions/Unicode15.0.0/ch04.pdf) from the Unicode standard itself but i) the next sentence in the documentation refers to the Wikipedia page (a subsection therein) already and ii) formal link is harder to digest as it is a reference document and it's also a PDF.
> Fix broken link in `uniprop`

- doc/Language/glossary.rakudoc
- doc/Language/subscripts.rakudoc
- doc/Type/Code.rakudoc
- doc/Type/HyperWhatever.rakudoc
- doc/Type/Whatever.rakudoc
- doc/Type/WhateverCode.rakudoc
The documentation currently uses the term "currying" to refer to what is more broadly known as "partial function application" (but frequently incorrectly called "currying").  However, Raku generally doesn't use the phrase "partial function application", probably because it's a real mouthful and could be off-putting to people not familiar with functional programming jargon.  Instead, Raku prefers the term "priming", see
[S06](https://design.raku.org/S06.html#Priming).
Accordingly, this PR changes (nearly) all uses of "currying" or related words to the "priming" equivalent; it also adds a "priming" entry to the glossary.
The only two (intentional) uses of "currying" left are in a TODO section of the Haskell-to-Raku guide and in the documentation for the (Rakudo-specific, unspecified) type …
> Replace incorrect use of "currying" with "priming"

- doc/Type/Bool.rakudoc
- xt/rakudoc-types.rakutest
Inconsistent formatting when referring to types in the docs that have their own primary page. (#2954)
```xt/rakudoc-types.rakutest```
> Type links

- doc/Language/regexes.rakudoc
The docs currently refer to `<|w>` as a synonym for `<?wb>`, but this doesn't seem to be valid syntax – it's not spec'd in Roast, it isn't documented elsewhere, and it doesn't work in Raku AST. So this commit removes it from here.
See https://stackoverflow.com/q/78069120 for details.
> Remove invalid <|w> syntax

- doc/Language/create-cli.rakudoc
There's a segment in the doc which has two consecutive `=item` lists. It's clear to me the second list is supposed to correspond to the first list, with three items in the second list to match the three items in the first list. But the second list was just two items.
This PR just fixes what I consider just a clear mistake with a minimalist fix by making the second list be a three item list corresponding to the three items in the first list.
----
It seems to me a better fix would be to turn the two lists into a single list of three items, or, better yet, a table. But rather than write that (more complicated) PR I've decided to wait for responses to this simpler PR.
> Address formatto in create-cli.rakudoc

- doc/Language/signatures.rakudoc
Sadly the table in my last commit - when rendered did not produce desired output. My POD6 skills are low, afaict it is not possible to embed markup in table cells. So I have rewritten accordingly and tested locally.
Feel free to edit if you can improve.
https://github.com/Raku/doc/issues/4493
> Avoid pod6 markup in table cells

- doc/Language/ipc.rakudoc
- xt/an-grammar.rakutest
- xt/pws/words.pws
`proc` (run/shell) is covered in a few places, but the way arbitrary data is piped into spawned process is very cryptic.
An example is provided that illustrates how to employ a terminal utility that is useful for web page design.
> Update ipc.rakudoc Demonstrating how to pipe data into a process using `:in`

- doc/Language/ipc.rakudoc
Although the example using shell works correctly, applying the 
comments about how to extend for repeated strings does not in fact work
Minimal change is to revise the comments. 
The following program, which has a loop, does work. Not sure about whether to include this in the example.
```
use v6.d;
#| process with utility, first check it exists
my $proc = shell( <<sass --version>>, :out, :merge);
exit note 'Cannot run sass' unless $proc.out.slurp(:close) ~~ / \d \. \d+ /;
my @scss = q:to/SCSS/ , q:to/SCC2/;
div.rendered-formula {
display: flex;
justify-content: space-around;
align-items: center;
img.logo {
align-self: center;
}
}
SCSS
.new { color: red }
SCC2
for @scss {
#| set up the process for stdin
$proc = shell( <<sass --stdin --style=compressed>>, :in, :err, :out ); …
```
> Update ipc.rakudoc revise example

- doc/Language/variables.rakudoc
Bad example: 
isa-ok $resources, Hash;
Correct error by showing the correct class name:
isa-ok $resources, Distribution::Resources;
> Fix for issue 4518, bad example

- doc/Language/regexes.rakudoc
PR corresponding to half of what I meant by "Open a new doc issue?" in Rakudo issue [Lining up `|` in a regex doesn't work as expected when using adverbs](https://github.com/rakudo/rakudo/issues/4147).
Quoting @zerodogg from the Rakudo issue:
> The [documentation for raku](https://docs.raku.org/language/regexes#Quoted_lists_are_LTM_matches) on regexes and `|` matches states that "If the first branch is an empty string, it is ignored.". This doesn't appear to be working when using an adverb like `:i`
This is true, so I've opened a new Rakudo issue narrowly focused on the hope that that can be fixed as part of the RakuAST work and doesn't warrant altering the doc.
That said, @jnthn went on to say:
> One could maybe argue that `|` should imply adverb scoping ... Perhaps a docs issue would be …
> Explicitly say alternations/conjunctions don't scope adverbs

- doc/Language/faq.rakudoc
Larry deliberately used the name "Junctions", not "Superpositions" because he felt officially leaning on the quantum analogy was a mistake.
I think the use of the word "eigenstate" is appropriate in its one use on the Junctions page but not in its uses in this FAQ question.
> Remove allusions to "eigenstate".

- doc/Language/nativecall.rakudoc
Doc' that NativeCall's `returns` trait's default is `Mu:U`.
Emphasize `void`-is-only-for-pointers with its own paragraph.
Ref #5293
> NativeCall void function returns Mu type object

- xt/headings.rakutest
While `<|w>` works in Rakudo, it isn't official Raku, and while I personally like it, there's a chance it will go away. Its semantics are the same as `<?wb>`, which _is_ official Raku, so I've switched to that. (See also https://github.com/Raku/doc/commit/5c1a147e68e800a35baea3505f4cdc14fee63efa.)
I meant my prior related commit (which changed the regex doc page) to be a PR because I wasn't 100% sure about the `X<...>` stuff and regardless of that I felt it could still do with a quick check by someone else. But I clicked the wrong button. Otoh, once I'd done that I thought it would almost certainly work and be wanted, and if it didn't it wouldn't be a big deal and would be easy for me to spot it even if no one else does, and to fix it.
But for _this_ change I'm making sure I do it as a …
> Finish s/`<|w>`/`<?wb>`/ in doc (headings.rakutest)

- doc/Language/control.rakudoc
See StackOverflow Q&A at https://stackoverflow.com/q/68744854
> Clarify when `do` runs a block

- doc/Language/pod.rakudoc
References to Pod6 in this document are outdated since the new name is Rakudoc
Replaced all occurences of `Pod6` with `Rakudoc`
> Replace Pod6 with Rakudoc

- doc/Language/containers.rakudoc
The text claimed that BIND-KEY is used to bind to an array element, but it is actually BIND-POS. Add a new sentence that still mentions BIND-KEY and what it is actually used for, since it's closely related.
> fix reference to BIND-* methods

- doc/Language/pod.rakudoc
The `--man` code example provided in the Rendering Pod to Text section has some issues:
* It will only render Pod in the file being executed by Raku. This is
problematic if you intend to distribute the program via Zef, as `$*PROGRAM` will
not point to the original script but a wrapper without the Pod instead.
* Performance issues from invoking Raku.
* Print the output of `pod2text $=pod` using `Pod::To::Text` directly. This way
we do not have to rely on `$*PROGRAM` pointing to our script file. It's also
faster than re-invoking Raku.
> Update --man code example in pod.rakudoc

- doc/Language/operators.rakudoc
Deprecated operators appeared with no explanation.  
Noted that they were deprecated, with a version.
> Documented deprecated operators, as discussed on #raku

- doc/Language/unicode.rakudoc
The current docs do not fully explain all the ways to enter Unicode
characters into a string.
I have expanded the examples to show Unicode entry by octal number.
I have alse added a section on using numerical codepoint entries
in a mixed string of normal text.
Additionally, I inserted level 2 headings to better separate the
several types of Unicode entry.
Note the docs search mechanism needs to be made more aware of entering Unicode characters in strings.
> Add examples of octal Unicode entry

- doc/Language/modules-core.rakudoc
- doc/Language/operators.rakudoc
- doc/Language/quoting.rakudoc
- doc/Language/syntax.rakudoc
- doc/Language/typesystem.rakudoc
- doc/Language/unicode_entry.rakudoc
- doc/Language/variables.rakudoc
- doc/Type/IO/Handle.rakudoc
- doc/Type/Sub.rakudoc
Zero-width index directives don't seem to work if they appear after a heading, so fix all occurrences by moving them before the heading.
The broken index directives also had the side-effect of causing blank headings in some situations, e.g.
- https://docs.raku.org/language/variables#Sigils
- https://docs.raku.org/language/operators#infix_%2E%2E%2E
> Fix missing index entries

- doc/Type/Proc/Async.rakudoc
Referring to issue #4324, the output of `class Proc::Async` is incorrect in the template sample.  
Adjust the output for [Proc::Async](https://docs.raku.org/type/Proc/Async).
> Fix incorrect Proc::Async output #4324

- doc/Language/operators.rakudoc
[The section that's affected.](https://docs.raku.org/language/operators#infix_.=)
Added a link to the postfix counterpart of infix `.=` and rephrased that sentence slightly; updated the error message generated by the second code example.
The overall code example is now slightly more verbose. I think this is justified because it's the first example in the section `Dotty infix precedence`.
> In `operators.rakudoc#infix_.=`, clarify usage of infix & postfix operator, and add link

- doc/Type/Metamodel/ConcreteRoleHOW.rakudoc
- doc/Type/Metamodel/CurriedRoleHOW.rakudoc
- doc/Type/Metamodel/ParametricRoleGroupHOW.rakudoc
- doc/Type/Metamodel/ParametricRoleHOW.rakudoc
The reference to the `metamodel` is ambiguous, as mentioned in #4201.  
Standardize and update the notes.
> standardizes the reference to the metamodel #4201

- doc/Language/5to6-perlop.rakudoc
Split the _Language/5to6-perlop/The_arrow_operator_ section into 3 paragraphs.
Changed the `fat arrow` redirect to the more local 5to6-perlop#Comma_operator.  And put it first.
Reduced the text of the central point into the second paragraph.  Making a change so the first sentence need not be corrected by the second.           
The third pargraph briefly states the `->`'s Raku purpose with links.
My "dereferencing is rare in Raku" seems justified in my slight experience and by JJ's tone.  If not so, advise.
> Split 5to6 section into 3 paragraphs

- doc/Language/control.rakudoc
- doc/Type/Supply.rakudoc
File `/type/Supply`: This topic was new to me when I read these docs. I struggled to understand the explanations on the page `/type/Supply` [(weblink)](https://docs.raku.org/language/concurrency#Supplies) right up until the point when I read the very good TV/Netflix analogy on `/language/concurrency`. Thus, here's a proposal to incorporate that analogy also in the dedicated page for Supplies.
File `/language/control`: Since strings have a `.chars` method rather than a `.char` method, that name looks more fitting to me here, unless I'm missing something.
> Use the TV/Netflix analogy on Supplies also on the dedicated page /type/Supply. (Plus one other small proposal)

- doc/Language/typesystem.rakudoc
[This is the section that's affected.](https://docs.raku.org/language/typesystem#Inheritance_and_multis)
I found it difficult to understand what is meant by the original phrase _"does not compete with"_. The replacement with _"there is no competition from"_ should be clearer and easier to parse.
In the code, change class names `A` and `B` to `Parent` and `Child`, and add comment that `int` is a subclass of `Int` (which is important to know in order to understand what goes on).
> In section `Inheritance_and_multis` of `typesystem.rakudoc`, clarify wording and code example

- doc/Language/signatures.rakudoc
[This is the section that's affected.](https://docs.raku.org/language/signatures#Was_an_argument_passed_for_a_parameter?)
Trying to use the trait "is optional" in a function signature throws error "Can't use unknown trait" (in all of v6.c, v6.d and v6.e.PREVIEW).
Perhaps some mention should be retained, though, if that trait was present in older versions.
> In signatures.rakudoc, remove mention of nonexistent trait `is optional`, and change `=:=` to `===`

- doc/Language/signatures.rakudoc
This is the first time the novel term "invocant marker" is used in this document, so let readers know that they'll find it explained immediately hereafter.
> In signatures.rakudoc, remark that "invocant marker" gets explained in the following section

- doc/Language/signatures.rakudoc
[Beginning of the affected parts.](https://docs.raku.org/language/signatures#Sub-signatures)
* **Move the section on `Long names` down**, so that the sections `Sub-signatures` and `Captures` come directly after another, since they are very closely related to one another.
* In section `Sub-signatures`, **change from using `|` to `\`**, since captures with `|` are already the topic of the `Captures` section thereafter, and because `\` gives behavior that's more like that of an actual "compound parameter", e.g. that other parameters can still come after them.
* Expand sections `Sub-signatures` and `Captions` by **more examples** showing that most of the signature syntax is available for sub-signatures, too.
* In section `Captures`, move the paragraph on **unbound captures** to the bottom to …
> In signatures.rakudoc, rearrange and modify the sections Sub-signatures, Captures, and Long names
