Raku/doc

lib/Language/variables.pod
Thought I'd add this to prevent further reinvention of the wheel
=> document $*USER

lib/Language/variables.pod
Noticed this was missing too while I was in the Process.pm
=> Document $*GROUP

lib/Language/regexes.pod
@moritz Oops, there were 4. You missed 2.
=> Remove more ? from ?! lookaround assertions

lib/Language/modules.pod
@moritz is this better? I think my intuition to use passive voice stems from my school days. It's pretty much what we were taught unfortunately :(.
=> Attempted to address passive vs active voice and added examples for need,use,import and require

lib/Language/control.pod, lib/Language/variables.pod
May want to change it to a =head2 heading, but for now have put it as a
=head3 under the =head2 for C<if>
=> Added docs for with/without

lib/Language/functions.pod
- Modified a pod command at line 351
- A typo at line 395
=> small changes

doc/Type/IO/Handle.pod, doc/Type/IO/Path.pod, doc/Type/IO/Socket/Async.pod, doc/Type/IO/Spec.pod, doc/Type/IO/Spec/Cygwin.pod, doc/Type/IO/Spec/QNX.pod, doc/Type/Routine.pod
And a second commit that fixes some typos.
=> Fix broken links in IO documentation.

doc/Language/faq.pod
Couple of grammar edits, plus replacing space with nonbreaking space in "Perl 6".
=> Minor edits

doc/Language/syntax.pod
I'm starting to add some things to Language/syntax. I'm doing a PR here because I'm at a pause point, though these are really just stubs for a lot of further work.
=> Add some further stubs for syntax sections

doc/Language/5to6-perlfunc.pod
=> Changed heading level of "Alphabetical Listing of Perl Functions" to an

doc/Language/classtut.pod
While I love memes as the next guy, I don't think they have a place in the standard documentation, specially now Christmas is arriving.
=> Replace lolcat by neutral title

CONTRIBUTING.md, STYLEGUIDE.md
I was looking for a way to close down #51, or at least lock in some value.
Maybe this should just all be folded into CONTRIBUTING.md?
=> Add initial styleguide

doc/Language/testing.pod
Test.pm's use-ok is not documented. Added.
If no reaction, I will merge this small PR.
=> Add use-ok

htmlify.p6
This fixes an issue described in #227, however `make html` still doesn't complete due to another issue which I've so far not been able to fix.
=> Fix type check failing (gh #227)

doc/Language/modules.pod
Fix META.info: author -> authors.
Link to Test::META
=> META.info: author -> authors

doc/Language/faq.pod
timotimo in IRC wanted some more text about put in the FAQ. Thoughts?
=> Some more documentation about put

doc/Language/variables.pod
Fix a minor typo, and improve the docs of placeholder variables to better represent intended usage and not advocate antipatterns
=> docs improvement

bin/p6doc
I wanted to preview some files, and this helped. I can update the usage if it is liked.
=> Also allow p6doc <filename>

htmlify.p6
The superfluous "" will be going away soon. Hopefully.
=> preparing for removal of extra ""

doc/Language/unicode_entry.pod
I also changed a few words in Emacs section. Hope that's OK.
=> Add another way of entering unicode characters in Emacs

doc/Type/Str.pod
Added trans method declarations and changed typo. Also added new-lines for readability in source.
=> Add method info to trans

doc/Language/operators.pod
=> Grammar-o on its

doc/Language/5to6-nutshell.pod
=> Fix tense due to pluralization

doc/Language/regexes.pod
The =head and =item markers may need some TLC.
=> Add documentation for s/// operator

doc/Language/operators.pod, doc/Language/setbagmix.pod
Some more index entries for operators, and trimming some whitespace
=> Index more operators

doc/Language/regexes.pod
=> s/than must/that must/

doc/Type/Supply.pod
Was displaying the link instead of linking the display.
=> link to Block

doc/Type/Any.pod
Looks like a copy/paste error.
=> Any and all.

doc/Language/5to6-nutshell.pod
Add some missing features and idioms.
=> Enhance the 5-to-6 documents.

doc/Type/Supply.pod
=> live method

doc/Type/Channel.pod
Thanks to jnthn for clarification.
=> Clarify behavior of Channel.Supply.

.gitignore, htmlify.p6
This pull request adds the 5to6-perlfunc functions to our cool and awesome search index.
=> Add 5to6-perlfunc functions to search index

doc/Type/Hash.pod
Hi
I added a missing semicolon in Hash page.
=> Add a missing semicolon

doc/Language/operators.pod
Update some verbiage, fix a few spelling errors, fix the examples, and
add some additional examples.
=> Add, fix and reword feed operator docs

doc/Type/Pair.pod
Hi
I added a missing single quote in the Pair description page.
=> Add a missing single quote

doc/Type/Cool.pod
My first attempt at doing a pull request through github
=> Fixed two typos

doc/Type/Cool.pod
ZoffixW++ for checking the commit
=> Added documentation for sech and asech to Cool.pod

doc/Language/unicode_texas.pod
I tested this in my local system--table should look better with clearly defined columns.
=> table clean up

doc/Language/faq.pod
=> Add an OpaquePointer section to the FAQ page

doc/Language/concurrency.pod, doc/Language/phasers.pod
And also the same basic functionality in .tap.
=> Adding docs for async LAST/QUIT phasers

bin/p6doc, htmlify.p6, lib/Pod/Convenience.pm6
One or two actual changes to code, but no operational changes.
=> Mostly whitespace/syntax cleanup

Build.pm, META.info, bin/p6doc
Discover all installed modules, not just those listed in the panda cache file. Also remove dependencies on panda/Shell::Command
=> Discover all installed modules + Less deps

doc/Type/IO/Path.pod
see http://irclog.perlgeek.de/perl6/2016-05-22#i_12525721
=> Clarify IO::Path.Str

doc/Type/IO.pod
=> Fix the example of the open method

doc/Type/Rational.pod
=> Fix a typo DenomT to DeT

doc/Language/contributors.pod
I have added my name to the list :)
=> Add a contributor

doc/Language/testing.pod
try to improves description of all three versions
=> document the third is-approx signature

doc/Type/Capture.pod
A formatting correction and a code example correction.
I'm new to Perl 6, Pods and git so let me know if I could do any of these things better.
=> Corrections in Capture doc

doc/Type/IO/Path.pod, doc/Type/IO/Special.pod
This requires Rakudo PR #773, which implements RT #125489
=> Add documentation for the new IO.mode method

doc/Language/5to6-perlfunc.pod, doc/Language/5to6-perlop.pod, doc/Language/5to6-perlsyn.pod, doc/Language/5to6-perlvar.pod, doc/Language/faq.pod, doc/Language/glossary.pod
Replacement of hard links by pod-style links.
=> Fixes for hard linking

doc/Language/glossary.pod, doc/Language/nativecall.pod, doc/Language/unicode_entry.pod, doc/Language/variables.pod, doc/Type/Callable.pod, doc/Type/Channel.pod, doc/Type/Hash.pod, doc/Type/IO/Socket/Async.pod, doc/Type/Mu.pod, doc/Type/Order.pod, doc/Type/Promise.pod, doc/Type/Signature.pod, doc/Type/Supplier.pod, doc/Type/Supply.pod, doc/Type/Whatever.pod, t/tabs.t, util/update-and-sync
=> Add (failing) tab test

doc/Language/variables.pod6
This was probably too much text to put into that cell anyway. Is this better?
=> Is this better? (note on $*SCHEDULER and threads)

doc/Language/5to6-perlfunc.pod6, doc/Type/CallFrame.pod6, doc/Type/Routine.pod6
Fixed up the 5-to-6 caller note and then added documentation for CallFrame and added docs for package on Routine as well since that was needed and related.
=> Add documentation for Callframe

assets/sass/style.scss, html/js/main.js
Reverts perl6/doc#767
Due to "by design" bug.
=> Revert "Css-based TOC animation"

doc/Language/pragmas.pod6
=> Add a page for pragmas

doc/Language/modules.pod6
Make documentation about constants more consistent.
=> Remove $ from constant

doc/Type/Hash.pod6
I've commented out the line of output of dd.
=> Add a missing sharp symbol

doc/Type/Signature.pod6
=> Add an index for ;;

doc/Type/Signature.pod6
=> Fix a ;; index again (use C<<;;>>)

predefined-search-items
=> Add ;; (long name) to the list of the predefined-search-items

doc/Type/Range.pod6
=> Added method sum() to Range pod

doc/Language/faq.pod6
=> Add some indexes for FAQ

doc/Language/classtut.pod6, doc/Language/control.pod6, doc/Language/functions.pod6, doc/Language/grammars.pod6, doc/Language/io.pod6, doc/Language/list.pod6, doc/Language/nativecall.pod6, doc/Language/performance.pod6, doc/Language/quoting.pod6, doc/Language/regexes.pod6, doc/Language/setbagmix.pod6, doc/Language/subscripts.pod6, doc/Type/Capture.pod6, doc/Type/Parameter.pod6, doc/Type/Scalar.pod6, doc/Type/X/AdHoc.pod6
See #888 
Is it important if code chunks also use – instead of --? I'll go back and change that if so.
=> Converted -- to –

doc/Language/glossary.pod6
=> Moved Thunk out of IRC lingo.

doc/Type/DateTime.pod6
Removed superfluous : from timestamp format string
=> Fixed timestamp format string

doc/Language/functions.pod6
=> Added documetation on function return types.

doc/Language/typesystem.pod6
=> Add indexes for both :ver and :auth

doc/Language/typesystem.pod6
=> Fix a typo

doc/Type/List.pod6
Add documentation for produce based on reduce (#926)
=> Issue #926 produce method is not documented

doc/Type/Proc.pod6
Also correct a few other tidbits.
=> Fix #913: Add documentation for shell and command

doc/Language/exceptions.pod6, doc/Language/objects.pod6
I believe these little changes could make the object documentation more clear.
I've also fixed what I believe is a miswritten header.
=> A few improvements

doc/Language/5to6-perlop.pod6, doc/Language/typesystem.pod6
Reading the page about the 5-to-6 operators I made a few corrections that hopefully make the page more clear.
=> A few enhancements on 5-to-6-operators

doc/Language/typesystem.pod6
From suggestion via https://github.com/perl6/doc/pull/961
=> Link to the classtut in the class explaination.

doc/Language/traps.pod6
This adds some explanation as to how the ^ twigil placeholder variables work and how some people can run into troubles with them.
=> Add ^ twigil to traps. Fixes #364

assets/sass/style.scss, html/images/External-link-04-bold-12x12.svg, template/footer.html
#822 
I added the credits per CC guidelines for attribution. I wanted it to be in the HTML, so I added the credits to a comment in the page footer, rather than the CREDITS file
=> Added external link SVG image.

doc/Type/Supply.pod6
=> Show how to go from signal numbers to Signal objects to use with the signal method

doc/Language/unicode_entry.pod6
Mention unicode quotes. See #332 for reference
=> Mention smartquotes

doc/Type/List.pod6
I've built the html docs (post-edit's to doc/Types/List.pod6) - looks ok
please take a look at new doc for List routine 'zip', and List sub 'roundrobin'
not sure what else to type here, or what files to attach, if any ...
=> Attempt to improve the documentation of routines zip, and roundrobin.

doc/Language/typesystem.pod6
Hi there! Thank you for this absolutely wonderful documentation - it is really incredible!
This is a very small patch that fixes some typos I found. Hope it helps :)
Cheers!
garu
=> small typo fixes

doc/Language/5to6-nutshell.pod6
At first I got the impression I DO HAVE to take care with ranges.
=> I believe this emphasis was wrong

doc/Language/operators.pod6
Fixes https://github.com/perl6/doc/issues/1021
=> Fix links to postcircumfix operators

doc/Language/syntax.pod6
Attempt to resolve Issue #1039
=> Examples and ref. to further explanation for Unicode in Perl 6 syntax

doc/Type/Signature.pod6
Review of grammar is welcome!
Attempt to fix https://github.com/perl6/doc/issues/1027
=> Attempt to explain ways to declare return type in signature

html/js/levenshtein.js, template/footer.html, template/search_template.js
=> Allow fuzzy searching

doc/Language/glossary.pod6
Some remainder of https://github.com/perl6/doc/issues/728-related work.
=> Cleanup of broken links on Glossary page(either removing or fixing)

doc/Language/nativecall.pod6
This example seems outdated to me.
=> Fix DBIish examples

doc/Type/Str.pod6
I wrote documentation for the method Str.match. Once merged, this completes issue #838
=> Wrote documentation for Str method match

doc/Type/Any.pod6, doc/Type/Mu.pod6
=> Use .perl instead of dd

doc/Type/Pair.pod6
Hello!  Thank you for all of the good work that is done to document Perl 6. :+1:
I'd like to help out with my first small patch; just wanting to correct some grammar. :smile_cat:
=> Small typos on page for Pair type

doc/Type/Cool.pod6
Info taken from https://github.com/rakudo/rakudo/commit/625d1c5116c3314dd5624d6dcbac676ce112fe6a
=> More info on allowing EVAL

doc/Language/operators.pod6, doc/Language/typesystem.pod6, doc/Type/Sub.pod6
Add an example of nodality affecting hyper-method operator.
=> Proofread updates by (Wenzel P. P. Peppmeyer)++

doc/Type/Cool.pod6, doc/Type/Date.pod6, doc/Type/DateTime.pod6, doc/Type/Hash.pod6, doc/Type/Int.pod6, doc/Type/Setty.pod6, doc/Type/Slip.pod6, doc/Type/Str.pod6, doc/Type/Sub.pod6, doc/Type/X/Proc/Unsuccessful.pod6
Here are mostly 'add semicolon'-like fixes.
=> Fix broken examples, a couple of signatures and one table

doc/Language/operators.pod6, doc/Language/pragmas.pod6, doc/Language/regexes.pod6, doc/Language/testing.pod6
Excuse the excessive commits. Tried to do some squashing but all I got was a mess.
=> some more edits/re-writes

doc/Language/glossary.pod6
it's not in the TODO list, but it simply wasn't there, so I said, why not...
=> Adds definition for Repository

doc/Language/grammar_tutorial.pod6
In preparation for future edits.
=> added line breaks to grammar_tutorial

CONTRIBUTING.md
I tried my best to provide an easy explanation about outcome of https://github.com/perl6/doc/issues/776.
Review is needed.
=> Contributing examples output style explanation

doc/Language/nativecall.pod6
=> Add a concrete example of CStruct initialization

doc/Language/pod.pod6
Add a tutorial for Perl 6 Pod under the "Language" section.
fix #713  
fix #669
=> Add Pod tutorial

doc/Language/pod.pod6, xt/code.pws, xt/examples-compilation.t, xt/words.pws
=> pod.pod6 pass xtest

doc/Language/py-nutshell.pod6
Hi All,
This PR adds a *Perl 6 from Python, in a nutshell* page.
It's almost certainly incomplete, but hopefully not incorrect, so I'm submitting this as a PR now, hoping that it can become more complete as time goes on.
Thanks to everyone who has already provided feedback on the commits in this branch.
Brian
=> Add "Perl 6 from Python -- Nutshell" page

doc/Language/about.pod6
* s/POD/Pod
* s/pygments/highlights
* Add link to https://docs.perl6.org/language/pod
=> about.pod6

doc/Type/Seq.pod6
Discussed here: <https://irclog.perlgeek.de/perl6/2017-03-20#i_14295300>
=> Caveat about volatile cache state in Seq

doc/Language/pod.pod6
I also put a little snippit showing how to add a --man option to dump Pod as a man page.
=> Add section on Pod rendering to Text

doc/Type/Callable.pod6
Borrowed content from brian d foy's Stack Overflow post http://stackoverflow.com/a/43669837/215487
=> Added multi-positional use of assuming

doc/Language/performance.pod6
I'll be doing some edits. Wanted to get the doc in better wrapped shape, before I started.
=> Rewrap lines

doc/Language/traps.pod6
http://writingexplained.org/then-vs-than-difference
=> fixed then/than grammar issue

doc/Type/Cool.pod6
=> Explicitly note coercion to string for .contains

doc/Type/IO.pod6
* on doc site
- https://docs.perl6.org/routine/slurp
- Since I don't know if this really 'fixing' it, I made this as a PR. Please suggests me changes to actually deal 
with this. Thanks.
best regards,
faraco.
=> possible fix on reformatting the slurp example

doc/Language/syntax.pod6
Trying to simplify the explanation to make it easier to understand.
=> Regarding separators in if/elsif/else blocks.

doc/Language/regexes.pod6
=> regexes.pod6 change predefined <|wb>, <ww> to <?wb>, <?ww>

doc/Type/IO/Handle.pod6
=> Specify rakudo release slurp introduction

doc/Type/List.pod6
Fixes https://github.com/perl6/doc/issues/1490
Is explanatory enough?
=> Document `with` of `squish`

doc/Language/objects.pod6
- Make discussion on class/instance methods into its own Section
- Add example code for `self` especially to illustrate its behavior with
different invocants
Thanks to @ronaldxs for further comments :+1:
References #1121 (hopefully fixes too :joy_cat:)
=> Further improve docs for methods + self

doc/Language/operators.pod6
=> Add explanation that != is alias for !==

doc/Language/5to6-perlfunc.pod6
=> Mention importance of closing handles in 5to6

doc/Type/Int.pod6
Attempt to resolve issue #1436.
=> Document the use of polymod for base conversion

doc/Type/Any.pod6
See https://github.com/perl6/doc/issues/1494 for details.
Help is needed with:
=> Attempt to document most of `Any` methods

doc/Type/IO/Socket/Async.pod6
Does simply removing this `if` statement resolve #1538?
=> Does this resolve #1538?

doc/Programs/02-reading-docs.pod6
Adding a new p6 pod description of program p6doc.
=> PR for new program p6doc info is ready

doc/Type/Supply.pod6
Remove Duplicate Code From Supply Migrate Example
=> Remove Duplicate Code From Supply Migrate Example

doc/Language/functions.pod6
=> note multi hiding via non-multi in lexical scope

doc/Language/glossary.pod6, doc/Language/py-nutshell.pod6, doc/Language/syntax.pod6, doc/Language/terms.pod6, doc/Language/unicode_ascii.pod6
I'll merge after (1) a good doc build and (2) no one objects.
=> changes required by changing 'Texas' to 'ASCII'

doc/Language/variables.pod6
https://github.com/rakudo/rakudo/blob/8ff76b5962ed34caa7b66b3f95644410fdb9b17e/src/core/Slang.pm
=> Can find implementation of Slang in rakudo

doc/Type/Signature.pod6
maybe puzzle user: https://irclog.perlgeek.de/perl6/2017-10-10#i_15282583
add example
=> Rewrite intro of alias named signature

doc/Language/operators.pod6
=> Fix broken link to ACCEPTS

doc/Type/Supplier/Preserving.pod6
=> doc Supplier::Preserving

doc/Language/concurrency.pod6, doc/Type/Supplier.pod6, doc/Type/Supply.pod6
=> link to Supplier::Preserving, fixes #1610

doc/Language/objects.pod6
I think it is worth to be searchable
=> Add hook to "Parameterized Roles"

doc/Type/Hash.pod6, doc/Type/Signature.pod6
These aren't big changes, but they jumped out at me as being missing or wrong.
=> Small changes: wrong link, missing :kv, grammar error

doc/Type/BagHash.pod6
=> Improve BagHash.new examples(Close #1629)

doc/Type/IO/Socket/Async.pod6
I'm little bit familiar about using this IO::Socket::Async so I thought to try to resolve this #1627 issue.
I also read about suggestion to put server+client examples to one, but I think is not so good idea for newcomers. Maybe.
=> Fixed server and client examples for IO::Socket::Async

CONTRIBUTING.md, Dockerfile, doc/Type/IO/Socket/Async.pod6
Added Docker way to get tools up and running for contributing
=> Added Dockerfile and instructions to CONTRIBUTING.md

doc/Language/regexes.pod6
Review needed.
Try to close #1550 , #1638
=> Rewrite the document of Longest Alternation: C<|>

doc/Language/modules.pod6
As explained here: https://rakudo.party/post/CPAN6-Is-Here
=> Update ecosystem module upload docs (CPAN).

doc/Type/Mu.pod6
=> link to /routine/gist

assets/sass/style.scss, html/images/External-link-04-bold-12x12.svg, html/images/pencil.svg, htmlify.p6, lib/Pod/Htmlify.pm6, template/header.html
=> Add edit ico

doc/Language/5to6-nutshell.pod6
=> Update 5to6-nutshell.pod6 (mentioned AUTOLOAD/FALLBACK)

CONTRIBUTING.md, doc/Language/5to6-perlfunc.pod6, doc/Language/nativecall.pod6, doc/Language/pod.pod6, xt/code.pws
Adding some elaboration on working with C structs, and a small handfull of test fixes.
=> Docfix manchicken 2017 12 12

doc/Language/variables.pod6
=> Add a link to the binding section

doc/Type/Signature.pod6
this was asked about at https://irclog.perlgeek.de/perl6/2018-01-22#i_15723547
=> 1=>1 vs. a=>1 as named arguments

doc/Type/Range.pod6
See also: https://github.com/perl6/roast/blob/master/S02-types/range.t#L285-L318
=> Add Shifting and scaling intervals section

doc/Language/operators.pod6
Minor comma adjustments. A little rewording to ease readability.
=> Adjust grammar.

doc/Language/nativecall.pod6
Curt Tilmes gave a great addition to a question on perl6 users. I thought it illustrated several parts of NativeCall, so I wrote it up as an example for the NativeCall documentation.
=> c function tutorial added

doc/Type/Range.pod6
Fix #862
However, if there are anyone who feel this one is redundant, feel free to revert it.
=> Add Range.rand

doc/Language/module-packages.pod6, doc/Language/modules.pod6, doc/Language/packages.pod6
These commits add a new language documentation page covering _Module Packages_.
RfC: @niner, @ugexe.
CC: @moritz, @zoffixznet.
=> Document module packages

doc/Language/testing.pod6
To go with https://github.com/rakudo/rakudo/pull/1664
----
Impl     PR: https://github.com/rakudo/rakudo/pull/1664
Propspec PR: https://github.com/perl6/roast/pull/408
=> Document fails-like test routine

doc/Type/Iterable.pod6
Improve the documentation on the hyper and race methods by adding some explanations about
- degree
- batch
=> Hyper race methods: explain batch and degree

doc/Type/Iterable.pod6
This fixes broken link from former PR in hyper / race.
Works now on my localhost:3000 doc. :-)
=> fix broken links

README.md, README.zh.md
=> Translate README for chinese

doc/Language/modules.pod6
=> Fix modules link

doc/Language/regexes.pod6
=> '/ /' and 'rx/ /' clarified purpose of use

README.es.md
README.es.md needed some minor corrections.
Added missing lineabreak and period, removed a typo and translated the languages in the README section to Spanish.
=> Made some minor corrections to README.es.md

doc/Type/Range.pod6
=> hint and and link to set operators from Range

doc/Language/faq.pod6
description just a little too terse
spelled it out a bit more
=> Make the availability of p6doc clearer

doc/Type/Str.pod6
=> Fix a pod directive in .comb

README.es.md
=> Minor changes

doc/Language/grammar_tutorial.pod6
Composing grammars with roles is currently presented as essentially identical to inheritance.  I asked for mention of roles in issue #1816 and feel the clarification will be helpful.
Documentation shows how difference between class and role applies to grammars and provides an example.
=> grammar_totorial.pm6 clarification of extending grammars with roles

doc/Language/js-nutshell.pod6
**DO NOT MERGE YET**
Just looking for some feedback as I write the page.
Fixes #1968
=> WIP: Add Node.js to Perl 6 nutshell page

README.de.md, README.es.md, README.fr.md, README.it.md, README.jp.md, README.md
Made it! I translated the README.md (English) version to a French version (README.fr.md). I also wrote the references of 'README.fr.md' file in the other README versions.
Maybe it is not a perfect translation, but i think everybody can easily understand it!
=> README.fr.md

README.fr.md
My french isn't that good and hasn't been actively used in a while but after googling `exéxutez` still looks like a typo.
=> Update README.fr.md - looks typo to my rusty french

README.pt.md
Tradução do README.md para o português.
=> Create README.pt.md closes #1984

doc/Language/glossary.pod6
=> Add missing right paranthesis

doc/Language/numerics.pod6
=> Fix some typos and wording

doc/Language/5to6-nutshell.pod6, doc/Language/5to6-overview.pod6, doc/Language/5to6-perlfunc.pod6, doc/Language/5to6-perlop.pod6, doc/Language/5to6-perlsyn.pod6, doc/Language/5to6-perlvar.pod6, doc/Language/MIGRATION.pod6, doc/Language/haskell-to-p6.pod6, doc/Language/py-nutshell.pod6, doc/Language/rb-nutshell.pod6
Language pages are not grouped as a newcomer might like.
Providing a simple scheme for adding grouping categories and specific page ordering as children of a category.
=> testing a first cut at a Language grouping

Dockerfile, doc/Language/rb-nutshell.pod6
Also fixed the `Dockerfile` so that `make docker-htmlify` works.
Specifically, I made it no longer purge the `buildDeps` because when
`npm install` in `highlights/`, it needs build-essentials to compile some
native module.
=> Correct and clarify some parts of ruby-to-perl6 nutshell.

doc/Type/IO/CatHandle.pod6, doc/Type/IO/Handle.pod6
POVI (Proof-Of-Viability Implementation): https://github.com/rakudo/rakudo/pull/2081
Spec and SAP: https://github.com/perl6/roast/compare/bf9171b4b447...14dcd028c14c
=> Document IO::[Cat]Handle.READ/.WRITE/.EOF

doc/Language/grammars.pod6
Using attributes in grammars is undocumented.
Document and provide an example using them.
=> Document grammar attributes

Makefile
This way eg. the test progress is shown when running `make
docker-xtest`.
=> run the Docker images interactively & on a tty from the Makefile

doc/Language/rb-nutshell.pod6
=> Fix link to Inline::Ruby

doc/Language/control.pod6
=> Revert "Revert "Update control.pod6""

doc/Language/classtut.pod6
=> Add missing letter

doc/Language/hashmap.pod6
=> Add minor fixes

doc/Language/js-nutshell.pod6
This section of the page was a TODO.
I wrote what needed to be documented.
=> Write networking API section for JS nutshell

doc/Language/traps.pod6
=> Remove period from headings and subheadings and other minor fixes

doc/Language/numerics.pod6, doc/Type/Rational.pod6
POV: https://github.com/rakudo/rakudo/pull/2314
Propspec: https://github.com/perl6/roast/pull/475
=> Normalized ZDRs

doc/Type/Signature.pod6
=> Fixed bad URL

doc/Type/IO.pod6
=> Fix a link

doc/Type/IO.pod6
=> Fixed links to :r, :w, and :x

doc/Language/regexes.pod6
#2230
Attempts to clarify regex interpolation by starting with two examples and a simple explanation.
Leaving in the more complicated examples should people want more.
=> Clarify interpolation section

doc/Language/typesystem.pod6
=> Fix some typos

CREDITS
=> Add credit to credits file

doc/Language/functions.pod6, doc/Type/Signature.pod6
=> Rephase sentence and fix minor typo

doc/Language/py-nutshell.pod6
=> Add some information to the input section

doc/Language/typesystem.pod6
=> Add minor fixes, rephrase sentences and reflow text

doc/Language/unicode_entry.pod6
The options and layout of the options menu has changed in WinCompose
=> Update WinCompose instructions

doc/Type/Kernel.pod6
Requires https://github.com/rakudo/rakudo/pull/2396
=> Document $*KERNEL.hostname

CONTRIBUTING.md
=> whitespace and text reflow

doc/Language/faq.pod6
=> refer to Raku in FAQ

doc/Language/containers.pod6
=> Wording and text reflow

doc/Language/regexes.pod6, doc/Type/Scalar.pod6
Try to close  #2465 and whitespace.
=> Change from list items to lower-level headings and whitespace

doc/Language/exceptions.pod6, doc/Language/objects.pod6
#2468
Just briefly mentioned it since the variable is documented here: https://docs.perl6.org/syntax/$!
=> Mention the $! variable in the 'try blocks' section

doc/Type/IO/Path.pod6
This would close #2474
Please review.
=> Add documentation to the test argument of sub/method dir

doc/Type/IO/Path.pod6, htmlify.p6
https://github.com/perl6/doc/issues/2476
Changing the headers for the table as suggested in the issue mentioned above.
=> Fix for issue #2476

doc/Language/pod.pod6
As discussed in Issue #2495 there are some undocumented but implemented FormatCodes.
The text is slightly adapted from S26.
=> formating codes in pod

doc/Language/py-nutshell.pod6
=> Whitespace and minor improvements

META6.json, README.md
=> bump Pod::To::HTML version

doc/Language/variables.pod6
https://github.com/rakudo/rakudo/pull/2574
=> Add docs on $?DISTRIBUTION

doc/Type/Int.pod6
=> check negative .expmod #2632

doc/Type/Complex.pod6
=> Complex exponentiation involving zeros #2632

doc/Language/js-nutshell.pod6
The control flow section of the JS nutshell was marked TBD
It is now done
=> Document control flow in the JS nutshell

doc/Language/js-nutshell.pod6
The types section of the JS nutshell was marked TBD.
It is now done.
=> Document types in the JS nutshell

doc/Language/hashmap.pod6, doc/Language/terms.pod6, doc/Type/Any.pod6, xt/word-variants.t, xt/words.pws
This PR is a very rough draft to fix #2660.
Feedback welcome, @coke. :)
=> replace 'sigilled' with 'sigiled'

doc/Type/Cool.pod6
Add a necessary dot and make relation before the two subs more bi-directional.
=> Extend uniprop(s) explanation

doc/Language/operators.pod6
See https://github.com/perl6/roast/blob/master/S03-operators/gcd.t
=> Clarify gcd with zero results

doc/Type/List.pod6
=> Revise examples in the intro to lists.

doc/Language/typesystem.pod6
=> Addressing #2710 - First draft

doc/Language/operators.pod6, doc/Language/setbagmix.pod6
Addresses #2761 and sets the ground work for #2603
=> Operators and SetBabMix page updates

type-graph.txt
=> Failure is Nil

doc/Language/statement-prefixes.pod6, doc/Language/subscripts.pod6
=> Remove spaces around operators and reflow

doc/Language/list.pod6, doc/Language/subscripts.pod6, doc/Type/Range.pod6
cf. rakudo/rakudo#2872 and perl6/roast#536
=> Fix infinite range subscript examples

doc/Type/Setty.pod6
=> document antipairs for Setty

doc/Type/Map.pod6
Add list method in Map documentation
=>  Add list method in Map documentation

doc/Language/exceptions.pod6, doc/Language/pragmas.pod6, doc/Type/Bag.pod6, doc/Type/BagHash.pod6, doc/Type/Blob.pod6, doc/Type/Buf.pod6, doc/Type/Mix.pod6, doc/Type/MixHash.pod6, doc/Type/Parameter.pod6, doc/Type/Set.pod6, doc/Type/SetHash.pod6, doc/Type/Signature.pod6, doc/Type/X/Control.pod6, doc/Type/X/Method/NotFound.pod6
=> Update for 2019.03

doc/Type/Any.pod6
Return value Seq consistent defined with commit https://github.com/rakudo/rakudo/commit/d73272e4c0f3d92ed82008eb366cfe756ae0c39b#diff-0bf1cf4b83dbeb7a105cd2e64f48fc44
=> Adapt documentation for pairup 

doc/Type/Any.pod6
Make it more consistent to current implementation and other parts of Any doc (antipairs).
=> Make pairup doc more consistent.

doc/Language/modules.pod6
=> Add minor rewording

doc/Language/operators.pod6, doc/Language/phasers.pod6
Examples for 6.d checklist https://github.com/perl6/doc/issues/2632
=> Examples for 6.d checklist

doc/Language/faq.pod6
=> Add minor rewording and C<>-tag some keywords

doc/Language/faq.pod6
I've corrected my name in the FAQ.
=> Fix brian's name

doc/Language/modules.pod6
=> minor typo & grammar changes

doc/Language/operators.pod6
=> Clarify infix Z behavior

doc/Language/regexes.pod6
=> Minor corrections to regexes section

doc/Language/community.pod6
- Added offline communities
- Restructured text so each line has exactly one sentence, so translating based on diffs becomes easier
=> Restructuring of text & mention offline communities

doc/Language/about.pod6, doc/Language/community.pod6, doc/Language/faq.pod6, doc/Language/tables.pod6
about.pod6, community.pod6, faq.pod6 and tables.pod6
Changes include minor rewording, text reflow, replacing indented code samples
with =code directives-wrapped code samples, order book list in [faq.pod6](https://docs.perl6.org/language/faq#Can_I_get_some_books_about_Perl_6?) alphabetically, etc.
=> Proofread several documents

doc/Language/regexes.pod6
This is a first attempt to fix #2599 and #2230
Clarification of the various interpolation constructs.
=> Rewrite of regex interpolation section

doc/Language/create-cli.pod6, doc/Language/exceptions.pod6, doc/Language/experimental.pod6, doc/Language/functions.pod6, doc/Language/io-guide.pod6, doc/Language/io.pod6, doc/Type/Sub.pod6
Changes mostly involve text reflow, whitespace and correcting minor typos.
=> Proofread some documents

doc/Language/regexes.pod6
=> tidy grammar

doc/Type/independent-routines.pod6
=> - MInor changes to independent-routines.pod6 to clarify options for run()

doc/Language/rb-nutshell.pod6
Ruby examples are slightly off and/or incorrect.
=> Ruby fixes

doc/Language/mop.pod6
=> Remove extra word and add relevant links

doc/Language/modules.pod6, doc/Language/variables.pod6
https://github.com/perl6/doc/issues/2240
Documented it. Please, __review__ it.
=> Document resources

doc/Language/101-basics.pod6
trivial formatting error and proposed fix.
=> Fix formatting

resources/i18n/de/README.de.md
Replace Perl_6 with Raku to be more consistent with the English version
=> Replace Perl_6 with Raku

doc/Language/functions.pod6
Mention the right function in nextwith() example.
=> Fix function name in example

doc/Language/setbagmix.pod6
=> Place C<> around operator and types

doc/Language/nativecall.pod6
=> Place C<> around types. Also Perl -> Raku

doc/Type/CompUnit/PrecompilationRepository.pod6
Issue #3043 
Documentation taken from PrecompilationRepository.pm6
The class is an interface and follows Jonathan's design document.
=> PrecompilationRepository document

t/02-pod-valid.t
=> "Pod 6" -> "Pod6"

resources/i18n/pt/README.pt.md
Caveat-ed with I don't speak, read, or write Portugese, but these seemed pretty straightforward changes.
=> "Raku Pod" -> "Raku Pod6" and "Pod 6" -> "Pod6"

doc/Language/operators.pod6
=> Expansion of Operator precedence and Assignment operators sections

doc/Language/regexes.pod6, doc/Language/statement-prefixes.pod6
=> Fix some links to Language pages

doc/Language/nativecall.pod6
Also clarify when/why this is necessary.
Closes #3169
=> Add NUL byte in NativeCall example

doc/Type/Seq.pod6, doc/Type/Sequence.pod6, type-graph.txt
Role Seq does role Sequence, role Sequence does role PositionalBindFailover and method eager is implemented by role Sequence.
=> Correct type graph of role Seq

doc/Type/Sequence.pod6
This should resolve issue #2918
=> Complete documentation of role Sequence

doc/Language/objects.pod6
=> Mention that the colon syntax on $.foo method is now supported

doc/Type/Str.pod6
=> Document Str.Version

doc/Type/Cool.pod6, doc/Type/Numeric.pod6
=> Add log2 subroutine and method

doc/Type/Supply.pod6
Document Supply.repeated
Ref #3187
=> Add Supply.repeated

doc/Type/Supply.pod6
Document Supply.first. Ref #3187
=> Add Supply.first

doc/Language/control.pod6, xt/code.pws
This is a pattern I sometimes use that I figure would be worth documenting.
=> Document how `when` can be used in `for` loops

doc/Language/5to6-nutshell.pod6
=> chg p6 to raku

doc/Language/5to6-perlfunc.pod6
=> chg pe6 to raku

doc/Type/Attribute.pod6
Reference: [2020.01](https://github.com/rakudo/rakudo/releases/tag/2020.01)
=> Partially document the 'is built' trait

doc/Type/Array.pod6
=> Add example for Callable/Whatever in splice

doc/Language/objects.pod6
=> Add small section about delegation

doc/Type/Blob.pod6
=> Document classes blob8, blob16, blob32 and blob64

doc/Type/Buf.pod6
=> Buf.list() now returns a List

doc/Type/List.pod6
Issue: https://github.com/Raku/doc/issues/3156
=> Mention immutability of lists on the List page

doc/Type/Blob.pod6, doc/Type/Buf.pod6
=> clarify Buf.list() and Blob.list() return value's type

CONTRIBUTING.md, util/perl-nbsp.p6, writing-docs/STYLEGUIDE.md
=> Rename: Perl 5 -> Perl (util) (3/6)

doc/Type/X/Syntax/P5.pod6, doc/Type/X/Syntax/Perl5Var.pod6, doc/Type/independent-routines.pod6
=> Rename: Perl 5 -> Perl (doc/Type) (4/6)

doc/Language/modules.pod6, doc/Language/performance.pod6, doc/Language/pragmas.pod6, doc/Language/regexes.pod6, doc/Language/system.pod6, doc/Language/variables.pod6
Issue #3091
Final PR (issue can be closed if I worked well)
I divided the PR in 6 small ones, easier to integrate (see discussion here 3272)
=> Rename: Perl 5 -> Perl (Language) (6/6)

doc/Language/101-basics.pod6, doc/Language/about.pod6, doc/Language/classtut.pod6, doc/Language/faq.pod6, doc/Language/traps.pod6
=> Rename: Perl 5 -> Perl (about) (5/6)

doc/Language/5to6-nutshell.pod6, doc/Language/5to6-overview.pod6, doc/Language/5to6-perlfunc.pod6, doc/Language/5to6-perlop.pod6, doc/Language/5to6-perlsyn.pod6, doc/Language/5to6-perlvar.pod6
=> Change Perl 5 to Perl (1/6)

doc/Type/Parameter.pod6, doc/Type/Str.pod6
=> Document that Str.contains now also can take a Regex

doc/Language/functions.pod6, xt/code.pws, xt/words.pws
For a long time, I didn't really understand how proto/multi signatures interacted with each other, and proto bodies being a feature at all was something I missed when first skimming over the functions page. It's really useful one!
Explain when proto bodies are useful and document how proto/multi signatures interact with each other, using proto bodies again in its example to make it harder to miss.
=> Add more documentation on proto bodies and proto/multi signatures

doc/Type/Signature.pod6
The documentation on this is unclear.
Explain in terms of variables rather than symbols, mention why the example given is given, and show how the example is used.
=> Clarify documentation on aliases for anonymous arguments

doc/Language/faq.pod6
The easiest possible fix for : #3259
=> Fix URL: language -> *.html

doc/Language/faq.pod6
Add common operations as specified here #3109 (1/5)
=> Faq: string common operations

doc/Language/regexes.pod6
Issue: #3220
Add the following to index
```raku
$variable
$(code)
<$variable>
<{code}>
<?{}>
<!{}>
<?>
<!>
<?before>
<?after>
```
=> Feature: Index regex interpolation tokens

doc/Language/modules.pod6
=> Perl 6 extensions -> Raku extensions

doc/Language/objects.pod6, xt/words.pws
=> Document sigiled method calls

doc/Language/glossary.pod6, xt/words.pws
=> Add type smiley to the glossary

util/xt-recent.sh
=> Do not use a local(?) git alias

doc/Type/Compiler.pod6
=> Add Compiler.backend()

doc/Type/Str.pod6
=> Document Str's .starts-with and .ends-with ignorecase/ignoremark

doc/Type/Str.pod6, xt/code.pws
=> Document Str.substr-eq ignorecase/ignoremark

doc/Type/Str.pod6, xt/code.pws
=> Document Str.indices ignorecase/ignoremark

Makefile
=> remove references to removed make targets

doc/Language/modules.pod6, doc/Language/pragmas.pod6
add example for `use lib` with `IO:Path`
=> example for use lib with IO:Path

writing-docs/EXAMPLES.md, xt/examples-compilation.t
Following #3309 we could consider a test like the following.
But it may be considered a bit drastic. :-}
=> Test for discouraged usage of .perl in sample code

doc/Language/numerics.pod6
change 1e0.perl to 1e0.raku
example use .perl method
change them to .raku
=> change perl method to raku method

Makefile
- remove broken targets: 'bigpage', 'epub'
- make 'html' target working again
- update 'help' target "text"
- remove now unneeded targets: 'clean-build', 'remove-build'
- introduce 'clean-cache' target
- make 'distclean' target more thorough
- remove references to long gone target 'html-nohighlight'
- tentatively add dependencies to 'for-documentable' target
hence make 'html' target depends on it
- avoid forking to set SELINUX_OPT
- remove unused variables: LANG_POD6_SOURCE, USE_CATEGORIES
XXX util/travis-test.sh references long gone targets as well
as a target removed by this commit... It probably needs some
attention
=> Clean up/improve Makefile

doc/Type/Map.pod6
while here use "common" output style
=> Fix pasto in example comment

xt/routine-definitions.t
=> Add test for routine header vs routine definitions

doc/Type/Mu.pod6
=> Mention .raku method instead of .perl method

doc/Type/independent-routines.pod6
File affected:
+ doc/Type/independent-routines.pod6
=> Modify and clarify routine sprintf details

doc/Type/Array.pod6, doc/Type/CallFrame.pod6, doc/Type/IO/Path/Win32.pod6, doc/Type/Nil.pod6, doc/Type/Pair.pod6, doc/Type/Seq.pod6
=> Change .perl to .raku in documents

doc/Type/Numeric.pod6
=> Change .perl to .raku in examples in doc/Type/Numeric.pod6

doc/Language/glossary.pod6
=> Make glossary entries consistent

doc/Language/pod.pod6
=> Fix formatting in doc/Language/pod.pod6

doc/HomePage.pod6
The 1-file HTML is currently broken, but we havn't done anything to let the readers know that.
Disable the link and adds a link to #1981 .
=> Disable link to the broken 1-file HTML

doc/Language/typesystem.pod6
This form can be guessed but we don't want to leave any user guessing.
=> show that substition works in enum subsript syntax

doc/Language/typesystem.pod6
=> Index :api and add bit of documentation

resources/i18n/zh/README.zh.md
=> Update Chinese translation

doc/Language/control.pod6
=> Minor rewording with few examples

doc/Type/Cool.pod6, doc/Type/Str.pod6
=> Document several index/rindex's needles feature

doc/Type/Str.pod6
Documents:
https://github.com/rakudo/rakudo/commit/1bcc5d73e3433badcdcb8b981a805cae9e84466d
=> Type::Str.lines: document new :$chomp parameter

doc/Language/functions.pod6
=> Add few examples for named arguments as adverbs

doc/Type/Any.pod6, doc/Type/List.pod6
=> Clarify description of reduce sub/method for Any and List

doc/Type/Capture.pod6
=> Revise the Capture page

doc/Type/Signature.pod6
=> Extend documentation on typed lambdas

doc/Type/Supply.pod6
ref #3187 (I forgot to mention it in the commit log)
=> Add Supply.collate

doc/Type/Block.pod6
=> $_ defaults to OUTER::<$_>

doc/Language/traits.pod6, doc/Type/Code.pod6
Resolves a point for https://github.com/Raku/doc/issues/3360 and closes https://github.com/Raku/doc/issues/3485
=> Document is impl trait

doc/Type/Pod/Block/Code.pod6
=> Remove documentation for (nonexistent) `allowed` method

doc/Type/Proc/Async.pod6
https://github.com/rakudo/rakudo/blob/master/src/core.c/Proc/Async.pm6#L307
=> update method start for Proc::Async

doc/Type/Supply.pod6
=> Add Supply.split

doc/Type/Mix.pod6, doc/Type/MixHash.pod6
- mention <> postcircumfix
- add ref to operators' description
=> More on { } and < > operators for Mix and MixHash

doc/Language/operators.pod6, doc/Language/subscripts.pod6, doc/Type/Bag.pod6, doc/Type/BagHash.pod6, doc/Type/Baggy.pod6, doc/Type/List.pod6, doc/Type/Mix.pod6, doc/Type/MixHash.pod6, doc/Type/QuantHash.pod6, doc/Type/Set.pod6, doc/Type/Setty.pod6
=> Tweak examples' output for current rakudo behavior

doc/Type/List.pod6
And while here, if we would like an example to produce an output,
we might as well call `say` :)
=> Uniformize examples' output

xt/aspell.t
Includes instructions for both Mac and Linux. closes  #3597
=> Add instructions for aspell installation/updating

xt/pws/code.pws, xt/pws/words.pws
- remove duplicated word
- sort words list
- fold case
=> placate xt/words.t

xt/pws/words.pws, xt/word-variants.t
This fix spell checks on doc/Type/Distribution/Resource.pod6
=> Add a new word and a word variant exception

doc/Language/operators.pod6
while here add output to an example for this operator
=> document sequence operator variants ^... and ^...^ ref #3360

doc/Type/Seq.pod6
while here document the various way to build a Seq at the
start of the document.
=> mention the sequence operator

doc/Language/community.pod6
Missing closing square bracket
Closed square bracket
=> Missing closing square bracket

doc/Language/nativecall.pod6
This PR adds examples that will illustrate several "oh gee, I didn't know it could do that" problems. I am submitting them to the locations where I checked for such information ... and didn't find it.
=> Adds Examples for Underutilized Features: Delegation / CArray Subarrays

doc/Language/haskell-to-p6.pod6
Just a typo.
Just corrected.
But by the way, I see no reason for Tail call elimination section if there is nothing to say about it. Maybe just to remove the section instead of typo fix?
=> Correct typo

doc/Language/create-cli.pod6
The option was recently added and will be released in 2020.10.
=> Document `%*SUB-MAIN-OPTS<bundling>`

doc/Programs/03-environment-variables.pod6, xt/headings.t, xt/pws/words.pws
Now it successfully runs `make test`.
Fixes #3682
=> Fix test errors in `doc/Programs/03-environment-variables.pod6`

doc/Type/List.pod6
ref #3495
While here flesh out a bit the routine description and adopt a more
common example style.
=> List.rotate returns a Seq since Rakudo 2020.06

doc/Type/IO/Spec.pod6, doc/Type/IO/Spec/Cygwin.pod6, doc/Type/IO/Spec/QNX.pod6, doc/Type/IO/Spec/Unix.pod6, doc/Type/IO/Spec/Win32.pod6
While here uniformize introduction to these classes
=> Fix IO::Spec::* parent class

doc/Type/IO/Path.pod6, doc/Type/IO/Path/Parts.pod6, doc/Type/IO/Spec/Cygwin.pod6, doc/Type/IO/Spec/Unix.pod6, doc/Type/IO/Spec/Win32.pod6, type-graph.txt
... and its relation with IO::Path and IO::Spec::*
=> Document IO::Path::Parts

doc/Type/Any.pod6, doc/Type/Array.pod6, doc/Type/Hash.pod6, doc/Type/independent-routines.pod6
I would like some feedback to find out if I'm on the right track.
=> Update documentation of pop, shift, push, append

doc/Language/testing.pod6
=> Test env vars

doc/Type/Parameter.pod6
This also covers part of  #3580
=> Document Parameter.usage-name

doc/Type/Parameter.pod6
.. for a better learned experience I hope :)
=> Rework Parameter.type_captures example

doc/Type/Test.pod6
=> Document Test.done-testing's return value

doc/Language/traps.pod6
Closes https://github.com/Raku/doc/issues/3721
The trap example code was incomplete and confused the reader.
Make it more complete.
=> De-trap a trap's description

doc/Type/Metamodel/PrivateMethodContainer.pod6
=> Document several metamethods

doc/Language/grammar_tutorial.pod6, doc/Language/iterating.pod6, doc/Language/list.pod6, doc/Language/newline.pod6, doc/Language/objects.pod6, doc/Language/regexes.pod6, doc/Type/Any.pod6, doc/Type/Associative.pod6, doc/Type/Compiler.pod6, doc/Type/Grammar.pod6, doc/Type/IO/Handle.pod6, doc/Type/IO/Path.pod6, doc/Type/Junction.pod6, doc/Type/PseudoStash.pod6, writing-docs/STYLEGUIDE.md
And sync styleguide with this commonly adopted style
=> Uniformize example output style

doc/Language/typesystem.pod6
.. to avoid duplicated and slightly out of date method
description
=> Link to Enumeration role documentation

writing-docs/EXAMPLES.md
... and be consistent about it in the given examples
=> Add a note about code block initial indentation

doc/Language/modules.pod6
=> mention fez in the dist ecosystem contribution

doc/Type/Lock.pod6
This PR matches [this PR](https://github.com/rakudo/rakudo/pull/4228) in Rakudo.
=> Added predicated ConditionVariable::wait

doc/Language/regexes.pod6
=> use correct word

doc/Language/modules-core.pod6
correct path to actually existing file
404 error in Raku docs
correct the path to existing file. (File is pm6 not rakumod)
=> correct path in link remove 404

doc/Language/numerics.pod6
This is not an obvious mistake. From the link it seems to point at a different file. Since this is a judgment call, I'm flagging my correction for review.
=> related to #3841

doc/Type/Any.pod6
simplify the X<> for $*COLLATION
=> See #3841 #3857

doc/Language/packages.pod6
There was discussion of this and I caused a conflict by editing twice. Here it is again
=> interpolate using wikipedia link (resubmission)

resources/i18n/zh/README.zh.md
Wrong link in Chinese translation .md
Use link instead of raw text
=> Update link in Chinese translation

doc/Language/py-nutshell.pod6
Do a minimal change as suggested in https://github.com/Raku/doc/commit/4cb25dbd56256a67c36c479ad2649936b73da106
=> Fix tuple-like structure in Raku

doc/Language/5to6-perlfunc.pod6
<...> was code quoted twice
removed the in-line quoting
=> minor fix: code quote within code quote

assets/documentable.json, assets/js/main.js, doc/Language/community.pod6, doc/Language/faq.pod6, doc/Language/glossary.pod6, doc/Language/modules.pod6, doc/Language/performance.pod6, doc/Type/IO/CatHandle.pod6, documentable.json, html/.htaccess, writing-docs/SQUASHATHONS.md, writing-docs/STYLEGUIDE.md, xt/pws/words.pws
Made a PR instead of committing directly so someone more authoritative can pull the trigger when we decide the time is right, as the Whateverable bots (and probably some other things and people) aren't yet migrated at the time of this writing
=>  Move from freenode to libera.chat

doc/Type/Cool.pod6, doc/Type/Str.pod6
... and state that Cool.samecase uses it.
=> Document Str.samecase

doc/Type/Numeric.pod6, doc/Type/Real.pod6
... and remove non-existent Numeric.{Int,Num,Real} ones
=> Add Real.{Int,Num,Rat} coercers ref #3782

doc/Type/Mu.pod6
=> Add back Mu.perl and tweak Mu.raku

doc/Language/packages.pod6
No example shown of interpolating and using a subroutine.
This PR aims to provide that example.
=> Provide a practical example of interpolating package names

doc/Language/packages.pod6
=> Pkg interp: complete example, improve var names

doc/Language/typesystem.pod6
=> Clarify effect of 'is required' on a private attribute

doc/Language/classtut.pod6, doc/Language/objects.pod6
Refs: https://github.com/Raku/doc/issues/3521
=> Add clarification about private methods

xt/aspell.t
This PR changes xt/aspell's output from a full list of all the suggestions aspell has for a word (frequently many lines of terminal output) and into a formatted list of misspelled words.
Before:
```
Thor, Thur, thaw, Tahoe, Thule, thane, thees, theme, there, these, thief, thine, thole, those, three, \
threw, throe, thyme, Thu, hie, hoe, hue, tho, thy, THC, shh, Thai, thaa, thou, Th's, Thad, than, \
that, thid, thin, this, thru, thud, thug, thus, therm, thews, Thanh, her, hew, hey, huh, thigh, Thoth, \
thither, their, H, h, theta, Huey, hoer, HI, Ha, Ho, ha, hi, ho, ddthh, thew's, Thea's, they'd
not ok 1 - doc/Language/containers.pod6 (text) has 1 spelling errors
```
After:
```
```
=> Minor tweak to make xt/aspell's output better/less verbose

doc/Language/faq.pod6
=> Update the ecosystem FAQ

doc/Language/modules.pod6
information about how to distribute modules is out of date
updates info about how to distribute a module
This is the same PR as #4008 which was accidentally obliterated by me.
=> Update information about methods for distributing modules

doc/Language/exceptions.pod6
In response to https://github.com/Raku/doc/issues/4049
=> Some tweaks on CATCH

doc/Language/5to6-perlfunc.pod6, doc/Language/5to6-perlvar.pod6, doc/Language/concurrency.pod6, doc/Language/control.pod6, doc/Language/faq.pod6, doc/Language/objects.pod6
Part of https://github.com/Raku/doc/issues/4055
=> Replace "Foreign" with "Other languages" category

CONTRIBUTING.md, writing-docs/INDEXING.md
An attempt to close https://github.com/Raku/doc/issues/4056
=> Explain new policy of index item categories

doc/Language/grammars.pod6, doc/Type/Hash.pod6, doc/Type/IO/CatHandle.pod6, doc/Type/IO/Handle.pod6
Simple typos, misphrasings, and punctuation errors.
With problems little problems like these,  I think thirty changes would be a reasonably size pull request.   Absent feedback, I'll roughly double the count over the next two PRs to twenty.
Thanks.
=> Simple typos, misphrasings, and punc

doc/Language/operators.pod6
=> Make &[max] and &[min] return LHS for ties

doc/Language/io-guide.pod6
No existing practical example of file path analysis.
An example is added.
=> Add example of file path analysis

doc/Language/variables.pod6
The current example is categorized as not safe.
Provide a practical, hopefully safe, example.
=> Add a practical example of augmenting class IO::Path

doc/Type/Iterator.pod6
Iterator.is-deterministic was not documented.
It is now
=> Document Iterator.is-deterministic

doc/Type/Mixy.pod6
Potential fix for D#2205 https://github.com/perl6/doc/issues/2205
pending resolution of https://github.com/rakudo/rakudo/issues/2109
This was created by @zoffixznet some time ago. Before deleting, I guess it's fair to give it a chance to be reviewed.
It's take it or leave it, we accept it as is (and then change whatever) or we reject it and the branch is deleted.
=> Document Mixy.pick/.grab/.kxxv

doc/Language/glossary.pod6
Closes https://github.com/Raku/doc/issues/4127.
This is my first PR in this repo; as I'm quite a newb to pod6, please check if I'm not doing it all wrong. :)
=> Fix the link of "arity" at Multi-dispatch section

doc/Language/classtut.pod6
The current docs do not show a practical, simple, and safe example of the use and implementation of class introspection. 
This PR attempts to rectify the problem by including such an example at the end of the *Classes and objects* tutorial.
=> Add a practical example of class introspection

doc/HomePage.pod6
Make glossary more accessible.
(@coke, thanks for the bit of education.  This kid is going to try that at home first.)
=> Put glossary ref on HomePage.pod6

doc/Language/objects.pod6
+ provide more practical examples
+ add a cross-reference link so the curious can find the discussion
=> Improve discussion and examples of programmatically using class method names

doc/Language/glossary.pod6
I added another 6guts blog link that I found particularly useful about the topic - probably more useful than its prequel. Also "deseriousalized" the chat discussion: it's clearly cute and funny if you already kind of grasp the topic but perhaps a newcomer shouldn't take it too seriously, that wouldn't seem good PR. :v
=> NFG link modifications

doc/Language/modules.pod6, doc/Language/traps.pod6
(I didn't see the need for detailing `CompUnit::Repository::FileSystem`)
=> Document potential performance penalties for filesystem repos (#2199)

doc/Language/traps.pod6
Relates to #2199 and comments on #4231.
=> Clarify the role of META6.json in filesystem repos

doc/Language/tables.pod6
Issue #4202 required the humerous subtitle be updated.
This PR replaces humorous text with expository text.
=> Change humorous text to technical exposition

Makefile
The minimum we should be running is 'test'
Triggered by #3935
=> Remove ctest target

README.md, writing-docs/EXAMPLES.md, writing-docs/README.md, writing-docs/TESTING.md
This will close #3935 but includes other cleanup as well.
=> Cleanup READMEs.

resources/i18n/de/README.de.md, resources/i18n/es/README.es.md, resources/i18n/fr/README.fr.md, resources/i18n/it/README.it.md, resources/i18n/jp/README.jp.md, resources/i18n/nl/README.nl.md, resources/i18n/pt/README.pt.md, resources/i18n/zh/README.zh.md, t/02-pod-valid.rakutest, t/03-tests-valid.rakutest, util/github-action-test.sh, writing-docs/EXAMPLES.md, xt/examples-compilation.rakutest
`P6_DOC_TEST_VERBOSE` → `RAKU_DOC_TEST_VERBOSE`, `P6_DOC_TEST_FUDGE` → `RAKU_DOC_TEST_FUDGE`.
=> Rename `P6_DOC_TEST_*` environment variables

doc/Type/Buf.rakudoc
=> Cleanup examples and some text

doc/Language/objects.rakudoc, doc/Type/Hash.rakudoc
The length of a vector (2,3) is most definitely not 6.
Change the numbers to give nice integral values, with the correct output.
=> Fix example output

doc/Language/operators.rakudoc
Commas got into the last two lines of some nice work.
=> Inconsistent commafication in precedence table

doc/Language/operators.rakudoc
=> Fix andthen/notandthen link

doc/Type/CompUnit/Repository/FileSystem.rakudoc
See: https://github.com/rakudo/rakudo/pull/5279
=> Document CURFS extensions

doc/Type/Proc.rakudoc
See https://github.com/Raku/doc-website/issues/270
=> fix broken shell link

doc/Programs/03-environment-variables.rakudoc
See: https://github.com/rakudo/rakudo/pull/5295
=> Document RAKUDO_NO_PRECOMPILATION

doc/Language/variables.rakudoc
=> Show how to access the %?RESOURCES variable in run-time code

doc/Type/Bool.rakudoc
Dunno if I should just be committing changes like this...
=> Fix codos in `pick` signatures in Bool.rakudoc

doc/Language/variables.rakudoc
+ Add examples to accompany the descriptions
=> Clarify use of the '$?DISTRIBUTION.ver' (and '.content') methods

doc/Language/control.rakudoc
Resolves https://github.com/Raku/doc/issues/4383
=> More practical example for the redo statement

doc/Type/Numeric.rakudoc
url is not complete
add appropriate url
=> missing links - Update Numeric.rakudoc

doc/Language/REPL.rakudoc, doc/Language/faq.rakudoc, doc/Language/unicode_entry.rakudoc, doc/Language/variables.rakudoc, doc/Programs/03-environment-variables.rakudoc, doc/Programs/04-running-raku.rakudoc, doc/Type/independent-routines.rakudoc, xt/pws/words.pws
=> First pass at Languages/REPL

doc/Type/IO/Socket/Async.rakudoc
https://github.com/Raku/doc/issues/3979
=> (Async.rakudoc) Improve example to work on modern browsers

doc/Language/numerics.rakudoc
=> Add examples of non-Allomorph transformations

doc/Language/signatures.rakudoc
This PR brings in the "final prePR" text from Issue #4493 
New Doc Content Request - Detecting Omitted Arguments
=> Add Detecting Omitted Arguments

doc/Language/functions.rakudoc
nextcallee was not explained in terms of a) whether it needed parameters, and b) whether it ever returned.  
- Answered both those questions
- Provided a handy table of the call/next same/with tools
=> Improve documentation for nextcallee

doc/Type/IO/Socket.rakudoc
This depends on https://github.com/rakudo/rakudo/pull/5604
=> Document IO::Socket::recv(:bin) caveat

doc/Language/control.rakudoc
=> Demonstrate succeed returns a value

doc/Language/5to6-nutshell.rakudoc, doc/Language/5to6-perlfunc.rakudoc, doc/Language/5to6-perlop.rakudoc, doc/Language/5to6-perlsyn.rakudoc, doc/Language/5to6-perlvar.rakudoc, doc/Language/glossary.rakudoc, doc/Language/haskell-to-p6.rakudoc, doc/Language/list.rakudoc, doc/Language/modules.rakudoc, doc/Language/performance.rakudoc, doc/Language/rb-nutshell.rakudoc, doc/Language/regexes.rakudoc, doc/Language/syntax.rakudoc
[gist of report with link checks](https://gist.github.com/finanalyst/c676034b4f09b0f7621b9d4ee4848955#file-report-changes-with-internal-targets-md) [gist of internal links that do not work](https://gist.github.com/finanalyst/8323598b46113a0c429bdf7cf0b41457#file-failing-internal-links-md)
=> see issue #4540 remaining files

doc/Language/operators.rakudoc
=> Delete unused line from example.

doc/Language/terms.rakudoc
Add link to term time to new term nano.
=> Add link to term time to new term nano

doc/Language/regexes.rakudoc, doc/Language/slangs.rakudoc, doc/Language/variables.rakudoc, xt/pws/code.pws, xt/pws/words.pws
I can never figure out how to write slangs, due to a) lack of documentation, and b) being unable to find the main grammar so that I know what to modify
I wrote some initial documentation.  No doubt it will need expansion, especially in the sections for "The Slang Grammar" and "The Slang Actions", but I thought I'd leave them to someone more qualified, whether that's future me, or someone else from the community.  
* About 5% is copy-paste from https://docs.raku.org/language/variables#The_~_twigil
* About 50% is copy-paste from @lizmat 's repos, Slangify and Slang::Lambda
I wasn't sure what to do about the duplication; possibly the first link can just link here; the second should be fine as-is, due to the commentary provided.
=> Added initial revision of Slangs tutorial

doc/Language/5to6-perlfunc.rakudoc
The map function didn't work exactly the same, as promised.
Changed the promise (by adding more explanation of differences).
=> Added some more examples of the differences in the map function

README.md
The existing para., at a quick glance, doesn't seem to refer to the current page and repo.
Change the wording in para 3 to ensure the reader knows which repo is being discussed.
=> Clarify the message in para 3.

README.md
"Deutsch" is what's natural to use here. (German is my first language.)
=> In README.md, change "Deutsche" → "Deutsch"

doc/Language/setbagmix.rakudoc
Missing ASCII examples for the Unicode Set, Bag, and Mix operators
Addresses issue #4649
This PR.
=> Fix setbagmix
